import Foundation

extension WordList {

    // MARK: - Words

    static let dogaWords: [WordEntry] = [
        WordEntry(word: "AÇIK DENİZ", category: "Doğa"),
        WordEntry(word: "ADA",        category: "Doğa"),
        WordEntry(word: "AKARSU",     category: "Doğa"),
        WordEntry(word: "BOĞAZ",      category: "Doğa"),
        WordEntry(word: "BOZKIR",     category: "Doğa"),
        WordEntry(word: "BUHAR",      category: "Doğa"),
        WordEntry(word: "BUZUL",      category: "Doğa"),
        WordEntry(word: "ÇAĞLAYAN",   category: "Doğa"),
        WordEntry(word: "ÇAYIR",      category: "Doğa"),
        WordEntry(word: "ÇÖL",        category: "Doğa"),
        WordEntry(word: "DAĞ",        category: "Doğa"),
        WordEntry(word: "DELTA",      category: "Doğa"),
        WordEntry(word: "DENİZ",      category: "Doğa"),
        WordEntry(word: "DEPREM",     category: "Doğa"),
        WordEntry(word: "DORUK",      category: "Doğa"),
        WordEntry(word: "FIRTINA",    category: "Doğa"),
        WordEntry(word: "GÖK",        category: "Doğa"),
        WordEntry(word: "GÖKKUŞAĞI",  category: "Doğa"),
        WordEntry(word: "GÖL",        category: "Doğa"),
        WordEntry(word: "GÖLET",      category: "Doğa"),
        WordEntry(word: "HORTUM",     category: "Doğa"),
        WordEntry(word: "IRMAK",      category: "Doğa"),
        WordEntry(word: "KANYON",     category: "Doğa"),
        WordEntry(word: "KAR",        category: "Doğa"),
        WordEntry(word: "KASIRGA",    category: "Doğa"),
        WordEntry(word: "KITA",       category: "Doğa"),
        WordEntry(word: "KOY",        category: "Doğa"),
        WordEntry(word: "KUMSAL",     category: "Doğa"),
        WordEntry(word: "KÖRFEZ",     category: "Doğa"),
        WordEntry(word: "LAGÜN",      category: "Doğa"),
        WordEntry(word: "MAĞARA",     category: "Doğa"),
        WordEntry(word: "MERA",       category: "Doğa"),
        WordEntry(word: "MERCAN",     category: "Doğa"),
        WordEntry(word: "NEHİR",      category: "Doğa"),
        WordEntry(word: "OKYANUS",    category: "Doğa"),
        WordEntry(word: "ORMAN",      category: "Doğa"),
        WordEntry(word: "PLATO",      category: "Doğa"),
        WordEntry(word: "SİS",        category: "Doğa"),
        WordEntry(word: "STEP",       category: "Doğa"),
        WordEntry(word: "ŞELALE",     category: "Doğa"),
        WordEntry(word: "TEPE",       category: "Doğa"),
        WordEntry(word: "TUNDRA",     category: "Doğa"),
        WordEntry(word: "UÇURUM",     category: "Doğa"),
        WordEntry(word: "VADİ",       category: "Doğa"),
        WordEntry(word: "VOLKAN",     category: "Doğa"),
        WordEntry(word: "YANARDAĞ",   category: "Doğa"),
        WordEntry(word: "YARIMADA",   category: "Doğa"),
        WordEntry(word: "YAĞMUR",     category: "Doğa"),
        WordEntry(word: "ZİRVE",      category: "Doğa"),
    ]

    // MARK: - Hints

    static let dogaHints: [String: String] = [
        "ADA":          "Her tarafı suyla çevrili kara parçası.",
        "AKARSU":       "Kaynaktan denize doğru akan küçük nehir ya da dere.",
        "BOĞAZ":        "İki denizi birbirine bağlayan dar su geçidi.",
        "BOZKIR":       "Ağaçsız, kurak, otsu bitki örtüsüyle kaplı geniş düzlük.",
        "BUZUL":        "Yüzyıllar boyunca biriken kardan oluşan, yavaş akan dev buz kütlesi.",
        "ÇAĞLAYAN":     "Dağlık araziden hızla akan, çağıltılı küçük şelale.",
        "ÇÖL":          "Yağışın son derece az, bitki örtüsünün neredeyse yok olduğu kurak alan.",
        "DAĞ":          "Çevresinden yüksek çıkıntı yapan, zirvesiyle gökyüzüne uzanan kara kütlesi.",
        "DELTA":        "Nehrin denize ya da göle döküldüğü yerde oluşan toprak parçası.",
        "DENİZ":        "Okyanusun kara içine girdiği, daha küçük tuzlu su kütlesi.",
        "DEPREM":       "Yer kabuğunun ani hareketleriyle oluşan, sarsıntıya neden olan doğa olayı.",
        "FIRTINA":      "Güçlü rüzgar, yıldırım ve şiddetli yağışla birleşen hava olayı.",
        "GÖKKUŞAĞI":    "Güneş ışığının yağmur damlalarında kırılmasıyla oluşan renkli yay.",
        "GÖL":          "Her tarafı kara ile çevrilmiş büyük su birikintisi.",
        "HORTUM":       "Fırtına sırasında oluşan, her şeyi emen dönen hava sütunu.",
        "IRMAK":        "Geniş, derin, akıntılı büyük akarsu.",
        "KANYON":       "Derine kazılmış, dik yamaçlı dramatik nehir vadisi.",
        "KAR":          "Soğuk havada buharın kristalleşerek düşen beyaz yağış.",
        "KASIRGA":      "Çok güçlü, her şeyi yıkabilen tropik fırtına.",
        "KITA":         "Büyük karasal kütleler; Asya, Avrupa, Afrika gibi.",
        "KUMSAL":       "Deniz kenarında biriken ince kum tabakasından oluşan kıyı şeridi.",
        "LAGÜN":        "Denizden kumul ya da resifle ayrılan sığ tuzlu su birikintisi.",
        "MAĞARA":       "Dağ ya da yeraltındaki doğal yollar, oyuklar.",
        "MERCAN":       "Sığ sıcak sularda yaşayan, renkli iskelet oluşturan deniz canlısı.",
        "NEHİR":        "Kaynaktan okyanusa akan uzun ve geniş doğal su yolu.",
        "OKYANUS":      "Kıtaların arasında uzanan büyük tuzlu su kütlesi.",
        "ORMAN":        "Sık ağaçların örtüsü altında pek çok canlıya ev sahipliği yapan ekosistem.",
        "PLATO":        "Çevresine göre yüksek, geniş düzlük arazi.",
        "SİS":          "Küçük su damlacıklarının havada asılı kalmasıyla oluşan düşük görüşlülük.",
        "STEP":         "Ağaçsız, kuru ve düz olan geniş ot alanı.",
        "ŞELALE":       "Yüksekten aşağıya dökülen, çağıltılı su kütlesi.",
        "TUNDRA":       "Kutup bölgelerinde donmuş toprak ve kısa bitki örtüsüyle kaplı düzlük.",
        "UÇURUM":       "Dik ve yüksek taş veya toprak yamacı, vadiler kenarında sık görülür.",
        "VADİ":         "Dağlar arasında, genellikle nehir akan uzun çukur.",
        "VOLKAN":       "Yeraltındaki magmanın yeryüzüne çıktığı konili dağ.",
        "YANARDAĞ":     "Faaliyette olan, lav ve kül püskürten volkanik dağ.",
        "YARIMADA":     "Üç tarafı suyla çevrili, bir tarafı karaya bağlı toprak parçası.",
        "YAĞMUR":       "Bulutlardaki su damlacıklarının düşmesiyle oluşan yağış.",
        "ZİRVE":        "Dağın en yüksek noktası.",
        "AÇIK DENİZ":   "Kıyıdan uzak, derinliği fazla olan engin deniz bölgesi.",
        "BUHAR":        "Suyun ısınarak gaz hâline geçmesiyle oluşan görünmez su bulutu.",
        "ÇAYIR":        "Genellikle sulak alanlarda kendiliğinden yetişen, ot kaplı düzlük.",
        "DORUK":        "Bir dağ ya da tepenin en üst noktası.",
        "GÖK":          "Bulutların, yıldızların ve atmosferin göründüğü yüksek uzay.",
        "GÖLET":        "Doğal ya da yapay olarak oluşmuş küçük su birikintisi.",
        "KOY":          "Denizin karaya doğru girdiği, küçük çaplı sığınak gibi kıyı girintisi.",
        "KÖRFEZ":       "Karanın içine doğru büyükçe girinti yapan, üç yanı kıyıyla çevrili deniz bölümü.",
        "MERA":         "Hayvanların otlatıldığı, geniş ve düz otlak alan.",
        "TEPE":         "Çevresine göre yüksek, genellikle yuvarlak tepeli küçük yükselti.",
    ]
}
