import Foundation

extension WordList {

    // MARK: - Words

    static let yiyeceklerWords: [WordEntry] = [
        WordEntry(word: "ADANA KEBAP",   category: "Yiyecekler"),
        WordEntry(word: "AŞURE",         category: "Yiyecekler"),
        WordEntry(word: "AYRAN",         category: "Yiyecekler"),
        WordEntry(word: "BAL",           category: "Yiyecekler"),
        WordEntry(word: "BAKLAVA",       category: "Yiyecekler"),
        WordEntry(word: "BİSKÜVİ",       category: "Yiyecekler"),
        WordEntry(word: "BÖREK",         category: "Yiyecekler"),
        WordEntry(word: "BROKOLİ",       category: "Yiyecekler"),
        WordEntry(word: "BULGUR",        category: "Yiyecekler"),
        WordEntry(word: "CACIK",         category: "Yiyecekler"),
        WordEntry(word: "ÇAY",           category: "Yiyecekler"),
        WordEntry(word: "ÇİĞ KÖFTE",     category: "Yiyecekler"),
        WordEntry(word: "ÇORBA",         category: "Yiyecekler"),
        WordEntry(word: "DOLMA",         category: "Yiyecekler"),
        WordEntry(word: "DOMATES",       category: "Yiyecekler"),
        WordEntry(word: "DONDURMA",      category: "Yiyecekler"),
        WordEntry(word: "DÜRÜM",         category: "Yiyecekler"),
        WordEntry(word: "EKMEK",         category: "Yiyecekler"),
        WordEntry(word: "ET",            category: "Yiyecekler"),
        WordEntry(word: "FASULYE",       category: "Yiyecekler"),
        WordEntry(word: "GÜVEÇ",         category: "Yiyecekler"),
        WordEntry(word: "GÖZLEME",       category: "Yiyecekler"),
        WordEntry(word: "HAMBURGER",     category: "Yiyecekler"),
        WordEntry(word: "HAVUÇ",         category: "Yiyecekler"),
        WordEntry(word: "HELVA",         category: "Yiyecekler"),
        WordEntry(word: "HUMUS",         category: "Yiyecekler"),
        WordEntry(word: "ISPANAK",       category: "Yiyecekler"),
        WordEntry(word: "İSKENDER",      category: "Yiyecekler"),
        WordEntry(word: "KADAYIF",       category: "Yiyecekler"),
        WordEntry(word: "KAHVE",         category: "Yiyecekler"),
        WordEntry(word: "KAVURMA",       category: "Yiyecekler"),
        WordEntry(word: "KEBAP",         category: "Yiyecekler"),
        WordEntry(word: "KEK",           category: "Yiyecekler"),
        WordEntry(word: "KEREVİZ",       category: "Yiyecekler"),
        WordEntry(word: "KOMPOSTO",      category: "Yiyecekler"),
        WordEntry(word: "KREP",          category: "Yiyecekler"),
        WordEntry(word: "KÖFTE",         category: "Yiyecekler"),
        WordEntry(word: "KÜNEFE",        category: "Yiyecekler"),
        WordEntry(word: "LAHANA",        category: "Yiyecekler"),
        WordEntry(word: "LAHMACUN",      category: "Yiyecekler"),
        WordEntry(word: "LOKUM",         category: "Yiyecekler"),
        WordEntry(word: "MAKARNA",       category: "Yiyecekler"),
        WordEntry(word: "MANTI",         category: "Yiyecekler"),
        WordEntry(word: "MARMELAT",      category: "Yiyecekler"),
        WordEntry(word: "MENEMEN",       category: "Yiyecekler"),
        WordEntry(word: "MERCİMEK",      category: "Yiyecekler"),
        WordEntry(word: "MUHALLEBİ",     category: "Yiyecekler"),
        WordEntry(word: "NOHUT",         category: "Yiyecekler"),
        WordEntry(word: "OMLET",         category: "Yiyecekler"),
        WordEntry(word: "PİDE",          category: "Yiyecekler"),
        WordEntry(word: "PİLAV",         category: "Yiyecekler"),
        WordEntry(word: "PİZZA",         category: "Yiyecekler"),
        WordEntry(word: "REÇEL",         category: "Yiyecekler"),
        WordEntry(word: "REVANİ",        category: "Yiyecekler"),
        WordEntry(word: "SANDVİÇ",       category: "Yiyecekler"),
        WordEntry(word: "SİMİT",         category: "Yiyecekler"),
        WordEntry(word: "SUCUK",         category: "Yiyecekler"),
        WordEntry(word: "SÜT",           category: "Yiyecekler"),
        WordEntry(word: "SÜTLAÇ",        category: "Yiyecekler"),
        WordEntry(word: "ŞALGAM",        category: "Yiyecekler"),
        WordEntry(word: "TARHANA",       category: "Yiyecekler"),
        WordEntry(word: "TAVUK",         category: "Yiyecekler"),
        WordEntry(word: "TOST",          category: "Yiyecekler"),
        WordEntry(word: "TRİLEÇE",       category: "Yiyecekler"),
        WordEntry(word: "TURŞU",         category: "Yiyecekler"),
        WordEntry(word: "URFA KEBAP",    category: "Yiyecekler"),
        WordEntry(word: "YOĞURT",        category: "Yiyecekler"),
        WordEntry(word: "ZEYTİN",        category: "Yiyecekler"),
    ]

    // MARK: - Hints

    static let yiyeceklerHints: [String: String] = [
        "ADANA KEBAP":  "Kıymanın şişe geçirilerek közde pişirildiği Güney Türkiye spesyali.",
        "AŞURE":        "Tahıl, kuru meyve ve kurubaklagille yapılan geleneksel tatlı.",
        "AYRAN":        "Yoğurt, su ve tuzla yapılan geleneksel Türk içeceği.",
        "BAL":          "Arıların çiçek poleniyle ürettiği, tatlı, altın renkli doğal besin.",
        "BAKLAVA":      "İnce yufkalar, fıstık ve şerbetle yapılan Türk tatlısı.",
        "BİSKÜVİ":      "Undan yapılmış, fırında pişirilmiş, genellikle tatlı çıtır atıştırmalık.",
        "BÖREK":        "Hamur içine peynir, ıspanak veya kıyma konulan hamur işi.",
        "BROKOLİ":      "Yeşil ağaç görünümlü, C vitamini zengini lahana türü sebze.",
        "BULGUR":       "Buğdayın haşlanıp kurutulmasıyla elde edilen, pilav yapılan tahıl.",
        "CACIK":        "Yoğurt, salatalık ve sarımsak ile yapılan, soğuk Türk mezesi.",
        "ÇAY":          "Türklerin ulusal içeceği, ince belli bardakta demlenen sıcak içecek.",
        "ÇİĞ KÖFTE":    "Bulgur, baharatlar ve salça ile hazırlanan çiğ, vegan Türk yemeği.",
        "ÇORBA":        "Çeşitli malzemelerle yapılan, genellikle sıcak içilen sıvı yemek.",
        "DOLMA":        "Pirinç veya kıyma ile doldurulmuş yaprak veya sebze.",
        "DOMATES":      "Kırmızı, sulu, salatalarda ve sosislerde kullanılan sebze-meyve.",
        "DONDURMA":     "Süt, şeker ve tatlandırıcılarla yapılan, dondurulan tatlı.",
        "DÜRÜM":        "Kebap veya tavuk dolgusuyla sarılan ince yufka ekmeği.",
        "EKMEK":        "Undan yapılmış, fırında pişirilmiş temel gıda.",
        "FASULYE":      "Bakla ailesinden, taze veya kuru tüketilen besleyici besin.",
        "GÜVEÇ":        "Toprak kapta pişirilen et ve sebze yemeği.",
        "GÖZLEME":      "Yufkanın içine peynir, ıspanak ya da patates konularak sacda pişirilen yemek.",
        "HAMBURGER":    "İki ekmek arası köfte, marul, domates ile servis edilen fast food.",
        "HAVUÇ":        "Turuncu renkli, A vitamini zengini, çiğ veya pişmiş yenebilen sebze.",
        "HELVA":        "Tahini veya irmikten yapılan, tatlı ve doyurucu geleneksel Türk tatlısı.",
        "HUMUS":        "Haşlanmış nohutla yapılan, zeytinyağı ve tahin katkılı Orta Doğu mezesi.",
        "ISPANAK":      "Demir açısından zengin, koyu yeşil yapraklı sebze.",
        "İSKENDER":     "Döner üzerine yoğurt ve tereyağı dökülen Bursa'ya özgü kebap.",
        "KADAYIF":      "İnce tel kadayıf hamuruyla yapılan, şerbetli Türk tatlısı.",
        "KAHVE":        "Kahve çekirdeklerinin öğütülüp demlenmesiyle hazırlanan içecek.",
        "KAVURMA":      "Yağında kavrulan, kuzu veya sığır etinden yapılan geleneksel et yemeği.",
        "KEBAP":        "Ateşte veya ızgarada pişirilen et yemeği.",
        "KEK":          "Yumurta, un ve şekerle yapılıp fırında pişirilen tatlı.",
        "KEREVİZ":      "Uzun saplı, güçlü kokulu, hem sapı hem kökü yenilen sebze.",
        "KÖFTE":        "Kıyma, soğan ve baharatla hazırlanan, ızgara veya tavada pişirilen et yemeği.",
        "KÜNEFE":       "İplik kadayıf, peynir ve şerbetten yapılan sıcak tatlı.",
        "LAHANA":       "Büyük, yuvarlak yapraklı, turşu ve dolmada kullanılan sebze.",
        "LAHMACUN":     "İnce hamur üzerine kıyma karışımı sürülüp pişirilen Türk pizzası.",
        "LOKUM":        "Nişasta ve şekerle yapılan, pudra şekeriyle kaplanan Türk şekeri.",
        "MAKARNA":      "Buğday unuyla yapılan, çeşitli soslarla tüketilen İtalyan kökenli yemek.",
        "MANTI":        "İçine kıyma konulan küçük hamur, yoğurt ve sosla servis edilir.",
        "MENEMEN":      "Yumurta, domates ve biberle yapılan, sabah kahvaltısının vazgeçilmezi.",
        "MERCİMEK":     "Kırmızı veya yeşil türleriyle çorba ve yemek yapılan baklagil.",
        "MUHALLEBİ":    "Süt, pirinç unu ve şekerle yapılan beyaz renk tatlı.",
        "NOHUT":        "Protein zengini, sarı renkli baklagil; humusta ve güveçte kullanılır.",
        "OMLET":        "Yumurtanın çırpılıp tavada pişirildiği hızlı kahvaltılık.",
        "PİDE":         "Fırında pişen, üzeri çeşitli malzemelerle dolu Türk ekmeği.",
        "PİLAV":        "Pirinç ya da bulgurdan hazırlanan, Türk mutfağının temel yemeği.",
        "PİZZA":        "Fırında pişen hamur üzerine domates sosu, peynir ve malzeme dökülen İtalyan yemeği.",
        "REÇEL":        "Meyvelerin şekerle pişirilmesiyle yapılan, ekmeğe sürülen tatlı.",
        "REVANİ":       "İrmik ve şerbetle yapılan, üzeri hindistan cevizli Türk tatlısı.",
        "SANDVİÇ":      "Ekmek dilimleri arasına malzeme konulan pratik atıştırmalık.",
        "SİMİT":        "Susamlı, halka şeklinde, çıtır bir Türk sokak yiyeceği.",
        "SUCUK":        "Baharatlı kıyma doldurulmuş kurutulmuş sosis; kahvaltının vazgeçilmezi.",
        "SÜT":          "İnekten veya koyundan elde edilen, kalsiyum zengini beyaz içecek.",
        "SÜTLAÇ":       "Fırında pişirilmiş, üzeri kızarmış sütlü pirinç tatlısı.",
        "ŞALGAM":       "Adana'ya özgü, ekşi ve baharatlı şalgam suyundan yapılan içecek.",
        "TARHANA":      "Yoğurt, un ve sebze karışımından yapılan, kurutularak saklanan çorba malzemesi.",
        "TAVUK":        "Yumurta veren, çiftliklerde yaşayan, beyaz etli kümes hayvanı.",
        "TOST":         "Ekmek arasına peynir veya salam koyulup ısıtılan pratik yemek.",
        "TRİLEÇE":      "Üç farklı sütlü karışıma bandırılan, ıslak kek tatlısı.",
        "TURŞU":        "Tuz-sirke salamurasında bekletilmiş sebze veya meyveler.",
        "URFA KEBAP":   "Acısız, iri kıymalı, Şanlıurfa'ya özgü şişte pişirilmiş kebap.",
        "YOĞURT":       "Sütün bakteri kültürüyle mayalanmasıyla oluşan ekşimsi fermente ürün.",
        "ZEYTİN":       "Türkiye'nin sembollerinden, tuzlanmış veya sıkılmış yağı ile kullanılan meyve.",
    ]
}
