import Foundation

extension WordList {

    // MARK: - Words

    static let bitkilerWords: [WordEntry] = [
        WordEntry(word: "AKASYA",      category: "Bitkiler"),
        WordEntry(word: "ARDIÇ",       category: "Bitkiler"),
        WordEntry(word: "AYÇİÇEĞİ",    category: "Bitkiler"),
        WordEntry(word: "BAMBU",       category: "Bitkiler"),
        WordEntry(word: "BEGONYA",     category: "Bitkiler"),
        WordEntry(word: "ÇAM",         category: "Bitkiler"),
        WordEntry(word: "ÇAMLIK",      category: "Bitkiler"),
        WordEntry(word: "ÇINAR",       category: "Bitkiler"),
        WordEntry(word: "ÇİĞDEM",      category: "Bitkiler"),
        WordEntry(word: "DEFNE",       category: "Bitkiler"),
        WordEntry(word: "ELMA AĞACI",  category: "Bitkiler"),
        WordEntry(word: "FREZYA",      category: "Bitkiler"),
        WordEntry(word: "GÜL",         category: "Bitkiler"),
        WordEntry(word: "IHLAMUR",     category: "Bitkiler"),
        WordEntry(word: "KAKTÜS",      category: "Bitkiler"),
        WordEntry(word: "KARANFİL",    category: "Bitkiler"),
        WordEntry(word: "KAVAK",       category: "Bitkiler"),
        WordEntry(word: "KIZILÇAM",    category: "Bitkiler"),
        WordEntry(word: "KİRAZ AĞACI", category: "Bitkiler"),
        WordEntry(word: "KAYIN",       category: "Bitkiler"),
        WordEntry(word: "KEDİ OTU",    category: "Bitkiler"),
        WordEntry(word: "KAMELYA",     category: "Bitkiler"),
        WordEntry(word: "LAVANTA",     category: "Bitkiler"),
        WordEntry(word: "LALE",        category: "Bitkiler"),
        WordEntry(word: "LİMON AĞACI", category: "Bitkiler"),
        WordEntry(word: "MAGNOLYA",    category: "Bitkiler"),
        WordEntry(word: "MEŞE",        category: "Bitkiler"),
        WordEntry(word: "MENEKŞE",     category: "Bitkiler"),
        WordEntry(word: "MİMOZA",      category: "Bitkiler"),
        WordEntry(word: "NERGİS",      category: "Bitkiler"),
        WordEntry(word: "ORKİDE",      category: "Bitkiler"),
        WordEntry(word: "PALMİYE",     category: "Bitkiler"),
        WordEntry(word: "PAPATYA",     category: "Bitkiler"),
        WordEntry(word: "SARDUNYA",    category: "Bitkiler"),
        WordEntry(word: "SÖĞÜT",       category: "Bitkiler"),
        WordEntry(word: "SÜSEN",       category: "Bitkiler"),
        WordEntry(word: "SERVİ",       category: "Bitkiler"),
        WordEntry(word: "TARÇIN AĞACI",category: "Bitkiler"),
        WordEntry(word: "YASEMİN",     category: "Bitkiler"),
        WordEntry(word: "ZEYTİN AĞACI",category: "Bitkiler"),
    ]

    // MARK: - Hints

    static let bitkilerHints: [String: String] = [
        "AKASYA":        "Sarı küme çiçekli, hızlı büyüyen tropikal kökenli ağaç türü.",
        "ARDIÇ":         "Her dem yeşil kozalaklı çalı ya da ağaç; meyvesi baharat olarak kullanılır.",
        "AYÇİÇEĞİ":      "Güneşe dönen iri sarı çiçeği ve yağlı tohumu ile tanınan tarla bitkisi.",
        "BAMBU":         "Dünyanın en hızlı büyüyen bitkisi; panda'nın temel besini.",
        "BEGONYA":       "Parlak renkli çiçekleri olan, genellikle saksıda yetiştirilen süs bitkisi.",
        "ÇAM":           "İnce uzun iğne yaprakları ve kozalağıyla tanınan her dem yeşil ağaç.",
        "ÇAMLIK":        "Çam ağaçlarının yoğun olduğu ormanlık alan.",
        "ÇINAR":         "Geniş gölgesi ve dökülen kabuk dokusuyla tarihi meydanların vazgeçilmez ağacı.",
        "ÇİĞDEM":        "İlkbaharda karların arasından ilk çıkan küçük renkli çiçek.",
        "DEFNE":         "Yaprakları mutfakta baharat olarak kullanılan, köklü mitolojiye konu olan ağaç.",
        "ELMA AĞACI":    "Beyaz-pembe bahar çiçekleri açan, sonbahar da tatlı ya da ekşi meyve veren ağaç.",
        "FREZYA":        "İnce saplı, hoş kokulu ve trompet biçimli renkli çiçek.",
        "GÜL":           "Dikenleri ve güzel kokusuyla sevginin simgesi olan çiçek.",
        "IHLAMUR":       "Sarı çiçeklerinden demlenen çayıyla tanınan, gölgesi bol ağaç.",
        "KAKTÜS":        "Çöl koşullarına uyum sağlamış, dikenli etli su depolayan bitki.",
        "KARANFİL":      "Güçlü baharatlı kokusuyla bilinen, kırmızı ve beyaz çiçekli bitki.",
        "KAVAK":         "Hızlı büyüyen, ince uzun gövdesiyle yol kenarlarına sıra sıra dikilen ağaç.",
        "KAYIN":         "Düzgün gri kabuğu ve güz renkleriyle tanınan, sert odunlu orman ağacı.",
        "KAMELYA":       "Kışın açan, gül benzeri iri çiçekleri olan süs ağacı.",
        "KEDİ OTU":      "Kedilerin yoğun ilgi gösterdiği, sakinleştirici etkili kokulu bitki.",
        "KIZILÇAM":      "Akdeniz iklimine özgü, kırmızımsı kabuğuyla tanınan çam türü.",
        "KİRAZ AĞACI":   "İlkbaharda beyaz çiçekler açan, küçük kırmızı meyveli meyve ağacı.",
        "LAVANTA":       "Mor çiçekli, güçlü ve hoş kokusuyla arıların vazgeçmediği bitki.",
        "LALE":          "Türkiye ve Hollanda'nın sembolü, kadeh şeklinde renkli bahar çiçeği.",
        "LİMON AĞACI":   "Her dem yeşil yapraklı, sarı ekşi meyvesiyle tanınan Akdeniz meyve ağacı.",
        "MAGNOLYA":      "İri kadifemsi çiçekleriyle ilkbaharda dikkat çeken süs ağacı.",
        "MEŞE":          "Sert odunu ve palamutlarıyla tanınan, yüzyıllarca yaşayan orman ağacı.",
        "MENEKŞE":       "Mor tonlarındaki küçük, hoş kokulu erken bahar çiçeği.",
        "MİMOZA":        "Dokunulduğunda yaprakları kapanan, sarı top çiçekli duyarlı bitki.",
        "NERGİS":        "Sarı veya beyaz trompet biçimli çiçeğiyle ilkbaharı müjdeleyen soğanlı bitki.",
        "ORKİDE":        "Çok çeşitli türleriyle dünyanın en büyük çiçek ailelerinden biri.",
        "PALMİYE":       "Uzun gövdesi ve üstteki büyük yapraklarıyla tropik iklimin simgesi.",
        "PAPATYA":       "Beyaz yaprakları ve sarı göbeğiyle tanınan sevimli kır çiçeği.",
        "SARDUNYA":      "Balkonda sıklıkla yetişen, kırmızı ve pembe çiçekli çok yıllık süs bitkisi.",
        "SERVİ":         "Konik biçimi ve koyu yeşil rengiyle mezarlıklarda sık rastlanan ağaç.",
        "SÖĞÜT":         "Sarkık ince dallarıyla su kenarlarında yetişen, esnek dallı ağaç.",
        "SÜSEN":         "Mor, sarı ya da beyaz iris çiçekleriyle bilinen soğanlı bitki.",
        "TARÇIN AĞACI":  "Kabuğundan elde edilen kışlık baharatıyla mutfaklarda kullanılan tropikal ağaç.",
        "YASEMİN":       "Küçük beyaz çiçekleri ve yoğun hoş kokusuyla tanınan tırmanıcı bitki.",
        "ZEYTİN AĞACI":  "Akdeniz'in simgesi, asırlarca yaşayan, değerli yağlı meyvesiyle tanınan ağaç.",
    ]
}
