import Foundation

extension WordList {

    // MARK: - Words

    static let sporWords: [WordEntry] = [
        WordEntry(word: "AMERİKAN FUTBOLU", category: "Spor"),
        WordEntry(word: "ANTRENÖR",     category: "Spor"),
        WordEntry(word: "ATLETİZM",     category: "Spor"),
        WordEntry(word: "BADMINTON",    category: "Spor"),
        WordEntry(word: "BASKETBOL",    category: "Spor"),
        WordEntry(word: "BEYZBOL",      category: "Spor"),
        WordEntry(word: "BİATLON",      category: "Spor"),
        WordEntry(word: "BİLARDO",      category: "Spor"),
        WordEntry(word: "BİNİCİLİK",    category: "Spor"),
        WordEntry(word: "BİSİKLET",     category: "Spor"),
        WordEntry(word: "BOKS",         category: "Spor"),
        WordEntry(word: "DART",         category: "Spor"),
        WordEntry(word: "DAĞCILIK",     category: "Spor"),
        WordEntry(word: "ESKRİM",       category: "Spor"),
        WordEntry(word: "FORMA",        category: "Spor"),
        WordEntry(word: "FORMULA",    category: "Spor"),
        WordEntry(word: "FUTBOL",       category: "Spor"),
        WordEntry(word: "GOLF",         category: "Spor"),
        WordEntry(word: "GÜREŞ",        category: "Spor"),
        WordEntry(word: "HAKEM",        category: "Spor"),
        WordEntry(word: "HALTER",       category: "Spor"),
        WordEntry(word: "HENTBOL",      category: "Spor"),
        WordEntry(word: "HOKEY",        category: "Spor"),
        WordEntry(word: "JİMNASTİK",    category: "Spor"),
        WordEntry(word: "JUDO",         category: "Spor"),
        WordEntry(word: "KARATE",       category: "Spor"),
        WordEntry(word: "KALECİ",       category: "Spor"),
        WordEntry(word: "KAYAK",        category: "Spor"),
        WordEntry(word: "KOŞU",         category: "Spor"),
        WordEntry(word: "KRAMPON",      category: "Spor"),
        WordEntry(word: "KRİKET",       category: "Spor"),
        WordEntry(word: "KÜREK",        category: "Spor"),
        WordEntry(word: "MADALYA",      category: "Spor"),
        WordEntry(word: "MARATON",      category: "Spor"),
        WordEntry(word: "MASA TENİSİ",  category: "Spor"),
        WordEntry(word: "OKÇULUK",      category: "Spor"),
        WordEntry(word: "PATEN",        category: "Spor"),
        WordEntry(word: "PENTATLON",    category: "Spor"),
        WordEntry(word: "RAKET",        category: "Spor"),
        WordEntry(word: "RAGBİ",        category: "Spor"),
        WordEntry(word: "SATRANÇ",      category: "Spor"),
        WordEntry(word: "SKİ",          category: "Spor"),
        WordEntry(word: "SNOWBOARD",    category: "Spor"),
        WordEntry(word: "SPORCU",       category: "Spor"),
        WordEntry(word: "STADYUM",      category: "Spor"),
        WordEntry(word: "SUMO",         category: "Spor"),
        WordEntry(word: "SÖRF",         category: "Spor"),
        WordEntry(word: "ŞAMPİYON",     category: "Spor"),
        WordEntry(word: "TAEKWONDO",    category: "Spor"),
        WordEntry(word: "TENİS",        category: "Spor"),
        WordEntry(word: "TRAMPLEN",     category: "Spor"),
        WordEntry(word: "TRİATLON",     category: "Spor"),
        WordEntry(word: "TURNUVA",      category: "Spor"),
        WordEntry(word: "VOLEYBOL",     category: "Spor"),
        WordEntry(word: "WUSHU",        category: "Spor"),
        WordEntry(word: "YELKEN",       category: "Spor"),
        WordEntry(word: "YÜZME",        category: "Spor"),
    ]

    // MARK: - Hints

    static let sporHints: [String: String] = [
        "ATLETİZM":     "Koşu, atlama ve atma branşlarından oluşan temel olimpik spor.",
        "BADMINTON":    "Raket ve tüylü topla file üzerinden oynanan hızlı salon oyunu.",
        "BASKETBOL":    "Beşer kişilik iki takımın potaya top atmaya çalıştığı popüler spor.",
        "BEYZBOL":      "Topun sopayla vurulup tarlada koşulan, Amerikalı popüler spor.",
        "BİATLON":      "Kros kayak ve atışın birleşimi olan kış olimpik sporu.",
        "BİLARDO":      "Kü ile renkli toplara vurulan, kapalı masada oynanan salon oyunu.",
        "BİNİCİLİK":    "Atın üzerinde çeşitli egzersiz ve yarışları içeren olimpik spor.",
        "BİSİKLET":     "Pedal çevirerek ilerlenen, iki tekerlekli taşıt ve spor dalı.",
        "BOKS":         "İki rakibin eldivenlerle yumruk attığı dövüş sporu.",
        "DART":         "Hedef tahtasına sivri uçlu ok fırlatılan eğlence ve spor oyunu.",
        "DAĞCILIK":     "Dağlara tırmanmayı, özel ekipman ve teknikle gerçekleştiren spor.",
        "ESKRİM":       "Kılıç, floret veya meç ile rakibe puan kazanmaya çalışılan olimpik spor.",
        "FUTBOL":       "11'er kişilik iki takımın topla kaleye gol atmaya çalıştığı en popüler spor.",
        "GOLF":         "Sopa ile topu az vuruşta deliğe sokmaya çalışılan, geniş sahada oynanan spor.",
        "GÜREŞ":        "İki rakibin birbirini yere getirmeye çalıştığı en eski olimpik spor.",
        "HALTER":       "Ağır metal levhaları kaldırarak güç gösterisinin yapıldığı olimpik spor.",
        "HENTBOL":      "Yedi kişilik takımların el ile topla file içine gol atmaya çalıştığı spor.",
        "HOKEY":        "Sopa ile puku veya topla rakip kaleye atış yapılan takım sporu.",
        "JİMNASTİK":    "Esneklik, güç ve koordinasyon gerektiren olimpik spor dalı.",
        "JUDO":         "Japon kökenli, rakibi atma ve kilitleyerek üstünlük kurulan dövüş sanatı.",
        "KARATE":       "Yumruk ve tekmelerin disiplin içinde kullanıldığı Japon dövüş sanatı.",
        "KALECİ":       "Takımın ağını koruyan, topun içeri girmesini önleyen oyuncu.",
        "KAYAK":        "Kar üzerinde uzun tahtalar ile hız veya sörf yapılan kış sporu.",
        "KOŞU":         "İki ayakla hızla ilerleyen temel atletizm disiplini.",
        "KRİKET":       "Sopa ile topun vurulduğu, İngiliz kökenli sahalı takım sporu.",
        "KÜREK":        "Tekne üzerinde kürekle güçlü çekişlerle ilerlenen olimpik su sporu.",
        "MADALYA":      "Olimpik veya şampiyona yarışmalarında dereceye girenin aldığı ödül simgesi.",
        "MARATON":      "42,195 km'lik uzun mesafe koşusu; dayanıklılık sporlarının zirvesi.",
        "MASA TENİSİ":  "İki ya da dört kişinin küçük raketlerle masa üzerinde top oynattığı spor.",
        "OKÇULUK":      "Yay ile hedefe ok fırlatılan eski ve olimpik spor dalı.",
        "PATEN":        "Ayağa takılan tekerlekli veya buz bıçaklı araçlarla yapılan spor.",
        "RAGBİ":        "Oval topun elle veya ayakla taşındığı, İngiliz kökenli sert takım sporu.",
        "SATRANÇ":      "64 kareli tahta üzerinde stratejik figürlerle oynanan zihin sporu.",
        "SNOWBOARD":    "Tek bir tahta üzerinde karda kayarak hız ve figür yapılan kış sporu.",
        "STADYUM":      "Seyircilerin tribünlerden maç veya atletizm izlediği büyük spor yapısı.",
        "SUMO":         "Dev yapılı Japon güreşçilerin daireden çıkarmaya çalıştığı geleneksel spor.",
        "SÖRF":         "Deniz dalgalarını sörf tahtasıyla süzme sanatı ve sporu.",
        "ŞAMPİYON":     "Turnuva veya lig sonunda birinci olan takım ya da sporcu.",
        "TAEKWONDO":    "Kore kökenli, yüksek tekme vuruşlarının öne çıktığı olimpik dövüş sanatı.",
        "TENİS":        "Raket ile topun ağ üzerinden karşılıklı vurulduğu olimpik spor.",
        "TRİATLON":     "Yüzme, bisiklet ve koşunun arka arkaya yapıldığı dayanıklılık sporu.",
        "TURNUVA":      "Birden fazla takım ya da oyuncunun rekabet ettiği organize müsabaka dizisi.",
        "VOLEYBOL":     "Altışar kişilik iki takımın file üzerinden topla oynattığı olimpik spor.",
        "YELKEN":       "Rüzgar gücüyle yelkenli tekneyi yönlendirerek yarışılan su sporu.",
        "YÜZME":        "Suda çeşitli stillerle ilerlenen temel olimpik su sporu.",
        "FORMULA":      "Açık kokpitli yarış araçlarının pistte yarıştığı motor sporu.",
        "SKİ":          "Karda hızlı iniş veya slalom yapılan kış sporu dalı.",
        "ANTRENÖR":     "Sporculara teknik ve fiziksel anlamda rehberlik eden eğitmen.",
        "HAKEM":        "Müsabakayı yöneten, kurallara uyumu denetleyen yetkili kişi.",
        "RAKET":        "Tenis, badminton gibi sporlarda topu vurmak için kullanılan araç.",
        "KRAMPON":      "Futbol ve rugby oyuncularının kaymaması için giydiği özel çivili bot.",
        "FORMA":        "Sporcuların giydikleri takım rengini ve numarasını gösteren özel kıyafet.",
    ]
}
