import Foundation

extension WordList {

    // MARK: - Words

    static let cografyaWords: [WordEntry] = [
        WordEntry(word: "AMAZON",      category: "Coğrafya"),
        WordEntry(word: "AMERİKA",     category: "Coğrafya"),
        WordEntry(word: "ANTARKTİKA",  category: "Coğrafya"),
        WordEntry(word: "ASYA",        category: "Coğrafya"),
        WordEntry(word: "AVRUPA",      category: "Coğrafya"),
        WordEntry(word: "BOĞAZ",       category: "Coğrafya"),
        WordEntry(word: "BUZUL",       category: "Coğrafya"),
        WordEntry(word: "ÇÖL",         category: "Coğrafya"),
        WordEntry(word: "DELTA",       category: "Coğrafya"),
        WordEntry(word: "EKVATOR",     category: "Coğrafya"),
        WordEntry(word: "EROZYON",     category: "Coğrafya"),
        WordEntry(word: "EVEREST",     category: "Coğrafya"),
        WordEntry(word: "FAY HATTI",   category: "Coğrafya"),
        WordEntry(word: "HİMALAYA",    category: "Coğrafya"),
        WordEntry(word: "HARİTA",      category: "Coğrafya"),
        WordEntry(word: "İKLİM",       category: "Coğrafya"),
        WordEntry(word: "KANAL",       category: "Coğrafya"),
        WordEntry(word: "KÖRFEZ",      category: "Coğrafya"),
        WordEntry(word: "KUTUP",       category: "Coğrafya"),
        WordEntry(word: "MERİDYEN",    category: "Coğrafya"),
        WordEntry(word: "MUSON",       category: "Coğrafya"),
        WordEntry(word: "NİL",         category: "Coğrafya"),
        WordEntry(word: "OKYANUS",     category: "Coğrafya"),
        WordEntry(word: "OKYANUSYA",   category: "Coğrafya"),
        WordEntry(word: "PARALEL",     category: "Coğrafya"),
        WordEntry(word: "PLATO",       category: "Coğrafya"),
        WordEntry(word: "SAHARA",      category: "Coğrafya"),
        WordEntry(word: "SAVANA",      category: "Coğrafya"),
        WordEntry(word: "STEP",        category: "Coğrafya"),
        WordEntry(word: "TEKTONİK",    category: "Coğrafya"),
        WordEntry(word: "TROPİK",      category: "Coğrafya"),
        WordEntry(word: "TUNDRA",      category: "Coğrafya"),
        WordEntry(word: "TSUNAMİ",     category: "Coğrafya"),
        WordEntry(word: "VADİ",        category: "Coğrafya"),
        WordEntry(word: "VOLKAN",      category: "Coğrafya"),
        WordEntry(word: "YARIMADA",    category: "Coğrafya"),
        WordEntry(word: "ZİRVE",       category: "Coğrafya"),
    ]

    // MARK: - Hints

    static let cografyaHints: [String: String] = [
        "AMAZON":       "Dünyanın en geniş yağmur ormanı ve en bol sulu nehri; Güney Amerika'da.",
        "AMERİKA":      "Kuzey ve Güney olmak üzere iki kıtadan oluşan dev kara kütlesi.",
        "ANTARKTİKA":   "Güney Kutbu'nu kaplayan, dünyanın en soğuk ve ıssız kıtası.",
        "ASYA":         "Dünyanın en büyük ve en kalabalık kıtası.",
        "AVRUPA":       "Batıda Atlantik, doğuda Ural Dağları ile sınırlanan küçük ama etkili kıta.",
        "BOĞAZ":        "İki denizi ya da denizle gölü birbirine bağlayan dar su geçidi.",
        "BUZUL":        "Yüzyıllarca biriken kar ve buzun sıkışmasıyla oluşan devasa buz kitlesi.",
        "ÇÖL":          "Yıllık yağışın çok az olduğu, bitki örtüsünden yoksun geniş kuru alan.",
        "DELTA":        "Nehrin denize ya da göle döküldüğü yerde alüvyon birikmesiyle oluşan üçgen kara.",
        "EKVATOR":      "Dünya'yı kuzey ve güney yarıküreye bölen, sıfır derece enlemi.",
        "EROZYON":      "Rüzgar ve su gibi doğal güçlerin toprağı ya da kayayı aşındırması süreci.",
        "EVEREST":      "Dünyanın en yüksek dağı; Himalayalar'da, Nepal-Çin sınırında.",
        "FAY HATTI":    "Yer kabuğundaki iki levhanın birbirine sürtündüğü kırık çizgisi; deprem kaynağı.",
        "HİMALAYA":     "Hindistan ile Tibet arasında uzanan, dünyanın en yüksek dağ sırası.",
        "HARİTA":       "Yeryüzünün belirli bir ölçekle düzleme aktarılmış temsili çizimi.",
        "İKLİM":        "Bir bölgedeki uzun süreli hava koşullarının genel örüntüsü.",
        "KANAL":        "İki su kütlesini birbirine bağlamak veya sulama için kazılan yapay su yolu.",
        "KÖRFEZ":       "Karanın içine doğru girintili, üç yanı kara ile çevrili geniş deniz kıyısı.",
        "KUTUP":        "Dünya'nın dönme ekseninin yüzeyle kesiştiği en kuzey ya da en güney noktası.",
        "MERİDYEN":     "Kuzey ve Güney Kutuplarını birleştiren, boylamı gösteren hayali dikey çizgi.",
        "MUSON":        "Yaz ve kış mevsimlerinde yön değiştiren mevsimlik rüzgar.",
        "NİL":          "Afrika'nın en uzun nehri; Mısır medeniyetinin temel yaşam kaynağı.",
        "OKYANUS":      "Kıtalar arasındaki tuzlu su kütlesi; yeryüzünün yaklaşık yüzde yetmişini kaplar.",
        "OKYANUSYA":    "Avustralya ve Pasifik'teki çevre adaları kapsayan coğrafi bölge.",
        "PARALEL":      "Ekvator'a paralel olarak çizilen, enlemi gösteren hayali yatay çizgiler.",
        "PLATO":        "Çevresine göre yüksek, üstü geniş ve düz arazi şekli.",
        "SAHARA":       "Afrika'da yer alan dünyanın en büyük sıcak çölü.",
        "SAVANA":       "Tropikal bölgelerdeki, ağaçların seyrek ve otların bol olduğu geniş düzlükler.",
        "STEP":         "Yarı kurak bölgelerde görülen, kısa çayırlı geniş ve düz alanlar.",
        "TEKTONİK":     "Yer kabuğundaki levhaların hareketi ve buna bağlı jeolojik olaylar.",
        "TROPİK":       "Ekvator'un her iki yanında yer alan sıcak ve nemli iklim kuşağı.",
        "TUNDRA":       "Kutup bölgelerine özgü, ağaç yetişmeyen soğuk ve düz alanlar.",
        "TSUNAMİ":      "Deniz altı deprem veya volkanın tetiklediği büyük ve yıkıcı su dalgası.",
        "VADİ":         "İki dağ ya da tepe arasında uzanan çukur arazi şekli.",
        "VOLKAN":       "Magmanın yeryüzüne çıktığı, püskürme ile şekillenen dağ.",
        "YARIMADA":     "Üç yanı suyla çevrili, bir yanı karaya bağlı çıkıntılı kara parçası.",
        "ZİRVE":        "Dağın en yüksek, tepe noktası.",
    ]
}
