import Foundation

extension WordList {

    // MARK: - Words

    static let sporPlusWords: [WordEntry] = [
        WordEntry(word: "FENERBAHÇE",      category: "Spor+"),
        WordEntry(word: "GALATASARAY",     category: "Spor+"),
        WordEntry(word: "BEŞİKTAŞ",        category: "Spor+"),
        WordEntry(word: "TRABZONSPOR",     category: "Spor+"),
        WordEntry(word: "BURSASPOR",       category: "Spor+"),
        WordEntry(word: "BAŞAKŞEHİR",      category: "Spor+"),
        WordEntry(word: "ŞAMPİYONLAR",     category: "Spor+"),
        WordEntry(word: "AVRUPA",          category: "Spor+"),
        WordEntry(word: "DÜNYAKUPASI",     category: "Spor+"),
        WordEntry(word: "OLİMPİYAT",       category: "Spor+"),
        WordEntry(word: "FORMULA",         category: "Spor+"),
        WordEntry(word: "WIMBLEDON",       category: "Spor+"),
        WordEntry(word: "MARATON",         category: "Spor+"),
        WordEntry(word: "PENALTİ",         category: "Spor+"),
        WordEntry(word: "FAVORİ",          category: "Spor+"),
        WordEntry(word: "VAR",             category: "Spor+"),
        WordEntry(word: "OFFSAYT",         category: "Spor+"),
        WordEntry(word: "FORVET",          category: "Spor+"),
        WordEntry(word: "STOPER",          category: "Spor+"),
        WordEntry(word: "KALECİ",          category: "Spor+"),
        WordEntry(word: "TEKNİKDİREKTÖR",  category: "Spor+"),
        WordEntry(word: "TRANSFER",        category: "Spor+"),
        WordEntry(word: "TURNUVA",         category: "Spor+"),
        WordEntry(word: "STADYUM",         category: "Spor+"),
        WordEntry(word: "TARAFTAR",        category: "Spor+"),
        WordEntry(word: "DERBİ",           category: "Spor+"),
        WordEntry(word: "ASİST",           category: "Spor+"),
        WordEntry(word: "HATTRİCK",        category: "Spor+"),
        WordEntry(word: "KORNER",          category: "Spor+"),
        WordEntry(word: "FRİKİK",          category: "Spor+"),
        WordEntry(word: "OFANSİF",         category: "Spor+"),
        WordEntry(word: "DEFANSİF",        category: "Spor+"),
        WordEntry(word: "KRAMP",           category: "Spor+"),
        WordEntry(word: "ANTRENMAN",       category: "Spor+"),
        WordEntry(word: "KONDİSYON",       category: "Spor+"),
        WordEntry(word: "REFERANS",        category: "Spor+"),
        WordEntry(word: "VOLEYBOL",        category: "Spor+"),
        WordEntry(word: "BASKETBOL",       category: "Spor+"),
        WordEntry(word: "HENTBOL",         category: "Spor+"),
        WordEntry(word: "GÜREŞ",           category: "Spor+"),
        WordEntry(word: "BOKS",            category: "Spor+"),
        WordEntry(word: "JUDO",            category: "Spor+"),
        WordEntry(word: "TEKVANDO",        category: "Spor+"),
        WordEntry(word: "EFES",            category: "Spor+"),
        WordEntry(word: "ANADOLU",         category: "Spor+"),
        WordEntry(word: "PİVOT",           category: "Spor+"),
        WordEntry(word: "PASLAŞMA",        category: "Spor+"),
        WordEntry(word: "RAKET",           category: "Spor+"),
        WordEntry(word: "FİLE",            category: "Spor+"),
        WordEntry(word: "JOKEY",           category: "Spor+"),
        WordEntry(word: "ATLET",           category: "Spor+"),
        WordEntry(word: "MEDALYA",         category: "Spor+"),
        WordEntry(word: "REKOR",           category: "Spor+"),
        WordEntry(word: "ZAFER",           category: "Spor+"),
        WordEntry(word: "TURBO",           category: "Spor+"),
        WordEntry(word: "PİT",             category: "Spor+"),
        WordEntry(word: "PODYUM",          category: "Spor+"),
        WordEntry(word: "SAMPDORIA",       category: "Spor+"),
        WordEntry(word: "BARÇA",           category: "Spor+"),
        WordEntry(word: "MADRİD",          category: "Spor+"),
    ]

    // MARK: - Hints

    static let sporPlusHints: [String: String] = [
        "FENERBAHÇE":      "Sarı-lacivert renkleriyle İstanbul'un Anadolu yakasını temsil eden futbol kulübü.",
        "GALATASARAY":     "Sarı-kırmızı formalarıyla Avrupa'da kupa kazanan İstanbul kökenli köklü kulüp.",
        "BEŞİKTAŞ":        "Siyah-beyaz renkleriyle Boğazın kıyısındaki tarihi İstanbul kulübü.",
        "TRABZONSPOR":     "Karadeniz'in gururunu ve bordo-maviyi temsil eden köklü Anadolu kulübü.",
        "BURSASPOR":       "Yeşil-beyaz formasıyla tanınan, Bursa'nın şampiyonluk deneyimli kulübü.",
        "BAŞAKŞEHİR":      "İstanbul'un en genç kulübü olup son yıllarda şampiyonluğa ulaşan takım.",
        "ŞAMPİYONLAR":     "Avrupa'nın en prestijli kulüpler arası futbol turnuvasının ana teması.",
        "AVRUPA":          "Kıta genelinde futbol kulüplerinin katıldığı uluslararası müsabaka ortamı.",
        "DÜNYAKUPASI":     "Her dört yılda bir oynanan ve milyarlarca izleyicinin takip ettiği futbol şöleni.",
        "OLİMPİYAT":       "Dört yılda bir farklı şehirlerde düzenlenen çok branşlı uluslararası spor oyunları.",
        "FORMULA":         "En hızlı yarış araçlarının pistlerde mücadele ettiği motorsporun en üst sınıfı.",
        "WIMBLEDON":       "İngiltere'de çim kortta oynanan en prestijli tenis grand slam turnuvası.",
        "MARATON":         "42 kilometre 195 metrelik mesafede koşulan dayanıklılık atletizm yarışması.",
        "PENALTİ":         "Ceza sahası içinde yapılan ihlal sonucu atılan, kaleciye karşı tek vuruş.",
        "FAVORİ":          "Kazanmaya en yakın görülen ve üzerine en çok bahis oynanan rakip.",
        "VAR":             "Futbolda tartışmalı pozisyonları incelemek için kullanılan video hakemlik sistemi.",
        "OFFSAYT":         "Bir oyuncunun topu aldığı anda rakip kaleye yeterince yakın olma ihlali.",
        "FORVET":          "Takımın en önünde hücum ederek gol atmayı birincil görev edinen oyuncu.",
        "STOPER":          "Savunmanın merkezinde rakip forvetleri durdurmakla görevli defans oyuncusu.",
        "KALECİ":          "Kalesi önünde ellerini de kullanarak golü engellemeye çalışan oyuncu.",
        "TEKNİKDİREKTÖR":  "Takımın taktik ve antrenman sürecini yönetip sahaya oluşumu belirleyen sorumlu.",
        "TRANSFER":        "Bir futbolcunun bir kulüpten başka bir kulübe geçiş sürecinin adı.",
        "TURNUVA":         "Birden fazla takımın şampiyonluk için mücadele ettiği organize müsabaka dizisi.",
        "STADYUM":         "On binlerce seyircinin maçları izlediği büyük kapalı ya da açık spor tesisi.",
        "TARAFTAR":        "Takımına coşkuyla bağlı, tribünlerde destek veren sadık spor tutkunu.",
        "DERBİ":           "Aynı şehrin ya da bölgenin büyük rakiplerinin yüksek gerilimle karşılaştığı maç.",
        "ASİST":           "Takım arkadaşının gol atmasını sağlayan son pasoyu veren oyuncunun katkısı.",
        "HATTRİCK":        "Bir oyuncunun aynı maçta üst üste ya da ard arda üç gol atması.",
        "KORNER":          "Topun defans oyuncusundan çizgi dışına çıkması sonrası köşeden atılan vuruş.",
        "FRİKİK":          "Rakibin ihlali sonucu verilen ve topu durma noktasından atma hakkı.",
        "OFANSİF":         "Saldırı odaklı, gol atmayı ön planda tutan oyun stili veya oyuncu tipi.",
        "DEFANSİF":        "Rakibin gol atmasını önlemeye yönelik savunmacı oyun anlayışı.",
        "KRAMP":           "Kasların ani kasılmasıyla oluşan ve oyuncuyu durduran ağrılı durum.",
        "ANTRENMAN":       "Sporcuların performansını geliştirmek için yapılan düzenli egzersiz çalışması.",
        "KONDİSYON":       "Sporcunun fiziksel dayanıklılık ve hazırlık düzeyini ifade eden kavram.",
        "REFERANS":        "Bir sporcunun ya da teknik adamın geçmiş performansına dair öneride bulunma.",
        "VOLEYBOL":        "Ağ üzerinden top gönderilen, altı oyunculu takımların oynadığı top oyunu.",
        "BASKETBOL":       "Potaya topu atarak sayı kazanmaya dayanan beş oyunculu parke sporu.",
        "HENTBOL":         "Elde tutulan topun kaleye atıldığı yedi oyunculu kapalı alan sporu.",
        "GÜREŞ":           "İki rakibin birbirini yere düşürmeye çalıştığı köklü dövüş sporu.",
        "BOKS":            "Eldivenli yumruklarla rakibi nakavt etmeye ya da puan toplamaya dayanan dövüş sporu.",
        "JUDO":            "Rakibi yere devirerek puan kazanmaya dayanan Japon kökenli dövüş sanatı.",
        "TEKVANDO":        "Yüksek ve hızlı tekme hareketleriyle öne çıkan Kore kökenli dövüş sporu.",
        "EFES":            "Anadolu kulübünün basketbol bölümü; Avrupa şampiyonluğunu kazanan İstanbul takımı.",
        "ANADOLU":         "Türkiye'nin Asya yakasını simgeleyen coğrafi bölge adını taşıyan spor kulübü.",
        "PİVOT":           "Basketbolda potaya yakın oynayan ve fiziksel gücünü kullanan iç saha oyuncusu.",
        "PASLAŞMA":        "İki ya da daha fazla oyuncunun topu birbirine hızlıca aktardığı ofansif hareket.",
        "RAKET":           "Tenis, badminton ya da masa tenisinde topu vurmak için kullanılan çerçeveli alet.",
        "FİLE":            "Tenis, voleybol ya da futbolda sahayı ikiye ayıran ya da golü sağlayan ağ.",
        "JOKEY":           "At yarışlarında hayvanın sırtına binerek koşuyu yöneten profesyonel sporcu.",
        "ATLET":           "Koşu, atlama ya da fırlatma gibi branşlarda yarışan atletizm sporcusu.",
        "MEDALYA":         "Olimpiyat ya da büyük yarışmalarda dereceye giren sporcuya verilen madalya.",
        "REKOR":           "Bir branşta daha önce kimsenin ulaşamadığı en iyi performans değeri.",
        "ZAFER":           "Rakibe üstünlük sağlayarak elde edilen spor ya da savaş başarısı.",
        "TURBO":           "Motor gücünü artırmak için egzoz gazından yararlanan zorlamalı hava sistemi.",
        "PİT":             "Formula yarışlarında aracın bakım, yakıt ve lastik değişimi için girdiği bölge.",
        "PODYUM":          "Yarışmada ilk üç dereceye giren sporcuların ödüllerini aldığı yükseltilmiş platform.",
        "SAMPDORIA":       "Cenova şehrinin denizcilik geleneğini taşıyan İtalyan futbol kulübü.",
        "BARÇA":           "İspanya'nın en büyük Katalonya kulübünün kısa ve yaygın lakabı.",
        "MADRİD":          "Dünyanın en çok kupa kazanan futbol kulübünün Avrupa başkentindeki yurdu.",
    ]
}
