import Foundation

extension WordList {

    // MARK: - Words

    static let mesleklerWords: [WordEntry] = [
        WordEntry(word: "AŞÇI", category: "Meslekler"),
        WordEntry(word: "ASTRONOM", category: "Meslekler"),
        WordEntry(word: "ANTROPOLOG", category: "Meslekler"),
        WordEntry(word: "ASKER", category: "Meslekler"),
        WordEntry(word: "AVUKAT", category: "Meslekler"),
        WordEntry(word: "BANKACI", category: "Meslekler"),
        WordEntry(word: "BERBER", category: "Meslekler"),
        WordEntry(word: "BİYOLOG", category: "Meslekler"),
        WordEntry(word: "BOTANİKÇİ", category: "Meslekler"),
        WordEntry(word: "CERRAH", category: "Meslekler"),
        WordEntry(word: "DENİZCİ", category: "Meslekler"),
        WordEntry(word: "DİŞÇİ", category: "Meslekler"),
        WordEntry(word: "DİYETİSYEN", category: "Meslekler"),
        WordEntry(word: "DOKTOR", category: "Meslekler"),
        WordEntry(word: "DUBLÖR", category: "Meslekler"),
        WordEntry(word: "ECZACI", category: "Meslekler"),
        WordEntry(word: "ELEKTRİKÇİ", category: "Meslekler"),
        WordEntry(word: "FİZİKÇİ", category: "Meslekler"),
        WordEntry(word: "FOTOĞRAFÇI", category: "Meslekler"),
        WordEntry(word: "GARSON", category: "Meslekler"),
        WordEntry(word: "GAZETECİ", category: "Meslekler"),
        WordEntry(word: "GRAFİKER", category: "Meslekler"),
        WordEntry(word: "HAKİM", category: "Meslekler"),
        WordEntry(word: "HEMŞİRE", category: "Meslekler"),
        WordEntry(word: "HEYKELTRAŞ", category: "Meslekler"),
        WordEntry(word: "HOSTES", category: "Meslekler"),
        WordEntry(word: "İKTİSATÇI", category: "Meslekler"),
        WordEntry(word: "İNŞAATÇI", category: "Meslekler"),
        WordEntry(word: "İNTERNET YAYINCISI", category: "Meslekler"),
        WordEntry(word: "İTFAİYECİ", category: "Meslekler"),
        WordEntry(word: "KAPTAN", category: "Meslekler"),
        WordEntry(word: "KARDİYOLOG", category: "Meslekler"),
        WordEntry(word: "KASAP", category: "Meslekler"),
        WordEntry(word: "KOMEDYEN", category: "Meslekler"),
        WordEntry(word: "KUAFÖR", category: "Meslekler"),
        WordEntry(word: "KURYE", category: "Meslekler"),
        WordEntry(word: "MANAV", category: "Meslekler"),
        WordEntry(word: "MİMAR", category: "Meslekler"),
        WordEntry(word: "MUHASEBECİ", category: "Meslekler"),
        WordEntry(word: "MÜHENDİS", category: "Meslekler"),
        WordEntry(word: "MÜZİSYEN", category: "Meslekler"),
        WordEntry(word: "NÖROLOG", category: "Meslekler"),
        WordEntry(word: "ORNİTOLOG", category: "Meslekler"),
        WordEntry(word: "PALEONTOLOG", category: "Meslekler"),
        WordEntry(word: "PİLOT", category: "Meslekler"),
        WordEntry(word: "POLİS", category: "Meslekler"),
        WordEntry(word: "PSİKOLOG", category: "Meslekler"),
        WordEntry(word: "REKLAMCI", category: "Meslekler"),
        WordEntry(word: "RESSAM", category: "Meslekler"),
        WordEntry(word: "SENARİST", category: "Meslekler"),
        WordEntry(word: "SOSYOLOG", category: "Meslekler"),
        WordEntry(word: "SUBAY", category: "Meslekler"),
        WordEntry(word: "ŞOFÖR", category: "Meslekler"),
        WordEntry(word: "TERZİ", category: "Meslekler"),
        WordEntry(word: "TEKNİSYEN", category: "Meslekler"),
        WordEntry(word: "TAMİRCİ", category: "Meslekler"),
        WordEntry(word: "VETERİNER", category: "Meslekler"),
        WordEntry(word: "YAZILIMCI", category: "Meslekler"),
        WordEntry(word: "YÖNETMEN", category: "Meslekler"),
    ]

    // MARK: - Hints

    static let mesleklerHints: [String: String] = [
        "AŞÇI":         "Yemek hazırlayan, mutfakta çalışan, lezzet yaratan kişi.",
        "ASTRONOM":     "Yıldızları, gezegenleri ve gökcisimlerini inceleyen bilim insanı.",
        "ANTROPOLOG":   "İnsan kültürlerini, tarihini ve evrimini araştıran bilim insanı.",
        "ASKER":        "Ülkeyi korumak için silahlı kuvvetlerde görev yapan kişi.",
        "AVUKAT":       "Mahkemelerde müvekkili temsil eden hukuk uzmanı.",
        "BANKACI":      "Para, kredi ve finansal işlemleri yöneten banka çalışanı.",
        "BERBER":       "Saç ve sakal kesen, erkek bakımı yapan esnaf.",
        "BİYOLOG":      "Canlıları ve yaşam süreçlerini inceleyen bilim insanı.",
        "BOTANİKÇİ":    "Bitkileri, türlerini ve özelliklerini araştıran uzman.",
        "CERRAH":       "Ameliyat yaparak hastalıkları tedavi eden doktor.",
        "DENİZCİ":      "Denizde gemi kullanan veya denizcilikle geçimini sağlayan kişi.",
        "DİŞÇİ":        "Diş sağlığıyla ilgilenen, çürük dolduran, diş çeken hekim.",
        "DİYETİSYEN":   "Beslenme planları yapan, sağlıklı yeme alışkanlıkları öğreten uzman.",
        "DOKTOR":       "Hastaları muayene edip tedavi eden tıp diplomalı kişi.",
        "DUBLÖR":       "Filmlerde tehlikeli sahnelerde oyuncunun yerine geçen kişi.",
        "ECZACI":       "İlaçları hazırlayan ve dağıtan sağlık profesyoneli.",
        "ELEKTRİKÇİ":  "Elektrik tesisatı kuran ve tamir eden teknisyen.",
        "FİZİKÇİ":      "Madde, enerji ve evrenin temel yasalarını araştıran bilim insanı.",
        "FOTOĞRAFÇI":   "Kamerayla anları ölümsüzleştiren, görsel sanatçı.",
        "GARSON":       "Restoran veya kafede sipariş alıp servis yapan çalışan.",
        "GAZETECİ":     "Haber toplayan ve kamuoyuna aktaran medya çalışanı.",
        "GRAFİKER":     "Görsel tasarım ve illüstrasyon yapan yaratıcı profesyonel.",
        "HAKİM":        "Davalar hakkında karar veren, yargı yetkisi olan hukuk görevlisi.",
        "HEMŞİRE":      "Doktorlara yardım eden, hastalara bakım sağlayan sağlık çalışanı.",
        "HEYKELTRAŞ":   "Taş, metal veya ahşaptan üç boyutlu eserler yaratan sanatçı.",
        "HOSTES":       "Uçakta yolculara hizmet veren, güvenlik açıklaması yapan kabin görevlisi.",
        "İKTİSATÇI":    "Ekonomik süreçleri analiz eden ve politika öneren akademisyen.",
        "İNŞAATÇI":     "Bina ve yapı inşaatını gerçekleştiren usta veya müteahhit.",
        "İTFAİYECİ":    "Yangın söndüren, kurtarma operasyonları yapan acil servis görevlisi.",
        "KAPTAN":       "Gemi, uçak veya takımı yöneten lider.",
        "KARDİYOLOG":   "Kalp hastalıklarını teşhis ve tedavi eden uzman doktor.",
        "KASAP":        "Et kesip hazırlayan ve satan esnaf.",
        "KOMEDYEN":     "İnsanları güldürmek için sahneye çıkan sanatçı.",
        "KUAFÖR":       "Saç kesimi, boyama ve şekillendirme yapan güzellik uzmanı.",
        "KURYE":        "Paket veya belge taşıyıp teslim eden görevli.",
        "MANAV":        "Meyve ve sebze satan esnaf.",
        "MİMAR":        "Binaların tasarımını yapan, çizen ve projelendiren uzman.",
        "MUHASEBECİ":   "Şirket ve kişilerin mali kayıtlarını tutan finans uzmanı.",
        "MÜHENDİS":     "Bilim ve matematiği kullanarak teknik sorunlar çözen kişi.",
        "MÜZİSYEN":     "Müzik aleti çalan veya şarkı söyleyen sanatçı.",
        "NÖROLOG":      "Sinir sistemi hastalıklarını teşhis ve tedavi eden uzman.",
        "ORNİTOLOG":    "Kuşları ve davranışlarını inceleyen zooloji uzmanı.",
        "PALEONTOLOG":  "Fosilleri ve soyu tükenmiş canlıları araştıran bilim insanı.",
        "PİLOT":        "Uçak veya helikopter kullanan yetkili kişi.",
        "POLİS":        "Kamu düzenini koruyan, suçları önleyen güvenlik görevlisi.",
        "PSİKOLOG":     "Zihinsel ve davranışsal sorunları inceleyen uzman.",
        "REKLAMCI":     "Ürün ve hizmetleri tanıtmak için kampanyalar tasarlayan kişi.",
        "RESSAM":       "Boya ve fırçayla tablolar yapan görsel sanatçı.",
        "SENARİST":     "Film, dizi veya tiyatro için hikayeler ve diyaloglar yazan kişi.",
        "SOSYOLOG":     "Toplumsal yapıları ve insan ilişkilerini araştıran bilim insanı.",
        "SUBAY":        "Ordu, deniz kuvvetleri veya hava kuvvetlerinde komuta yetkisi olan asker.",
        "ŞOFÖR":        "Araç kullanan, taşımacılık yapan kişi.",
        "TERZİ":        "Kumaş keserek giysi diken, onarım yapan zanaatçı.",
        "TEKNİSYEN":    "Teknik arıza ve bakımı gerçekleştiren uygulamalı çalışan.",
        "TAMİRCİ":      "Bozuk araç gereç veya makineleri onaran kişi.",
        "VETERİNER":    "Hayvanları tedavi eden hayvan doktoru.",
        "YAZILIMCI":    "Bilgisayar programları ve uygulamalar geliştiren kişi.",
        "YÖNETMEN":     "Film veya tiyatro yapımını yöneten sanatçı.",
    ]
}
