import Foundation

extension WordList {

    // MARK: - Words

    static let sanatWords: [WordEntry] = [
        WordEntry(word: "AKRİLİK",     category: "Sanat"),
        WordEntry(word: "ANİMASYON",   category: "Sanat"),
        WordEntry(word: "ATÖLYE",      category: "Sanat"),
        WordEntry(word: "BOYA",        category: "Sanat"),
        WordEntry(word: "ÇİZİM",       category: "Sanat"),
        WordEntry(word: "ESKİZ",       category: "Sanat"),
        WordEntry(word: "FRESK",       category: "Sanat"),
        WordEntry(word: "FIRÇA",       category: "Sanat"),
        WordEntry(word: "GALERİ",      category: "Sanat"),
        WordEntry(word: "GRAVÜR",      category: "Sanat"),
        WordEntry(word: "HEYKEL",      category: "Sanat"),
        WordEntry(word: "İLLÜSTRASYON",category: "Sanat"),
        WordEntry(word: "KALİGRAFİ",   category: "Sanat"),
        WordEntry(word: "KARİKATÜR",   category: "Sanat"),
        WordEntry(word: "KOLAJ",       category: "Sanat"),
        WordEntry(word: "LİTOGRAFİ",   category: "Sanat"),
        WordEntry(word: "MİNYATÜR",    category: "Sanat"),
        WordEntry(word: "MOZAİK",      category: "Sanat"),
        WordEntry(word: "MÜZE",        category: "Sanat"),
        WordEntry(word: "PALET",       category: "Sanat"),
        WordEntry(word: "PEYZAJ",      category: "Sanat"),
        WordEntry(word: "PORTRE",      category: "Sanat"),
        WordEntry(word: "RÖLYEF",      category: "Sanat"),
        WordEntry(word: "SANATÇI",     category: "Sanat"),
        WordEntry(word: "SERAMİK",     category: "Sanat"),
        WordEntry(word: "SERGİ",       category: "Sanat"),
        WordEntry(word: "SULUBOYA",    category: "Sanat"),
        WordEntry(word: "ŞÖVALE",      category: "Sanat"),
        WordEntry(word: "TABLO",       category: "Sanat"),
        WordEntry(word: "TARZ",        category: "Sanat"),
        WordEntry(word: "TUVAL",       category: "Sanat"),
        WordEntry(word: "YAĞLIBOYA",   category: "Sanat"),
    ]

    // MARK: - Hints

    static let sanatHints: [String: String] = [
        "EMPRESYONIZM": "19. yüzyılda ışık ve rengi ön plana çıkaran Fransız resim akımı.",
        "KALİGRAFİ":    "Güzel ve estetik el yazısı yazma sanatı.",
        "KOLAJ":        "Farklı malzemeleri keserek yapıştırarak oluşturulan sanat eseri.",
        "MİNYATÜR":     "İnce detaylı, küçük ölçekli resim geleneği, Osmanlı'da yaygın.",
        "MOZAİK":       "Küçük renkli taş veya cam parçalarıyla oluşturulan resim.",
        "ORİGAMİ":      "Kağıdı katlayarak çeşitli şekiller yapma Japon sanatı.",
        "RÖLYEF":       "Düz bir zemin üzerinde yükselen üç boyutlu kabartma.",
        "SÜRREALIZM":   "Bilinçaltını ve rüyaları temsil eden, hayali-gerçek dışı sanat akımı.",
        "HEYKELTİRAŞ":  "Taş, metal veya ahşaptan üç boyutlu eserler yaratan sanatçı.",
        "AKRİLİK":      "Hızlı kuruyan, su bazlı plastik boya; tuval ve kağıtta kullanılır.",
        "ANİMASYON":    "Durağan çizimleri ya da nesneleri hareket illüzyonuyla canlandırma sanatı.",
        "ATÖLYE":       "Sanatçının eserlerini ürettiği ve çalıştığı özel stüdyo ya da çalışma odası.",
        "BOYA":         "Yüzeylere renk vermek için kullanılan sıvı ya da katı pigment karışımı.",
        "ÇİZİM":        "Kalem, karakalem ya da mürekkeptle kağıda yapılan şekil ve görüntü.",
        "ESKİZ":        "Bir eserin ilk taslak çizimi; ayrıntısız, hızlıca yapılan ön çalışma.",
        "FRESK":        "Islak sıva üzerine boyanan, duvar yüzeyine işlenmiş kalıcı resim.",
        "FIRÇA":        "Boyayı yüzeye uygulamak için kullanılan, kıllı uçlu alet.",
        "GALERİ":       "Sanat eserlerinin sergilendiği ve satışa sunulduğu özel mekân.",
        "GRAVÜR":       "Metal ya da ahşap yüzeye kazınarak çoğaltılan baskı resim tekniği.",
        "HEYKEL":       "Taş, metal, ahşap veya kil gibi malzemeden yapılan üç boyutlu sanat eseri.",
        "İLLÜSTRASYON": "Kitap, dergi ya da dijital içerikleri görselleştiren açıklayıcı çizim.",
        "KARİKATÜR":    "Kişi veya olayları abartılı, eleştirel bir biçimde betimleyen mizahi çizim.",
        "LİTOGRAFİ":    "Yağ ve su itişiminden yararlanan, düz taş üzerine baskı resim tekniği.",
        "MÜZE":         "Sanat, tarih veya bilim eserlerinin korunup sergilendiği kamu kurumu.",
        "PALET":        "Boyaları karıştırmak için kullanılan, tutamaklı düz oval levha.",
        "PEYZAJ":       "Doğa manzaralarını konu alan resim ya da fotoğraf türü.",
        "PORTRE":       "Bir kişinin yüz ve üst bedenini konu alan resim ya da fotoğraf.",
        "SANATÇI":      "Özgün eserler yaratan, yaratıcılığını sanata dönüştüren kişi.",
        "SERAMİK":      "Topraktan şekillendirilerek fırında pişirilen kap, kase ve süs eşyası.",
        "SERGİ":        "Sanat eserlerinin izleyiciye sunulduğu geçici ya da kalıcı etkinlik.",
        "SULUBOYA":     "Su ile seyreltilen, şeffaf renkli boya; kağıt üzerinde kullanılır.",
        "ŞÖVALE":       "Tuvali dik tutmak için kullanılan, üç ya da dört ayaklı taşıyıcı stand.",
        "TABLO":        "Çerçeveye yerleştirilen tuval ya da tahta üzerine yapılmış resim eseri.",
        "TARZ":         "Bir sanatçının ya da dönemin ayırt edici anlatım biçimi ve üslubu.",
        "TUVAL":        "Üzerine yağlıboya ya da akrilik boyanan, kasnaklı keten bez.",
        "YAĞLIBOYA":    "Yağ bazlı boya kullanılan, zengin renk ve dokular yaratan resim tekniği.",
    ]
}
