import Foundation

extension WordList {

    // MARK: - Words

    static let markalarWords: [WordEntry] = [
        WordEntry(word: "ADIDAS", category: "Markalar"),
        WordEntry(word: "AIRBNB", category: "Markalar"),
        WordEntry(word: "AMAZON", category: "Markalar"),
        WordEntry(word: "APPLE", category: "Markalar"),
        WordEntry(word: "ARMANI", category: "Markalar"),
        WordEntry(word: "ASTON MARTIN", category: "Markalar"),
        WordEntry(word: "BALMAIN", category: "Markalar"),
        WordEntry(word: "BENTLEY", category: "Markalar"),
        WordEntry(word: "BMW", category: "Markalar"),
        WordEntry(word: "BIRKENSTOCK", category: "Markalar"),
        WordEntry(word: "BURBERRY", category: "Markalar"),
        WordEntry(word: "BUGATTI", category: "Markalar"),
        WordEntry(word: "BURGER KING", category: "Markalar"),
        WordEntry(word: "CADILLAC", category: "Markalar"),
        WordEntry(word: "CALVIN KLEIN", category: "Markalar"),
        WordEntry(word: "CANON", category: "Markalar"),
        WordEntry(word: "CARTIER", category: "Markalar"),
        WordEntry(word: "CASIO", category: "Markalar"),
        WordEntry(word: "CHEVROLET", category: "Markalar"),
        WordEntry(word: "CHANEL", category: "Markalar"),
        WordEntry(word: "CHAMPION", category: "Markalar"),
        WordEntry(word: "CLINIQUE", category: "Markalar"),
        WordEntry(word: "COCA COLA", category: "Markalar"),
        WordEntry(word: "COLUMBIA", category: "Markalar"),
        WordEntry(word: "CONVERSE", category: "Markalar"),
        WordEntry(word: "DISNEY", category: "Markalar"),
        WordEntry(word: "DOLCE GABBANA", category: "Markalar"),
        WordEntry(word: "EMIRATES", category: "Markalar"),
        WordEntry(word: "FACEBOOK", category: "Markalar"),
        WordEntry(word: "FENDI", category: "Markalar"),
        WordEntry(word: "FERRARI", category: "Markalar"),
        WordEntry(word: "FERRERO", category: "Markalar"),
        WordEntry(word: "GARNIER", category: "Markalar"),
        WordEntry(word: "GIVENCHY", category: "Markalar"),
        WordEntry(word: "GOOGLE", category: "Markalar"),
        WordEntry(word: "GUCCI", category: "Markalar"),
        WordEntry(word: "HARIBO", category: "Markalar"),
        WordEntry(word: "HERMES", category: "Markalar"),
        WordEntry(word: "HILTON", category: "Markalar"),
        WordEntry(word: "HONDA", category: "Markalar"),
        WordEntry(word: "HUAWEI", category: "Markalar"),
        WordEntry(word: "HUGO BOSS", category: "Markalar"),
        WordEntry(word: "HYUNDAI", category: "Markalar"),
        WordEntry(word: "IKEA", category: "Markalar"),
        WordEntry(word: "INTEL", category: "Markalar"),
        WordEntry(word: "INSTAGRAM", category: "Markalar"),
        WordEntry(word: "JEEP", category: "Markalar"),
        WordEntry(word: "KENZO", category: "Markalar"),
        WordEntry(word: "LAND ROVER", category: "Markalar"),
        WordEntry(word: "LAMBORGHINI", category: "Markalar"),
        WordEntry(word: "LACOSTE", category: "Markalar"),
        WordEntry(word: "LANCOME", category: "Markalar"),
        WordEntry(word: "LEGO", category: "Markalar"),
        WordEntry(word: "LENOVO", category: "Markalar"),
        WordEntry(word: "LINKEDIN", category: "Markalar"),
        WordEntry(word: "LINDT", category: "Markalar"),
        WordEntry(word: "LOGITECH", category: "Markalar"),
        WordEntry(word: "LOREAL", category: "Markalar"),
        WordEntry(word: "LUFTHANSA", category: "Markalar"),
        WordEntry(word: "MAZDA", category: "Markalar"),
        WordEntry(word: "MARRIOTT", category: "Markalar"),
        WordEntry(word: "MASERATI", category: "Markalar"),
        WordEntry(word: "MAYBELLINE", category: "Markalar"),
        WordEntry(word: "MCDONALDS", category: "Markalar"),
        WordEntry(word: "MERCEDES", category: "Markalar"),
        WordEntry(word: "MICHAEL KORS", category: "Markalar"),
        WordEntry(word: "MICROSOFT", category: "Markalar"),
        WordEntry(word: "MILKA", category: "Markalar"),
        WordEntry(word: "MITSUBISHI", category: "Markalar"),
        WordEntry(word: "MONCLER", category: "Markalar"),
        WordEntry(word: "MONTBLANC", category: "Markalar"),
        WordEntry(word: "NESCAFE", category: "Markalar"),
        WordEntry(word: "NETFLIX", category: "Markalar"),
        WordEntry(word: "NEW BALANCE", category: "Markalar"),
        WordEntry(word: "NIKE", category: "Markalar"),
        WordEntry(word: "NISSAN", category: "Markalar"),
        WordEntry(word: "NIVEA", category: "Markalar"),
        WordEntry(word: "NOKIA", category: "Markalar"),
        WordEntry(word: "NUTELLA", category: "Markalar"),
        WordEntry(word: "OMEGA", category: "Markalar"),
        WordEntry(word: "PANASONIC", category: "Markalar"),
        WordEntry(word: "PANTENE", category: "Markalar"),
        WordEntry(word: "PEPSI", category: "Markalar"),
        WordEntry(word: "PHILIPS", category: "Markalar"),
        WordEntry(word: "PORSCHE", category: "Markalar"),
        WordEntry(word: "PRINGLES", category: "Markalar"),
        WordEntry(word: "PUMA", category: "Markalar"),
        WordEntry(word: "RAY BAN", category: "Markalar"),
        WordEntry(word: "REEBOK", category: "Markalar"),
        WordEntry(word: "RENAULT", category: "Markalar"),
        WordEntry(word: "ROLEX", category: "Markalar"),
        WordEntry(word: "ROLLS ROYCE", category: "Markalar"),
        WordEntry(word: "RYANAIR", category: "Markalar"),
        WordEntry(word: "SAMSUNG", category: "Markalar"),
        WordEntry(word: "SNAPCHAT", category: "Markalar"),
        WordEntry(word: "SNICKERS", category: "Markalar"),
        WordEntry(word: "SONY", category: "Markalar"),
        WordEntry(word: "SPOTIFY", category: "Markalar"),
        WordEntry(word: "STARBUCKS", category: "Markalar"),
        WordEntry(word: "SUBARU", category: "Markalar"),
        WordEntry(word: "SWAROVSKI", category: "Markalar"),
        WordEntry(word: "TESLA", category: "Markalar"),
        WordEntry(word: "TIKTOK", category: "Markalar"),
        WordEntry(word: "TISSOT", category: "Markalar"),
        WordEntry(word: "TOBLERONE", category: "Markalar"),
        WordEntry(word: "TOYOTA", category: "Markalar"),
        WordEntry(word: "TOSHIBA", category: "Markalar"),
        WordEntry(word: "VALENTINO", category: "Markalar"),
        WordEntry(word: "VERSACE", category: "Markalar"),
        WordEntry(word: "VOLKSWAGEN", category: "Markalar"),
        WordEntry(word: "VOLVO", category: "Markalar"),
        WordEntry(word: "WALMART", category: "Markalar"),
        WordEntry(word: "WHATSAPP", category: "Markalar"),
        WordEntry(word: "XIAOMI", category: "Markalar"),
        WordEntry(word: "YOUTUBE", category: "Markalar"),
        WordEntry(word: "ZARA", category: "Markalar"),
    ]

    // MARK: - Hints

    static let markalarHints: [String: String] = [
        "ADIDAS":           "Almanya'dan çıkan üç çizgili logosuyla dünya genelinde bilinen spor markası.",
        "AIRBNB":           "Seyahat edenleri yerel ev sahipleriyle buluşturan, ABD kökenli kira platformu.",
        "AMAZON":           "Jeff Bezos'un kurduğu, dünyanın en büyük e-ticaret ve bulut bilişim şirketi.",
        "APPLE":            "Isırılmış elma logosuyla tanınan, iPhone ve Mac bilgisayarlarıyla ünlü ABD teknoloji devi.",
        "ARMANI":           "İtalyan Giorgio'nun kurduğu, sade ve zarif çizgisiyle tanınan lüks moda evi.",
        "ASTON MARTIN":     "James Bond filmlerinde kullanılan araçlarıyla efsaneleşen İngiliz spor otomobil üreticisi.",
        "BALMAIN":          "Fransız lüks moda evi; omuz hatları ve askeri detaylarıyla dikkat çeker.",
        "BENTLEY":          "El yapımı lüks otomobilleriyle tanınan, İngiltere kökenli prestijli araç markası.",
        "BMW":              "Bavyera motorlarından doğan, mavi-beyaz pervane logosuyla tanınan Alman otomobil markası.",
        "BIRKENSTOCK":      "Alman kökenli, mantar tabanlı sandalet ve ayakkabılarıyla bilinen konfor markası.",
        "BURBERRY":         "Eşsiz ekose deseni ve trençkotlarıyla ünlü İngiliz lüks moda markası.",
        "BUGATTI":          "Fransa'da üretilen, dünyanın en hızlı ve en pahalı otomobillerini yapan İtalyan asıllı marka.",
        "BURGER KING":      "Hamburger ve Whopper sandviçiyle ünlü, ABD kökenli fast-food zinciri.",
        "CADILLAC":         "Amerikan lüksünün simgesi olan, uzun gövdeli otomobilleriyle tanınan ABD markası.",
        "CALVIN KLEIN":     "Minimal tasarımı ve kot pantolonlarıyla ünlü Amerikan moda markası.",
        "CANON":            "Japon kökenli, kamera ve yazıcı alanındaki çözümleriyle dünyaca bilinen elektronik markası.",
        "CARTIER":          "Kraliyet mücevhercisi olarak bilinen, kırmızı kutusuyla tanınan Fransız lüks marka.",
        "CASIO":            "Elektronik saat ve hesap makinesiyle ünlü, Japon tüketici elektroniği markası.",
        "CHEVROLET":        "Altın renkli ilmek logosuyla bilinen, Amerikan otomobil endüstrisinin köklü markası.",
        "CHANEL":           "Coco'nun kurduğu, siyah-beyaz şıklığı ve No.5 parfümüyle simgeleşen Fransız moda evi.",
        "CHAMPION":         "C logosundan tanınan, spor giyim ve sweatshirt dünyasının ABD kökenli öncü markası.",
        "CLINIQUE":         "Dermatolog testi yapılmış ürünleriyle bilinen, ABD kökenli güzellik markası.",
        "COCA COLA":        "Kırmızı-beyaz renkleri ve dalgalı yazısıyla tanınan, dünyanın en ikonik meşrubat markası.",
        "COLUMBIA":         "Açık hava giyim ve ekipmanlarıyla bilinen, ABD kökenli outdoor markası.",
        "CONVERSE":         "Yıldız işaretli bilekliğiyle tanınan, Chuck Taylor'ın simgeleştiği ABD ayakkabı markası.",
        "DISNEY":           "Sihirli bir fare maskotun kurduğu dev; prensesler, karikatürler ve theme park'larıyla ünlü.",
        "DOLCE GABBANA":    "Sicilya'dan ilham alan, zengin desen ve altın detaylarıyla ünlü İtalyan moda ikilisi.",
        "EMIRATES":         "Dubai merkezli, dünyanın en büyük uzun mesafeli havayolu şirketlerinden biri.",
        "FACEBOOK":         "Mark Zuckerberg'in Harvard'da kurduğu, dünya genelinde en kalabalık sosyal ağ.",
        "FENDI":            "Çift F logosuyla tanınan, Roma kökenli İtalyan lüks deri ve moda evi.",
        "FERRARI":          "İtalya'nın Maranello kentinden çıkan, şahane at amblemli kırmızı spor otomobil markası.",
        "FERRERO":          "Fındık kreması ve altın kaplı çikolatasiyla tanınan, İtalyan şeker üreticisi.",
        "GARNIER":          "Fransa kökenli, saç ve cilt bakım ürünleriyle yaygın bilinen kitlesel güzellik markası.",
        "GIVENCHY":         "Audrey Hepburn ile özdeşleşen, Fransız lüks moda ve parfüm evi.",
        "GOOGLE":           "Renkli logosu ve arama motoru ile dijital dünyaya yön veren ABD teknoloji devi.",
        "GUCCI":            "Çift G logosu ve bambu saplı çantalarıyla tanınan, Floransalı İtalyan lüks moda evi.",
        "HARIBO":           "Sarı ayı şeklindeki şeker bonbonlarıyla çocukların gözde Alman markası.",
        "HERMES":           "Turuncu kutusundan tanınan, Birkin ve Kelly çantalarıyla efsaneleşen Fransız lüks deri evi.",
        "HILTON":           "Paris Hilton'un soyundan gelen bir ailenin kurduğu, dünya genelinde zincirleri olan otel markası.",
        "HONDA":            "Motosiklet ve ekonomik otomobilleriyle öne çıkan, Japon motor üreticisi.",
        "HUAWEI":           "Çin'in en büyük telekom altyapısı ve akıllı telefon üreticisi.",
        "HUGO BOSS":        "Almanya'da kurulan, takım elbise ve erkek giyimiyle öne çıkan lüks moda markası.",
        "HYUNDAI":          "Kore'nin küresel çapta en tanınmış otomobil üreticilerinden biri.",
        "IKEA":             "İsveç'te bir çiftlik evinin adından ilham alan, montajlı mobilyalarıyla ünlü mağaza zinciri.",
        "INTEL":            "İşlemci çipiyle bilgisayar dünyasını şekillendiren, Silikon Vadisi merkezli ABD teknoloji firması.",
        "INSTAGRAM":        "Fotoğraf ve video paylaşımını merkeze alan, Meta bünyesindeki sosyal medya uygulaması.",
        "JEEP":             "İkinci Dünya Savaşı'nda doğan, off-road gücüyle ünlü Amerikan araç markası.",
        "KENZO":            "Japon tasarımcı Takada'nın Paris'te kurduğu, canlı renk ve çiçek desenleriyle bilinen marka.",
        "LAND ROVER":       "İngiliz yapımı, zorlu arazileri aşacak şekilde tasarlanan 4x4 araç markası.",
        "LAMBORGHINI":      "İtalya'da boğa amblemiyle üretilen, aşırı performanslı spor otomobil markası.",
        "LACOSTE":          "Fransız tenisçi René'nin kurduğu, timsah logosuyla tanınan spor giyim markası.",
        "LANCOME":          "Fransız kökenli, gül aromalı parfümleri ve lüks kozmetikleriyle bilinen güzellik markası.",
        "LEGO":             "Danimarkalı, plastik yapı taşlarıyla hayal gücünü serbest bırakan oyuncak markası.",
        "LENOVO":           "Çin kökenli, ThinkPad laptop serisiyle dünya genelinde tanınan teknoloji şirketi.",
        "LINKEDIN":         "Profesyonellerin ağ kurmasını sağlayan, Microsoft bünyesindeki kariyer platformu.",
        "LINDT":            "İsviçreli, kırmızı altın ambalajlı hindi çikolataları ve pürüzsüz lezzeti ile ünlü marka.",
        "LOGITECH":         "İsviçreli, fare ve klavye gibi bilgisayar çevre birimlerinde uzmanlaşmış teknoloji markası.",
        "LOREAL":           "'Çünkü değersiniz' sloganıyla bilinen, Fransa kökenli dünyanın en büyük kozmetik grubu.",
        "LUFTHANSA":        "Turna kuşu logosuyla tanınan, Almanya'nın ulusal havayolu şirketi.",
        "MAZDA":            "Japon kökenli, dönen rotary motoruyla ilgi çeken otomobil üreticisi.",
        "MARRIOTT":         "ABD merkezli, dünyanın en büyük otel zinciri gruplarından biri.",
        "MASERATI":         "Trident amblemiyle tanınan, İtalyan üretimi lüks ve yüksek performanslı otomobil markası.",
        "MAYBELLINE":       "'New York'tan geliyor' sloganıyla bilinen, ABD kökenli kitlesel makyaj markası.",
        "MCDONALDS":        "Altın M logosuyla dünyada yaygın olan, hamburger ve patates kızartmasıyla bilinen zincir.",
        "MERCEDES":         "Üç kollu yıldız amblemiyle tanınan, Almanya'nın en prestijli otomobil markası.",
        "MICHAEL KORS":     "New York merkezli, jet set yaşamı simgeleyen ABD lüks moda markası.",
        "MICROSOFT":        "Windows işletim sistemi ve Office yazılımıyla dünyayı etkileyen Bill Gates'in kurduğu şirket.",
        "MILKA":            "Mor ambalajı ve mor inekle sembolleşen, Alpler'den ilham alan sütlü çikolata markası.",
        "MITSUBISHI":       "Üç elmas logosuyla tanınan, otomobilden elektroniğe geniş ürün yelpazeli Japon şirketi.",
        "MONCLER":          "Fransız dağcılık geleneğinden doğan, kabarık tüy montlarıyla lüks moda dünyasındaki yerini alan marka.",
        "MONTBLANC":        "Alp karından ilham alan beyaz yıldız logosuyla tanınan, Alman lüks dolmakalem ve aksesuar markası.",
        "NESCAFE":          "Neredeyse tüm dünyada sabah kahvesi ritüelini şekillendiren İsviçreli çözünür kahve markası.",
        "NETFLIX":          "Kırmızı N harfiyle tanınan, dizi ve film akış hizmetinde dünyanın öncü platformu.",
        "NEW BALANCE":      "NB harfleriyle bilinen, koşu ayakkabısı ve konforuyla öne çıkan Amerikan spor markası.",
        "NIKE":             "Swoosh işareti ve 'Just Do It' sloganıyla dünyanın en tanınmış spor giyim markası.",
        "NISSAN":           "Japonya'dan çıkan, elektrikli Leaf modeliyle öne çıkan kitlesel otomobil üreticisi.",
        "NIVEA":            "Mavi teneke kutusundaki nemlendirici kremiyle dünyaya yayılan Alman cilt bakım markası.",
        "NOKIA":            "Finlandiya kökenli, tuş telefonlar çağının sembolü olan telekomünikasyon markası.",
        "NUTELLA":          "Fındık ve kakaolu kremasıyla kahvaltı masalarının vazgeçilmezi olan İtalyan sürme ürünü.",
        "OMEGA":            "İsviçreli, Ay'a ilk giden astronotun bileğinde bulunan saat markası.",
        "PANASONIC":        "Japonya'nın Osaka kentinde kurulan, geniş elektronik ürün yelpazesiyle tanınan marka.",
        "PANTENE":          "Pro-V formülüyle bilinen, parlak ve sağlıklı saç vaat eden ABD kökenli şampuan markası.",
        "PEPSI":            "Kırmızı-beyaz-mavi küresel logosuyla, kola içeceği pazarındaki en büyük rakip.",
        "PHILIPS":          "Hollandalı, sağlık teknolojisinden ev aletlerine uzanan geniş yelpaziyle bilinen elektronik markası.",
        "PORSCHE":          "Stuttgart'ta doğan, at amblemiyle tanınan Alman spor ve lüks otomobil üreticisi.",
        "PRINGLES":         "Silindir tüpündeki Pringles Bay maskotu ile akılda kalan patates cipsi markası.",
        "PUMA":             "Puma hayvanını logosunda taşıyan, Almanya kökenli spor ve atletizm giyim markası.",
        "RAY BAN":          "Pilot gözlüğü ve Wayfarer modelleriyle ikonikleşen, İtalyan asıllı güneş gözlüğü markası.",
        "REEBOK":           "İngiltere'de doğan, aerobik ve fitness dünyasında öncü olan ABD merkezli spor markası.",
        "RENAULT":          "Lozan'daki sarı elmas logosuyla tanınan, Fransa'nın köklü otomobil üreticisi.",
        "ROLEX":            "Taç logosuyla tanınan, İsviçreli prestijin sembolü olan lüks saat markası.",
        "ROLLS ROYCE":      "Spirit of Ecstasy heykelciğiyle tanınan, İngiliz el yapımı ultra lüks otomobil markası.",
        "RYANAIR":          "Çok düşük biletleriyle öne çıkan, İrlandalı düşük maliyetli havayolu şirketi.",
        "SAMSUNG":          "Mavi renk ve elektronik çeşitliliğiyle tanınan, Güney Koreli teknoloji devi.",
        "SNAPCHAT":         "Hayalet maskotu ve kaybolur fotoğraf özelliğiyle gençlerin kullandığı ABD'li sosyal uygulama.",
        "SNICKERS":         "Fıstık, karamel ve çikolatayla dolu; 'Acıkınca kendini kaybetme' sloganıyla ünlü bar.",
        "SONY":             "PlayStation, Walkman ve TV'siyle tanınan, Japonya kökenli çok uluslu elektronik ve eğlence devi.",
        "SPOTIFY":          "Yeşil dalga logosuyla tanınan, İsveçli müzik akış platformu.",
        "STARBUCKS":        "Deniz kızı logosuyla tanınan, seattle kökenli küresel kahve zinciri.",
        "SUBARU":           "Perya yıldızlarından ilham alan logosuyla bilinen, Japon otomobil üreticisi.",
        "SWAROVSKI":        "Avusturyalı, elle işlenen kristalleri ve mücevherleriyle tanınan lüks aksesuar markası.",
        "TESLA":            "Elon Musk'ın önderliğinde elektrikli araçları ana akıma sokan Silikon Vadisi otomobil markası.",
        "TIKTOK":           "Kısa video içerikleriyle gençler arasında hızla yayılan, Çin kökenli sosyal medya uygulaması.",
        "TISSOT":           "İsviçreli, uygun fiyatlı lüks saatleriyle bilinen, TAG Heuer'ın kardeş markası.",
        "TOBLERONE":        "İsviçre Alpleri'nden ilham alan, üçgen prizma şeklindeki nougat çikolata.",
        "TOYOTA":           "Güvenilirliği ve hibrit Prius modeliyle öne çıkan, Japonya'nın en büyük otomobil üreticisi.",
        "TOSHIBA":          "Japonya'da kurulan, bilgisayar ve yarı iletken alanında köklü teknoloji şirketi.",
        "VALENTINO":        "Roma kökenli, kırmızı elbiseler ve çiçek işlemeleriyle tanınan İtalyan lüks moda evi.",
        "VERSACE":          "Medusa başı amblemiyle tanınan, cesur desen ve altın detaylı İtalyan lüks moda evi.",
        "VOLKSWAGEN":       "Halkın arabası anlamına gelen, VW logosuyla bilinen Alman otomobil üreticisi.",
        "VOLVO":            "Güvenlik teknolojilerinin öncüsü olarak bilinen, İsveçli otomobil markası.",
        "WALMART":          "ABD merkezli, dünyanın en büyük perakende zinciri olan süpermarket grubu.",
        "WHATSAPP":         "Yeşil telefon simgesiyle tanınan, Meta bünyesindeki anlık mesajlaşma uygulaması.",
        "XIAOMI":           "Mi logosuyla tanınan, uygun fiyatlı akıllı telefon ve akıllı ev ürünleriyle büyüyen Çin markası.",
        "YOUTUBE":          "Google bünyesindeki, kırmızı play tuşuyla dünyaya yayın yapan video paylaşım platformu.",
        "ZARA":             "İspanyolların Amancio Ortega'sının kurduğu, hızlı moda anlayışıyla öne çıkan giyim zinciri.",
    ]
}
