import Foundation

extension WordList {

    // MARK: - Words

    static let tarihPlusWords: [WordEntry] = [
        WordEntry(word: "OSMANLI",         category: "Tarih+"),
        WordEntry(word: "BİZANS",          category: "Tarih+"),
        WordEntry(word: "SELÇUKLU",        category: "Tarih+"),
        WordEntry(word: "FATİH",           category: "Tarih+"),
        WordEntry(word: "KANUNİ",          category: "Tarih+"),
        WordEntry(word: "ATATÜRK",         category: "Tarih+"),
        WordEntry(word: "KURTULUŞ",        category: "Tarih+"),
        WordEntry(word: "CUMHURİYET",      category: "Tarih+"),
        WordEntry(word: "İSTİKLAL",        category: "Tarih+"),
        WordEntry(word: "GALİPOLİ",        category: "Tarih+"),
        WordEntry(word: "ÇANAKKALE",       category: "Tarih+"),
        WordEntry(word: "İNEBOLU",         category: "Tarih+"),
        WordEntry(word: "DUMLUPINAR",      category: "Tarih+"),
        WordEntry(word: "MALAZGİRT",       category: "Tarih+"),
        WordEntry(word: "MOHAÇ",           category: "Tarih+"),
        WordEntry(word: "VİYANA",          category: "Tarih+"),
        WordEntry(word: "ANKARA",          category: "Tarih+"),
        WordEntry(word: "SAMSUN",          category: "Tarih+"),
        WordEntry(word: "ERZURUM",         category: "Tarih+"),
        WordEntry(word: "SİVAS",           category: "Tarih+"),
        WordEntry(word: "İNÖNÜ",           category: "Tarih+"),
        WordEntry(word: "SAKARYA",         category: "Tarih+"),
        WordEntry(word: "LOZAN",           category: "Tarih+"),
        WordEntry(word: "MUDANYA",         category: "Tarih+"),
        WordEntry(word: "SEVR",            category: "Tarih+"),
        WordEntry(word: "DEVLETÇİLİK",     category: "Tarih+"),
        WordEntry(word: "MİLLİYETÇİLİK",   category: "Tarih+"),
        WordEntry(word: "LAİKLİK",         category: "Tarih+"),
        WordEntry(word: "İNKILAP",         category: "Tarih+"),
        WordEntry(word: "TANZİMAT",        category: "Tarih+"),
        WordEntry(word: "MEŞRUTİYET",      category: "Tarih+"),
        WordEntry(word: "PADİŞAH",         category: "Tarih+"),
        WordEntry(word: "VEZİR",           category: "Tarih+"),
        WordEntry(word: "DİVAN",           category: "Tarih+"),
        WordEntry(word: "TUĞRA",           category: "Tarih+"),
        WordEntry(word: "MİMARSİNAN",      category: "Tarih+"),
        WordEntry(word: "BARBAROS",        category: "Tarih+"),
        WordEntry(word: "PİRİREİS",        category: "Tarih+"),
        WordEntry(word: "EVLİYAÇELEBİ",    category: "Tarih+"),
        WordEntry(word: "KATİPÇELEBİ",     category: "Tarih+"),
        WordEntry(word: "FARABİ",          category: "Tarih+"),
        WordEntry(word: "İBNİSİNA",        category: "Tarih+"),
        WordEntry(word: "ULUĞBEY",         category: "Tarih+"),
        WordEntry(word: "MEVLANA",         category: "Tarih+"),
        WordEntry(word: "YUNUS",           category: "Tarih+"),
        WordEntry(word: "HACIBEKTAŞ",      category: "Tarih+"),
        WordEntry(word: "PİRİSULTAN",      category: "Tarih+"),
        WordEntry(word: "ŞEYHEDEBALI",     category: "Tarih+"),
        WordEntry(word: "ALPARSLAN",       category: "Tarih+"),
        WordEntry(word: "TOPRAKAĞA",       category: "Tarih+"),
        WordEntry(word: "AYASOFYA",        category: "Tarih+"),
        WordEntry(word: "TOPKAPI",         category: "Tarih+"),
        WordEntry(word: "DOLMABAHÇE",      category: "Tarih+"),
        WordEntry(word: "KAPADOKYA",       category: "Tarih+"),
        WordEntry(word: "ANITKABİR",       category: "Tarih+"),
        WordEntry(word: "GAZİ",            category: "Tarih+"),
        WordEntry(word: "ŞEHİT",           category: "Tarih+"),
        WordEntry(word: "MEHTERAN",        category: "Tarih+"),
        WordEntry(word: "YENİÇERİ",        category: "Tarih+"),
        WordEntry(word: "KIRIM",           category: "Tarih+"),
    ]

    // MARK: - Hints

    static let tarihPlusHints: [String: String] = [
        "OSMANLI":         "Altı yüz yıl boyunca üç kıtaya hükmeden ve İstanbul'u başkent yapan büyük imparatorluk.",
        "BİZANS":          "Doğu Roma'nın devamı olarak İstanbul merkezinde bin yılı aşkın süre yaşayan imparatorluk.",
        "SELÇUKLU":        "Anadolu'yu yurt edinen ve Türk-İslam medeniyetini Orta Asya'dan batıya taşıyan devlet.",
        "FATİH":           "1453'te Konstantinopolis'i fethederek tarihin akışını değiştiren Osmanlı padişahı.",
        "KANUNİ":          "Osmanlı'nın en görkemli dönemini yaşatan ve Avrupa'yı dehşete düşüren padişah.",
        "ATATÜRK":         "Türkiye Cumhuriyeti'ni kuran, toplumu çağdaşlaştıran asker ve devlet adamı.",
        "KURTULUŞ":        "Türk milletinin işgale karşı verdiği ve bağımsızlıkla sonuçlanan mücadelenin adı.",
        "CUMHURİYET":      "Halkın kendi kendini yönettiği, 1923'te ilan edilen Türkiye'nin temel yönetim biçimi.",
        "İSTİKLAL":        "Bağımsızlığı simgeleyen ve Kurtuluş Savaşı ruhunu yansıtan onur sözcüğü.",
        "GALİPOLİ":        "Çanakkale Savaşı'nın uluslararası literatürdeki adı; büyük kayıpların yaşandığı cephe.",
        "ÇANAKKALE":       "Birinci Dünya Savaşı'nda Türk kuvvetlerinin düşmanı durdurup geçirmediği boğaz.",
        "İNEBOLU":         "Kurtuluş Savaşı döneminde silah ve cephanenin karaya çıkarıldığı Karadeniz kenti.",
        "DUMLUPINAR":      "Kurtuluş Savaşı'nın son ve belirleyici büyük zaferinin kazanıldığı yer.",
        "MALAZGİRT":       "1071'de Türklerin Anadolu'nun kapılarını açtığı tarihi zafer alanı.",
        "MOHAÇ":           "1526'da Osmanlı ordusunun Macar Krallığını yıkarak Orta Avrupa'ya egemen olduğu savaş.",
        "VİYANA":          "Osmanlı ordusunun iki kez kuşatıp alamadığı, Habsburgların kalesi olan Avusturya başkenti.",
        "ANKARA":          "Kurtuluş Savaşı'nın merkezi olan ve sonrasında Türkiye Cumhuriyeti'nin başkenti olan şehir.",
        "SAMSUN":          "Atatürk'ün Milli Mücadele'yi başlatmak için 1919'da ayak bastığı Karadeniz kenti.",
        "ERZURUM":         "Doğu Anadolu'da Kongre'nin toplandığı ve milli iradenin yeşerdiği tarihi şehir.",
        "SİVAS":           "Milli iradenin birleştiği ve Kongre kararlarının alındığı Anadolu şehri.",
        "İNÖNÜ":           "Kurtuluş Savaşı sırasında Yunan kuvvetlerinin iki kez geri püskürtüldüğü yer.",
        "SAKARYA":         "1921'de Türk ordusunun ağır bir meydan muharebesini kazandığı nehir ve savaş adı.",
        "LOZAN":           "1923'te Türkiye'nin sınırlarını ve egemenliğini uluslararası alanda onaylayan antlaşma.",
        "MUDANYA":         "Kurtuluş Savaşı sonrasında ateşkes hükümlerini belirleyen 1922 tarihli antlaşma.",
        "SEVR":            "1920'de Osmanlı'yı parçalayan, Türk milletinin reddederek geçersiz kıldığı antlaşma.",
        "DEVLETÇİLİK":     "Devletin ekonomiyi yönlendirdiği, Atatürk döneminin altı ilkesinden biri.",
        "MİLLİYETÇİLİK":   "Milli kimlik ve bağımsızlık duygusunu esas alan Cumhuriyet'in kurucu ilkelerinden biri.",
        "LAİKLİK":         "Din ile devlet işlerinin birbirinden ayrıldığı Türkiye Cumhuriyeti'nin temel ilkesi.",
        "İNKILAP":         "Toplumu kökten dönüştüren ve Cumhuriyet'i şekillendiren kapsamlı yenileşme hareketi.",
        "TANZİMAT":        "19. yüzyılda Osmanlı'nın Batı tarzı reformlarla modernleşmeye çalıştığı dönem.",
        "MEŞRUTİYET":      "Padişahın yetkilerini sınırlayan anayasal yönetim anlayışının Osmanlı'daki adı.",
        "PADİŞAH":         "Osmanlı Devleti'nde mutlak egemenliği elinde bulunduran hükümdar unvanı.",
        "VEZİR":           "Osmanlı'da padişaha yönetim konusunda yardımcı olan üst düzey devlet görevlisi.",
        "DİVAN":           "Osmanlı'da devlet işlerinin görüşüldüğü ve kararların alındığı yüksek kurul.",
        "TUĞRA":           "Osmanlı padişahlarının belgeler ve sikkelere bastırdığı özel el yazısı imza şekli.",
        "MİMARSİNAN":      "Süleymaniye ve Selimiye gibi yüzyılları aşan eserleri yapan Osmanlı baş mimarı.",
        "BARBAROS":        "Akdeniz'e Osmanlı adına hükmeden efsanevi Türk deniz komutanı.",
        "PİRİREİS":        "1513'te Amerika kıtasını da içeren dünya haritasını çizen Osmanlı denizcisi.",
        "EVLİYAÇELEBİ":    "17. yüzyılda yıllarca seyahat ederek coğrafi gözlemlerini yazan Osmanlı seyyahı.",
        "KATİPÇELEBİ":     "17. yüzyılda ansiklopedik eserler kaleme alan Osmanlı alim ve bibliyografı.",
        "FARABİ":          "Felsefe ve müziği harmanlayan, İslam dünyasının İkinci Öğretmen'i sayılan düşünür.",
        "İBNİSİNA":        "Tıp tarihinin en büyük eserlerinden birini yazan, el-Kanun'un yazarı olan bilgin.",
        "ULUĞBEY":         "Semerkant'ta rasathane kuran ve yıldız katalogları hazırlayan Türk astronomi bilgini.",
        "MEVLANA":         "Konya'da yaşayan, hoşgörü ve aşkı mesneviyle anlatan büyük mutasavvıf şair.",
        "YUNUS":           "Anadolu'yu sevgi ve insanlık şiirleriyle dolaşan halk ozanı ve derviş.",
        "HACIBEKTAŞ":      "Anadolu'da insan sevgisini ve toleransı yayan, Bektaşi tarikatının kurucusu.",
        "PİRİSULTAN":      "Haksızlığa isyan eden deyişleriyle tanınan Alevi-Bektaşi geleneğinin şair ozanı.",
        "ŞEYHEDEBALI":     "Osman Gazi'ye kız veren ve Osmanlı'nın manevi temellerini atan bilge şeyh.",
        "ALPARSLAN":       "Malazgirt'te Bizans'ı yenip Anadolu'nun kapılarını Türklere açan Selçuklu sultanı.",
        "TOPRAKAĞA":       "Toprağı olan ya da köy düzeninde arazi sahibi büyük Osmanlı çiftlik yöneticisi.",
        "AYASOFYA":        "Önce kilise, sonra cami olan ve günümüzde yeniden ibadete açılan İstanbul simgesi.",
        "TOPKAPI":         "Osmanlı padişahlarının yaklaşık dört yüz yıl boyunca ikamet ettiği İstanbul sarayı.",
        "DOLMABAHÇE":      "Boğaz kıyısında yükselen Batı tarzı büyük Osmanlı sarayı.",
        "KAPADOKYA":       "Peri bacaları ve yeraltı şehirleriyle ünlü, Anadolu'nun masalsı coğrafi bölgesi.",
        "ANITKABİR":       "Atatürk'ün ebedi istirahatgahı olan ve Ankara'daki ulusal anıt yapısı.",
        "GAZİ":            "Savaşta düşmanla çarpışıp zaferle dönen savaşçıya verilen onursal unvan.",
        "ŞEHİT":           "Vatan uğruna canını feda eden ve toplumda saygıyla anılan kahraman.",
        "MEHTERAN":        "Osmanlı ordusunun savaşa motivasyon kazandıran geleneksel askeri müzik takımı.",
        "YENİÇERİ":        "Osmanlı'nın seçkin piyade sınıfı; devşirme sistemiyle yetiştirilen düzenli askerler.",
        "KIRIM":           "Karadeniz'in kuzeyinde uzanan ve Türk tarihi ile kültürüyle derin bağları olan yarımada.",
    ]
}
