import Foundation

extension WordList {

    // MARK: - Words

    static let markalarWords: [WordEntry] = [
        WordEntry(word: "ADIDAS", category: "Markalar"),
        WordEntry(word: "AIRBNB", category: "Markalar"),
        WordEntry(word: "AMAZON", category: "Markalar"),
        WordEntry(word: "APPLE", category: "Markalar"),
        WordEntry(word: "ARMANI", category: "Markalar"),
        WordEntry(word: "ASTON MARTIN", category: "Markalar"),
        WordEntry(word: "BALMAIN", category: "Markalar"),
        WordEntry(word: "BENTLEY", category: "Markalar"),
        WordEntry(word: "BMW", category: "Markalar"),
        WordEntry(word: "BIRKENSTOCK", category: "Markalar"),
        WordEntry(word: "BURBERRY", category: "Markalar"),
        WordEntry(word: "BUGATTI", category: "Markalar"),
        WordEntry(word: "BURGER KING", category: "Markalar"),
        WordEntry(word: "CADILLAC", category: "Markalar"),
        WordEntry(word: "CALVIN KLEIN", category: "Markalar"),
        WordEntry(word: "CANON", category: "Markalar"),
        WordEntry(word: "CARTIER", category: "Markalar"),
        WordEntry(word: "CASIO", category: "Markalar"),
        WordEntry(word: "CHEVROLET", category: "Markalar"),
        WordEntry(word: "CHANEL", category: "Markalar"),
        WordEntry(word: "CHAMPION", category: "Markalar"),
        WordEntry(word: "CLINIQUE", category: "Markalar"),
        WordEntry(word: "COCA COLA", category: "Markalar"),
        WordEntry(word: "COLUMBIA", category: "Markalar"),
        WordEntry(word: "CONVERSE", category: "Markalar"),
        WordEntry(word: "DISNEY", category: "Markalar"),
        WordEntry(word: "DOLCE GABBANA", category: "Markalar"),
        WordEntry(word: "EMIRATES", category: "Markalar"),
        WordEntry(word: "FACEBOOK", category: "Markalar"),
        WordEntry(word: "FENDI", category: "Markalar"),
        WordEntry(word: "FERRARI", category: "Markalar"),
        WordEntry(word: "FERRERO", category: "Markalar"),
        WordEntry(word: "GARNIER", category: "Markalar"),
        WordEntry(word: "GIVENCHY", category: "Markalar"),
        WordEntry(word: "GOOGLE", category: "Markalar"),
        WordEntry(word: "GUCCI", category: "Markalar"),
        WordEntry(word: "HARIBO", category: "Markalar"),
        WordEntry(word: "HERMES", category: "Markalar"),
        WordEntry(word: "HILTON", category: "Markalar"),
        WordEntry(word: "HONDA", category: "Markalar"),
        WordEntry(word: "HUAWEI", category: "Markalar"),
        WordEntry(word: "HUGO BOSS", category: "Markalar"),
        WordEntry(word: "HYUNDAI", category: "Markalar"),
        WordEntry(word: "IKEA", category: "Markalar"),
        WordEntry(word: "INTEL", category: "Markalar"),
        WordEntry(word: "INSTAGRAM", category: "Markalar"),
        WordEntry(word: "JEEP", category: "Markalar"),
        WordEntry(word: "KENZO", category: "Markalar"),
        WordEntry(word: "LAND ROVER", category: "Markalar"),
        WordEntry(word: "LAMBORGHINI", category: "Markalar"),
        WordEntry(word: "LACOSTE", category: "Markalar"),
        WordEntry(word: "LANCOME", category: "Markalar"),
        WordEntry(word: "LEGO", category: "Markalar"),
        WordEntry(word: "LENOVO", category: "Markalar"),
        WordEntry(word: "LINKEDIN", category: "Markalar"),
        WordEntry(word: "LINDT", category: "Markalar"),
        WordEntry(word: "LOGITECH", category: "Markalar"),
        WordEntry(word: "LOREAL", category: "Markalar"),
        WordEntry(word: "LUFTHANSA", category: "Markalar"),
        WordEntry(word: "MAZDA", category: "Markalar"),
        WordEntry(word: "MARRIOTT", category: "Markalar"),
        WordEntry(word: "MASERATI", category: "Markalar"),
        WordEntry(word: "MAYBELLINE", category: "Markalar"),
        WordEntry(word: "MCDONALDS", category: "Markalar"),
        WordEntry(word: "MERCEDES", category: "Markalar"),
        WordEntry(word: "MICHAEL KORS", category: "Markalar"),
        WordEntry(word: "MICROSOFT", category: "Markalar"),
        WordEntry(word: "MILKA", category: "Markalar"),
        WordEntry(word: "MITSUBISHI", category: "Markalar"),
        WordEntry(word: "MONCLER", category: "Markalar"),
        WordEntry(word: "MONTBLANC", category: "Markalar"),
        WordEntry(word: "NESCAFE", category: "Markalar"),
        WordEntry(word: "NETFLIX", category: "Markalar"),
        WordEntry(word: "NEW BALANCE", category: "Markalar"),
        WordEntry(word: "NIKE", category: "Markalar"),
        WordEntry(word: "NISSAN", category: "Markalar"),
        WordEntry(word: "NIVEA", category: "Markalar"),
        WordEntry(word: "NOKIA", category: "Markalar"),
        WordEntry(word: "NUTELLA", category: "Markalar"),
        WordEntry(word: "OMEGA", category: "Markalar"),
        WordEntry(word: "PANASONIC", category: "Markalar"),
        WordEntry(word: "PANTENE", category: "Markalar"),
        WordEntry(word: "PEPSI", category: "Markalar"),
        WordEntry(word: "PHILIPS", category: "Markalar"),
        WordEntry(word: "PORSCHE", category: "Markalar"),
        WordEntry(word: "PRINGLES", category: "Markalar"),
        WordEntry(word: "PUMA", category: "Markalar"),
        WordEntry(word: "RAY BAN", category: "Markalar"),
        WordEntry(word: "REEBOK", category: "Markalar"),
        WordEntry(word: "RENAULT", category: "Markalar"),
        WordEntry(word: "ROLEX", category: "Markalar"),
        WordEntry(word: "ROLLS ROYCE", category: "Markalar"),
        WordEntry(word: "RYANAIR", category: "Markalar"),
        WordEntry(word: "SAMSUNG", category: "Markalar"),
        WordEntry(word: "SNAPCHAT", category: "Markalar"),
        WordEntry(word: "SNICKERS", category: "Markalar"),
        WordEntry(word: "SONY", category: "Markalar"),
        WordEntry(word: "SPOTIFY", category: "Markalar"),
        WordEntry(word: "STARBUCKS", category: "Markalar"),
        WordEntry(word: "SUBARU", category: "Markalar"),
        WordEntry(word: "SWAROVSKI", category: "Markalar"),
        WordEntry(word: "TESLA", category: "Markalar"),
        WordEntry(word: "TIKTOK", category: "Markalar"),
        WordEntry(word: "TISSOT", category: "Markalar"),
        WordEntry(word: "TOBLERONE", category: "Markalar"),
        WordEntry(word: "TOYOTA", category: "Markalar"),
        WordEntry(word: "TOSHIBA", category: "Markalar"),
        WordEntry(word: "VALENTINO", category: "Markalar"),
        WordEntry(word: "VERSACE", category: "Markalar"),
        WordEntry(word: "VOLKSWAGEN", category: "Markalar"),
        WordEntry(word: "VOLVO", category: "Markalar"),
        WordEntry(word: "WALMART", category: "Markalar"),
        WordEntry(word: "WHATSAPP", category: "Markalar"),
        WordEntry(word: "XIAOMI", category: "Markalar"),
        WordEntry(word: "YOUTUBE", category: "Markalar"),
        WordEntry(word: "ZARA", category: "Markalar"),
    ]

    // MARK: - Hints

    static let markalarHints: [String: String] = [:]
}
