import Foundation

extension WordList {

    // MARK: - Words

    static let tasitlarWords: [WordEntry] = [
        WordEntry(word: "AMBULANS", category: "Taşıtlar"),
        WordEntry(word: "ARABA", category: "Taşıtlar"),
        WordEntry(word: "BİSİKLET", category: "Taşıtlar"),
        WordEntry(word: "BULDOZER", category: "Taşıtlar"),
        WordEntry(word: "FERİBOT", category: "Taşıtlar"),
        WordEntry(word: "FORKLİFT", category: "Taşıtlar"),
        WordEntry(word: "GEMİ", category: "Taşıtlar"),
        WordEntry(word: "GONDOL", category: "Taşıtlar"),
        WordEntry(word: "HELİKOPTER", category: "Taşıtlar"),
        WordEntry(word: "İTFAİYE", category: "Taşıtlar"),
        WordEntry(word: "JET", category: "Taşıtlar"),
        WordEntry(word: "KAMYON", category: "Taşıtlar"),
        WordEntry(word: "KAMYONET", category: "Taşıtlar"),
        WordEntry(word: "KANO", category: "Taşıtlar"),
        WordEntry(word: "KAYIK", category: "Taşıtlar"),
        WordEntry(word: "METRO", category: "Taşıtlar"),
        WordEntry(word: "METROBÜS", category: "Taşıtlar"),
        WordEntry(word: "MİNİBÜS", category: "Taşıtlar"),
        WordEntry(word: "MOTOSİKLET", category: "Taşıtlar"),
        WordEntry(word: "OTOBÜS", category: "Taşıtlar"),
        WordEntry(word: "OTOMOBİL", category: "Taşıtlar"),
        WordEntry(word: "PARAŞÜT", category: "Taşıtlar"),
        WordEntry(word: "ROKET", category: "Taşıtlar"),
        WordEntry(word: "SCOOTER", category: "Taşıtlar"),
        WordEntry(word: "TAKSİ", category: "Taşıtlar"),
        WordEntry(word: "TANK", category: "Taşıtlar"),
        WordEntry(word: "TEKNE", category: "Taşıtlar"),
        WordEntry(word: "TIR", category: "Taşıtlar"),
        WordEntry(word: "TRAMVAY", category: "Taşıtlar"),
        WordEntry(word: "TREN", category: "Taşıtlar"),
        WordEntry(word: "TRAKTÖR", category: "Taşıtlar"),
        WordEntry(word: "UÇAK", category: "Taşıtlar"),
        WordEntry(word: "UZAY MEKİĞİ", category: "Taşıtlar"),
        WordEntry(word: "VİNÇ", category: "Taşıtlar"),
        WordEntry(word: "YAT", category: "Taşıtlar"),
        WordEntry(word: "ZEPLİN", category: "Taşıtlar"),
    ]

    // MARK: - Hints

    static let tasitlarHints: [String: String] = [
        "AMBULANS":     "Hastaları acil olarak hastaneye taşıyan özel araç.",
        "FERİBOT":      "Araç ve yolcuları denizde ya da nehirde taşıyan yüzen araç.",
        "GONDOL":       "Venedik kanallarında kürekle yönlendirilen geleneksel tekne.",
        "HELİKOPTER":   "Kanatçık yerine dönen rotor bıçaklarıyla uçan hava aracı.",
        "HOVERCRAFT":   "Hava yastığı üzerinde hem karada hem suda gidebilen araç.",
        "KATAMARAN":    "İki gövdeli, deniz üzerinde hızlı gidebilen tekne türü.",
        "KAYIK":        "Kürekle ya da yelkenle yönlendirilen küçük deniz aracı.",
        "LOKOMOTİF":    "Tren vagonlarını çeken güçlü motor bölümü.",
        "METRO":        "Şehir içinde yeraltı tünellerinde işleyen hızlı raylı ulaşım sistemi.",
        "MİNİBÜS":      "Otobüs ve araba arasında boyutta olan toplu taşıma aracı.",
        "MOTOSİKLET":   "İki tekerlekli, motorlu bireysel taşıt.",
        "PARAMOTOR":    "Sırt motoru ve kanat yardımıyla uçulan küçük hava aracı.",
        "RİKŞA":        "Bisiklet ya da motosiklet çekimli, Asya'da yaygın küçük taşıt.",
        "SÜRAT TEKNESİ":"Güçlü motoruyla çok hızlı giden küçük deniz aracı.",
        "TAKSI":        "Ücret karşılığı yolcu taşıyan özel araç.",
        "TRAMVAY":      "Şehir yollarında ray üzerinde çalışan elektrikli toplu taşıma.",
        "UÇAK":         "Motor gücüyle havalanıp havada seyreden motorlu taşıt.",
        "VAPUR":        "Buharlı motor gücüyle denizde yolcu ve araç taşıyan gemi.",
        "YAT":          "Lüks tekne olarak bilinen, hem yelken hem motorlu büyük deniz aracı.",
        "ZEPLİN":       "Helyum dolu büyük balonlu, yavaş hareket eden hava aracı.",
        "ARABA":        "Dört tekerlekli, motorlu, kişisel ulaşımda en yaygın taşıt.",
        "BİSİKLET":     "Pedallarla insan gücüyle hareket eden iki tekerlekli araç.",
        "BULDOZER":     "Toprağı iterek düzleyen, ağır iş makineleri arasında en çok tanınan.",
        "FORKLİFT":     "Ön çatallı kollarıyla ağır paletleri kaldırıp taşıyan fabrika aracı.",
        "GEMİ":         "Denizde yük veya yolcu taşıyan büyük su taşıtı.",
        "İTFAİYE":      "Yangına müdahale için kullanılan, büyük su tankı ve merdivenli araç.",
        "JET":          "Jet motoru gücüyle yüksek hızda uçan askeri ya da özel uçak.",
        "KAMYON":       "Büyük yük taşımak için tasarlanmış ağır motorlu araç.",
        "KAMYONET":     "Kamyondan küçük, hem yük hem yolcu taşıyabilen hafif ticari araç.",
        "KANO":         "Kürekle çekilen, sivri uçlu ve hafif kano.",
        "METROBÜS":     "Özel şeridinde çift vagonlu işleyen hızlı kent otobüsü.",
        "OTOBÜS":       "Çok sayıda yolcuyu aynı anda taşıyan büyük motorlu araç.",
        "OTOMOBİL":     "Ailelik dört tekerlekli motorlu kara taşıtı.",
        "PARAŞÜT":      "Havadan atlarken yavaş iniş sağlayan kubbe şekilli örtü sistemi.",
        "ROKET":        "Yakıt yakarak yüksek hızda uzaya ya da hedefe fırlatılan taşıt.",
        "SCOOTER":      "Küçük motorlu, ayaklık platformlu kentsel taşıt.",
        "TAKSİ":        "Ücret karşılığı yolcu taşıyan, genellikle sarı renkli özel araç.",
        "TANK":         "Zırhlı, paletli, top taşıyan askeri savaş aracı.",
        "TEKNE":        "Su üzerinde yüzen, motorlu ya da kürekli küçük deniz taşıtı.",
        "TIR":          "Uzun mesafe yük taşımacılığında kullanılan çekici ve dorse bütünü.",
        "TREN":         "Raylarda hareket eden, çok vagonlu kara taşıtı.",
        "TRAKTÖR":      "Tarla sürme ve tarımsal işlerde kullanılan güçlü motorlu araç.",
        "UZAY MEKİĞİ":  "Uzayda görev yapıp tekrar Dünya'ya dönen yeniden kullanılabilir uzay aracı.",
        "VİNÇ":         "Ağır yükleri kaldırmak ve taşımak için kullanılan mekanik araç.",
    ]
}
