import Foundation

extension WordList {

    // MARK: - Words

    static let hayvanlarWords: [WordEntry] = [
        WordEntry(word: "AHTAPOT", category: "Hayvanlar"),
        WordEntry(word: "AKBABA", category: "Hayvanlar"),
        WordEntry(word: "AKREP", category: "Hayvanlar"),
        WordEntry(word: "ALBATROS", category: "Hayvanlar"),
        WordEntry(word: "ANTİLOP", category: "Hayvanlar"),
        WordEntry(word: "ARI", category: "Hayvanlar"),
        WordEntry(word: "ASLAN", category: "Hayvanlar"),
        WordEntry(word: "AT", category: "Hayvanlar"),
        WordEntry(word: "AYI", category: "Hayvanlar"),
        WordEntry(word: "BALİNA", category: "Hayvanlar"),
        WordEntry(word: "BALIK", category: "Hayvanlar"),
        WordEntry(word: "BAYKUŞ", category: "Hayvanlar"),
        WordEntry(word: "BONOBO", category: "Hayvanlar"),
        WordEntry(word: "BÜLBÜL", category: "Hayvanlar"),
        WordEntry(word: "ÇAKAL", category: "Hayvanlar"),
        WordEntry(word: "ÇEKİRGE", category: "Hayvanlar"),
        WordEntry(word: "ÇITA", category: "Hayvanlar"),
        WordEntry(word: "ÇİPURA", category: "Hayvanlar"),
        WordEntry(word: "DEVE", category: "Hayvanlar"),
        WordEntry(word: "DOMUZ", category: "Hayvanlar"),
        WordEntry(word: "EŞEK", category: "Hayvanlar"),
        WordEntry(word: "FİL", category: "Hayvanlar"),
        WordEntry(word: "FLAMİNGO", category: "Hayvanlar"),
        WordEntry(word: "GERGEDAN", category: "Hayvanlar"),
        WordEntry(word: "GORİL", category: "Hayvanlar"),
        WordEntry(word: "GUGUK", category: "Hayvanlar"),
        WordEntry(word: "HAMSİ", category: "Hayvanlar"),
        WordEntry(word: "HİPOPOTAM", category: "Hayvanlar"),
        WordEntry(word: "İGUANA", category: "Hayvanlar"),
        WordEntry(word: "JAGUAR", category: "Hayvanlar"),
        WordEntry(word: "KANGURU", category: "Hayvanlar"),
        WordEntry(word: "KAPLUMBAĞA", category: "Hayvanlar"),
        WordEntry(word: "KAPLAN", category: "Hayvanlar"),
        WordEntry(word: "KARİDES", category: "Hayvanlar"),
        WordEntry(word: "KARGA", category: "Hayvanlar"),
        WordEntry(word: "KARTAL", category: "Hayvanlar"),
        WordEntry(word: "KEDİ",   category: "Hayvanlar"),
        WordEntry(word: "KEÇİ",   category: "Hayvanlar"),
        WordEntry(word: "KOYUN",  category: "Hayvanlar"),
        WordEntry(word: "KEKLİK", category: "Hayvanlar"),
        WordEntry(word: "KELEBEK", category: "Hayvanlar"),
        WordEntry(word: "KİRPİ", category: "Hayvanlar"),
        WordEntry(word: "KOALA", category: "Hayvanlar"),
        WordEntry(word: "KÖPEK", category: "Hayvanlar"),
        WordEntry(word: "KUNDUZ", category: "Hayvanlar"),
        WordEntry(word: "KURBAĞA", category: "Hayvanlar"),
        WordEntry(word: "KURT", category: "Hayvanlar"),
        WordEntry(word: "KUŞ", category: "Hayvanlar"),
        WordEntry(word: "LEOPAR", category: "Hayvanlar"),
        WordEntry(word: "LEVREK", category: "Hayvanlar"),
        WordEntry(word: "LEYLEK", category: "Hayvanlar"),
        WordEntry(word: "MARTI", category: "Hayvanlar"),
        WordEntry(word: "MAYMUN", category: "Hayvanlar"),
        WordEntry(word: "MERSİN BALIĞI", category: "Hayvanlar"),
        WordEntry(word: "OKAPI",     category: "Hayvanlar"),
        WordEntry(word: "ORANGUTAN", category: "Hayvanlar"),
        WordEntry(word: "ÖRDEK",     category: "Hayvanlar"),
        WordEntry(word: "PANDA", category: "Hayvanlar"),
        WordEntry(word: "PANTER", category: "Hayvanlar"),
        WordEntry(word: "PAPAĞAN", category: "Hayvanlar"),
        WordEntry(word: "PELİKAN", category: "Hayvanlar"),
        WordEntry(word: "PENGUEN", category: "Hayvanlar"),
        WordEntry(word: "PORSUK", category: "Hayvanlar"),
        WordEntry(word: "SANSAR", category: "Hayvanlar"),
        WordEntry(word: "SINCAP", category: "Hayvanlar"),
        WordEntry(word: "SÜLÜN", category: "Hayvanlar"),
        WordEntry(word: "ŞAHİN", category: "Hayvanlar"),
        WordEntry(word: "ŞEMPANZE", category: "Hayvanlar"),
        WordEntry(word: "TAPİR", category: "Hayvanlar"),
        WordEntry(word: "TAVŞAN", category: "Hayvanlar"),
        WordEntry(word: "TİLKİ", category: "Hayvanlar"),
        WordEntry(word: "TİMSAH", category: "Hayvanlar"),
        WordEntry(word: "VARAN", category: "Hayvanlar"),
        WordEntry(word: "VAŞAK", category: "Hayvanlar"),
        WordEntry(word: "YENGEÇ", category: "Hayvanlar"),
        WordEntry(word: "YILAN", category: "Hayvanlar"),
        WordEntry(word: "YUNUS", category: "Hayvanlar"),
        WordEntry(word: "ZEBRA", category: "Hayvanlar"),
        WordEntry(word: "ZÜRAFA", category: "Hayvanlar"),
    ]

    // MARK: - Hints

    static let hayvanlarHints: [String: String] = [
        "AHTAPOT":      "Denizin derinliklerinde yaşar, sekiz kolu vardır.",
        "AKBABA":       "Ölü hayvanlarla beslenen, kafası tüysüz bir yırtıcı kuş.",
        "AKREP":        "Kuyruğunda zehir iğnesi olan, çölde yaşayan eklembackli hayvan.",
        "ALBATROS":     "Okyanusun üzerinde saatlerce süzülebilen dev bir deniz kuşu.",
        "ANTİLOP":      "Afrika savanalarında sürüler halinde yaşayan, hızlı koşan otçul.",
        "ARI":          "Çiçeklerden bal toplayan, sarı-siyah çizgili zararlı böcek.",
        "ASLAN":        "Savananın kralı olarak bilinir, erkeklerin yelesi vardır.",
        "AT":           "İnsanların bindiği, hızlı koşan, dört ayaklı hayvan.",
        "AYI":          "Ormanda yaşayan, balı çok seven iri yapılı hayvan.",
        "BALİNA":       "Dünyanın en büyük memelisi olabilir, denizde yaşar.",
        "BALIK":        "Suda yaşayan, solungaçla nefes alan hayvan.",
        "BAYKUŞ":       "Geceleri avlanan, başını 270 derece döndürebilen kuş.",
        "BONOBO":       "İnsanlara en yakın primatlardan biri, Kongo ormanlarında yaşar.",
        "BÜLBÜL":       "Güzel ötüşüyle ünlü, geceleri de şakıyan küçük kuş.",
        "ÇAKAL":        "Hem avlanan hem de leş yiyen, çöl ve ormanlarda yaşayan köpekgil.",
        "ÇEKİRGE":      "Sürüler halinde tarlaları mahvedebilen, atlayan böcek.",
        "ÇITA":         "Karada en hızlı koşan hayvan, saatte 120 km'ye ulaşabilir.",
        "ÇİPURA":       "Akdeniz ve Ege'de yetişen, beyaz etli, lezzetli balık türü.",
        "DEVE":         "Çölde haftalarca susuz kalabilen, hörgüçlü hayvan.",
        "DOMUZ":        "Çiftliklerde yetiştirilen, pembe tenli, kıvırcık kuyruklu evcil hayvan.",
        "EŞEK":         "Yük taşımada kullanılan, inatçılığıyla bilinen evcil hayvan.",
        "FİL":          "Karada yaşayan en büyük memeli, uzun bir hortumu var.",
        "FLAMİNGO":     "Uzun bacakları ve pembe rengiyle dikkat çeken, tek ayak üzerinde duran kuş.",
        "GERGEDAN":     "Burnunda boynuz taşıyan, kalın derili büyük memeli.",
        "GORİL":        "İnsanlarla DNA'sının %98'ini paylaşan büyük primat.",
        "GUGUK":        "Yuvaya yumurta bırakıp başkasına yuvayı teslim eden, sesli ötüşlü kuş.",
        "HAMSİ":        "Karadeniz'in sembolü olan, küçük ama lezzetli balık.",
        "HİPOPOTAM":    "Nilüfer çiçekleri arasında dinlenen, yarı suda yarı karada yaşayan dev memeli.",
        "İGUANA":       "Tropikal bölgelerde yaşayan, büyük pullu, yeşil renkli kertenkele.",
        "JAGUAR":       "Amerika'nın en güçlü yırtıcı kedisi, benekli tüyleri var.",
        "KANGURU":      "Avustralya'ya özgü, kesesinde yavru taşıyan memeli.",
        "KAPLUMBAĞA":   "Çok yavaş hareket eden, sert kabuğuyla korunan sürüngen.",
        "KAPLAN":       "Çizgili deseni ve güçlü yapısıyla Asya'nın en büyük yırtıcı kedisi.",
        "KARİDES":      "Denizde yaşayan, küçük, kıvrık vücutlu deniz ürünü.",
        "KARGA":        "Akıllı ve meraklı, siyah renkli, şehirlerde de yaşayan kuş.",
        "KARTAL":       "Gökyüzünün efendisi, keskin görüşüyle ünlü büyük yırtıcı kuş.",
        "KEDİ":         "Miyavlayan, tırmalayan, evcil küçük yırtıcı hayvan.",
        "KEÇİ":         "Dağlık arazide rahatça gezen, süt veren çiftlik hayvanı.",
        "KOYUN":        "Yünü kıyafet yapımında kullanılan, evcil sürü hayvanı.",
        "KEKLİK":       "Yerde yuvası olan, gagası kırmızı tüylü av kuşu.",
        "KELEBEK":      "Çiçekten çiçeğe uçan, renkli kanatlarıyla güzellik simgesi.",
        "KİRPİ":        "Tüm vücudu dikenlerle kaplı, küçük memelinin korunma yöntemi.",
        "KOALA":        "Avustralya'da ökaliptüs yaprağı yiyen, ağaçta yaşayan sevimli hayvan.",
        "KÖPEK":        "İnsanların en sadık hayvan dostu.",
        "KUNDUZ":       "Ağaçları kemirerek nehirde baraj inşa eden, yassı kuyruklu memeli.",
        "KURBAĞA":      "Hem suda hem karada yaşayan, sıçrayan ve vıraklayan amfibi.",
        "KURT":         "Sürüler halinde avlanan, köpeğin vahşi atası.",
        "KUŞ":          "Tüyleri ve kanatlarıyla uçabilen omurgalı hayvan.",
        "LEOPAR":       "Benekli, yalnız yaşayan büyük kedi; avını ağaca taşır.",
        "LEVREK":       "Türkiye kıyılarında çok avlanan, beyaz etli deniz balığı.",
        "LEYLEK":       "Uzun bacaklı, bacaca yapan göçmen kuş; bebeği getirdiği söylenir.",
        "MARTI":        "Deniz kenarında sık görülen, cıvıltılı beyaz bir kuş.",
        "MAYMUN":       "Ağaçtan ağaca zıplayabilen, insan davranışları taklit eden primat.",
        "MERSİN BALIĞI":"Havyar kaynağı olan, antik sularda yaşayan büyük balık.",
        "OKAPI":        "Zürafa akrabası olduğu halde boynu kısa, bacakları çizgili orman hayvanı.",
        "ORANGUTAN":    "Ağaçlarda yaşayan, kızıl tüylü büyük primat.",
        "ÖRDEK":        "Suda yüzebilen, vac vac sesi çıkaran evcil ya da vahşi kuş.",
        "PANDA":        "Çin'e özgü, bambu yiyen, siyah-beyaz renkli sevimli ayı.",
        "PANTER":       "Siyah renkli, yalnız avlanan, güçlü büyük kedi türü.",
        "PAPAĞAN":      "İnsan sesini taklit edebilen, renkli tüylü, zeki kuş.",
        "PELİKAN":      "Geniş gerdanlık torbası olan, balık avlayan büyük su kuşu.",
        "PENGUEN":      "Kanatları olduğu halde uçamayan, yüzmeyi seven kuş.",
        "PORSUK":       "Geceleri aktif olan, yer kazan, kısa bacaklı memeli.",
        "SANSAR":       "İnce uzun vücutlu, tavuk kümeslerine giren yırtıcı memeli.",
        "SINCAP":       "Uzun tüylü kuyruğuyla ağaçlarda zıplayan, fındık yiyen kemirgen.",
        "SÜLÜN":        "Erkek bireyinin renkli tüyleriyle göz kamaştırdığı av kuşu.",
        "ŞAHİN":        "Hızlı dalışıyla ünlü, eğitilip ava götürülen yırtıcı kuş.",
        "ŞEMPANZE":     "İnsanlarla en yakın akraba olan primat türü.",
        "TAPİR":        "Kısa hortumsu burnu olan, Güney Amerika ve Güneydoğu Asya'da yaşayan memeli.",
        "TAVŞAN":       "Uzun kulakları ve kısa kuyruğuyla hızlı koşan, otçul memeli.",
        "TİLKİ":        "Kurnazlığıyla ünlü, keskin burunlu, kızıl tüylü et yiyen memeli.",
        "TİMSAH":       "Yüz milyonlarca yıldır değişmeyen, devasa sürüngen.",
        "VARAN":        "Büyük kertenkele türü, Komodo ejderi de bu aileye girer.",
        "VAŞAK":        "Püsküllü kulakları olan, Avrupa ve Asya ormanlarında yaşayan yırtıcı kedi.",
        "YENGEÇ":       "Yandan yürüyen, sert kabuklu, denizde yaşayan eklembackli.",
        "YILAN":        "Bacaksız, zehirli ya da sarma yoluyla avlayan sürüngen.",
        "YUNUS":        "Zeki ve sosyal deniz memelisi, insanlara yakın ilgi gösterir.",
        "ZEBRA":        "Afrika savanalarında yaşayan, siyah-beyaz çizgili at akrabası.",
        "ZÜRAFA":       "Dünyanın en uzun boyunlu hayvanı, ağaçların tepesinden yaprak yer.",
    ]
}
