import Foundation

extension WordList {

    // MARK: - Words

    static let ulkelerWords: [WordEntry] = [
        WordEntry(word: "AFGANİSTAN", category: "Ülkeler"),
        WordEntry(word: "ALMANYA", category: "Ülkeler"),
        WordEntry(word: "AMERİKA", category: "Ülkeler"),
        WordEntry(word: "ANDORRA", category: "Ülkeler"),
        WordEntry(word: "ANGOLA", category: "Ülkeler"),
        WordEntry(word: "ARJANTİN", category: "Ülkeler"),
        WordEntry(word: "ARNAVUTLUK", category: "Ülkeler"),
        WordEntry(word: "AVUSTRALYA", category: "Ülkeler"),
        WordEntry(word: "AVUSTURYA", category: "Ülkeler"),
        WordEntry(word: "AZERBAYCAN", category: "Ülkeler"),
        WordEntry(word: "BAHREYN", category: "Ülkeler"),
        WordEntry(word: "BANGLADEŞ", category: "Ülkeler"),
        WordEntry(word: "BELÇİKA", category: "Ülkeler"),
        WordEntry(word: "BENİN", category: "Ülkeler"),
        WordEntry(word: "BELARUS", category: "Ülkeler"),
        WordEntry(word: "BOLİVYA", category: "Ülkeler"),
        WordEntry(word: "BOSNA HERSEK", category: "Ülkeler"),
        WordEntry(word: "BREZİLYA", category: "Ülkeler"),
        WordEntry(word: "BULGARİSTAN", category: "Ülkeler"),
        WordEntry(word: "BURKİNA FASO", category: "Ülkeler"),
        WordEntry(word: "CEZAYİR", category: "Ülkeler"),
        WordEntry(word: "ÇAD", category: "Ülkeler"),
        WordEntry(word: "ÇEK CUMHURİYETİ", category: "Ülkeler"),
        WordEntry(word: "ÇİN", category: "Ülkeler"),
        WordEntry(word: "DANİMARKA", category: "Ülkeler"),
        WordEntry(word: "DOMİNİK CUMHURİYETİ", category: "Ülkeler"),
        WordEntry(word: "EKVADOR", category: "Ülkeler"),
        WordEntry(word: "EL SALVADOR", category: "Ülkeler"),
        WordEntry(word: "ENDONEZYA", category: "Ülkeler"),
        WordEntry(word: "ERMENİSTAN", category: "Ülkeler"),
        WordEntry(word: "ESTONYA", category: "Ülkeler"),
        WordEntry(word: "ETİYOPYA", category: "Ülkeler"),
        WordEntry(word: "FAS", category: "Ülkeler"),
        WordEntry(word: "FİJİ", category: "Ülkeler"),
        WordEntry(word: "FİLDİŞİ SAHİLİ", category: "Ülkeler"),
        WordEntry(word: "FİLİPİNLER", category: "Ülkeler"),
        WordEntry(word: "FİLİSTİN", category: "Ülkeler"),
        WordEntry(word: "FİNLANDİYA", category: "Ülkeler"),
        WordEntry(word: "FRANSA", category: "Ülkeler"),
        WordEntry(word: "GABON", category: "Ülkeler"),
        WordEntry(word: "GAMBİYA", category: "Ülkeler"),
        WordEntry(word: "GANA", category: "Ülkeler"),
        WordEntry(word: "GİNE", category: "Ülkeler"),
        WordEntry(word: "GUYANA", category: "Ülkeler"),
        WordEntry(word: "GUATEMALA", category: "Ülkeler"),
        WordEntry(word: "GÜNEY AFRİKA", category: "Ülkeler"),
        WordEntry(word: "GÜNEY KORE", category: "Ülkeler"),
        WordEntry(word: "GÜRCİSTAN", category: "Ülkeler"),
        WordEntry(word: "HIRVATİSTAN", category: "Ülkeler"),
        WordEntry(word: "HİNDİSTAN", category: "Ülkeler"),
        WordEntry(word: "HOLLANDA", category: "Ülkeler"),
        WordEntry(word: "HONDURAS", category: "Ülkeler"),
        WordEntry(word: "IRAK", category: "Ülkeler"),
        WordEntry(word: "İRAN", category: "Ülkeler"),
        WordEntry(word: "İRLANDA", category: "Ülkeler"),
        WordEntry(word: "İNGİLTERE", category: "Ülkeler"),
        WordEntry(word: "İSPANYA", category: "Ülkeler"),
        WordEntry(word: "İSRAİL", category: "Ülkeler"),
        WordEntry(word: "İSVEÇ", category: "Ülkeler"),
        WordEntry(word: "İSVİÇRE", category: "Ülkeler"),
        WordEntry(word: "İTALYA", category: "Ülkeler"),
        WordEntry(word: "İZLANDA", category: "Ülkeler"),
        WordEntry(word: "JAMAİKA", category: "Ülkeler"),
        WordEntry(word: "JAPONYA", category: "Ülkeler"),
        WordEntry(word: "KAMBOÇYA", category: "Ülkeler"),
        WordEntry(word: "KAMERUN", category: "Ülkeler"),
        WordEntry(word: "KANADA", category: "Ülkeler"),
        WordEntry(word: "KARADAĞ", category: "Ülkeler"),
        WordEntry(word: "KATAR", category: "Ülkeler"),
        WordEntry(word: "KAZAKİSTAN", category: "Ülkeler"),
        WordEntry(word: "KENYA", category: "Ülkeler"),
        WordEntry(word: "KIBRIS", category: "Ülkeler"),
        WordEntry(word: "KIRGIZİSTAN", category: "Ülkeler"),
        WordEntry(word: "KOLOMBİYA", category: "Ülkeler"),
        WordEntry(word: "KONGO", category: "Ülkeler"),
        WordEntry(word: "KOSOVA", category: "Ülkeler"),
        WordEntry(word: "KOSTA RİKA", category: "Ülkeler"),
        WordEntry(word: "KUVEYT", category: "Ülkeler"),
        WordEntry(word: "KUZEY KORE", category: "Ülkeler"),
        WordEntry(word: "KÜBA", category: "Ülkeler"),
        WordEntry(word: "LAOS", category: "Ülkeler"),
        WordEntry(word: "LETONYA", category: "Ülkeler"),
        WordEntry(word: "LİBYA", category: "Ülkeler"),
        WordEntry(word: "LİHTENŞTAYN", category: "Ülkeler"),
        WordEntry(word: "LİTVANYA", category: "Ülkeler"),
        WordEntry(word: "LÜBNAN", category: "Ülkeler"),
        WordEntry(word: "LÜKSEMBURG", category: "Ülkeler"),
        WordEntry(word: "MACARİSTAN", category: "Ülkeler"),
        WordEntry(word: "MAKEDONYA", category: "Ülkeler"),
        WordEntry(word: "MALDİVLER", category: "Ülkeler"),
        WordEntry(word: "MALEZYA", category: "Ülkeler"),
        WordEntry(word: "MALİ", category: "Ülkeler"),
        WordEntry(word: "MALTA", category: "Ülkeler"),
        WordEntry(word: "MEKSİKA", category: "Ülkeler"),
        WordEntry(word: "MISIR", category: "Ülkeler"),
        WordEntry(word: "MOĞOLİSTAN", category: "Ülkeler"),
        WordEntry(word: "MOLDOVA", category: "Ülkeler"),
        WordEntry(word: "MONAKO", category: "Ülkeler"),
        WordEntry(word: "MORİTANYA", category: "Ülkeler"),
        WordEntry(word: "MOZAMBİK", category: "Ülkeler"),
        WordEntry(word: "MYANMAR", category: "Ülkeler"),
        WordEntry(word: "NAMİBYA", category: "Ülkeler"),
        WordEntry(word: "NEPAL", category: "Ülkeler"),
        WordEntry(word: "NİJER", category: "Ülkeler"),
        WordEntry(word: "NİJERYA", category: "Ülkeler"),
        WordEntry(word: "NORVEÇ", category: "Ülkeler"),
        WordEntry(word: "ÖZBEKİSTAN", category: "Ülkeler"),
        WordEntry(word: "PAKİSTAN", category: "Ülkeler"),
        WordEntry(word: "PANAMA", category: "Ülkeler"),
        WordEntry(word: "PARAGUAY", category: "Ülkeler"),
        WordEntry(word: "PERU", category: "Ülkeler"),
        WordEntry(word: "POLONYA", category: "Ülkeler"),
        WordEntry(word: "PORTEKİZ", category: "Ülkeler"),
        WordEntry(word: "ROMANYA", category: "Ülkeler"),
        WordEntry(word: "RUSYA", category: "Ülkeler"),
        WordEntry(word: "SENEGAL", category: "Ülkeler"),
        WordEntry(word: "SEYŞELLER", category: "Ülkeler"),
        WordEntry(word: "SIRBİSTAN", category: "Ülkeler"),
        WordEntry(word: "SİNGAPUR", category: "Ülkeler"),
        WordEntry(word: "SLOVAKYA", category: "Ülkeler"),
        WordEntry(word: "SLOVENYA", category: "Ülkeler"),
        WordEntry(word: "SOMALİ", category: "Ülkeler"),
        WordEntry(word: "SRİ LANKA", category: "Ülkeler"),
        WordEntry(word: "SUDAN", category: "Ülkeler"),
        WordEntry(word: "SURİYE", category: "Ülkeler"),
        WordEntry(word: "SUUDİ ARABİSTAN", category: "Ülkeler"),
        WordEntry(word: "ŞİLİ", category: "Ülkeler"),
        WordEntry(word: "TACİKİSTAN", category: "Ülkeler"),
        WordEntry(word: "TANZANYA", category: "Ülkeler"),
        WordEntry(word: "TAYLAND", category: "Ülkeler"),
        WordEntry(word: "TAYVAN", category: "Ülkeler"),
        WordEntry(word: "TOGO", category: "Ülkeler"),
        WordEntry(word: "TRİNİDAD VE TOBAGO", category: "Ülkeler"),
        WordEntry(word: "TUNUS", category: "Ülkeler"),
        WordEntry(word: "TÜRKİYE", category: "Ülkeler"),
        WordEntry(word: "TÜRKMENİSTAN", category: "Ülkeler"),
        WordEntry(word: "UGANDA", category: "Ülkeler"),
        WordEntry(word: "UKRAYNA", category: "Ülkeler"),
        WordEntry(word: "UMMAN", category: "Ülkeler"),
        WordEntry(word: "URUGUAY", category: "Ülkeler"),
        WordEntry(word: "ÜRDÜN", category: "Ülkeler"),
        WordEntry(word: "VENEZUELA", category: "Ülkeler"),
        WordEntry(word: "VİETNAM", category: "Ülkeler"),
        WordEntry(word: "YEMEN", category: "Ülkeler"),
        WordEntry(word: "YENİ ZELANDA", category: "Ülkeler"),
        WordEntry(word: "YUNANİSTAN", category: "Ülkeler"),
        WordEntry(word: "ZAMBİYA", category: "Ülkeler"),
        WordEntry(word: "ZİMBABVE", category: "Ülkeler"),
    ]

    // MARK: - Hints

    static let ulkelerHints: [String: String] = [
        "AFGANİSTAN":           "Başkenti Kabil olan, Hindu Kuş dağlarıyla çevrili Orta Asya ülkesi.",
        "ALMANYA":              "Avrupa'nın en kalabalık ülkesi olup başkenti Berlin'dir.",
        "AMERİKA":              "50 eyaletten oluşan, başkenti Washington D.C. olan kuzey yarımküre devi.",
        "ANDORRA":              "Fransa ile İspanya arasında sıkışmış, dünyanın en küçük ülkelerinden biri.",
        "ANGOLA":               "Afrika'nın güneybatısında yer alan, başkenti Luanda olan petrol zengini ülke.",
        "ARJANTİN":             "Güney Amerika'nın en büyük ikinci ülkesi; tango dansı ve futboluyıyla ünlüdür.",
        "ARNAVUTLUK":           "Balkanlar'da Adriyatik kıyısında yer alan, başkenti Tiran olan ülke.",
        "AVUSTRALYA":           "Hem kıta hem ülke olan, Kanguru ve Sidney Opera Evi ile ünlü ülke.",
        "AVUSTURYA":            "Alpler'in kalbinde yer alan, başkenti Viyana olan Orta Avrupa ülkesi.",
        "AZERBAYCAN":           "Hazar Denizi kıyısında, başkenti Bakü olan Kafkasya ülkesi.",
        "BAHREYN":              "Körfez'deki küçük ada ülkesi; başkenti Manama'dır.",
        "BANGLADEŞ":            "Güney Asya'da yoğun nüfusuyla bilinen, başkenti Dakka olan ülke.",
        "BELÇİKA":              "Avrupa Birliği'nin merkezi Brüksel'e ev sahipliği yapan Batı Avrupa ülkesi.",
        "BENİN":                "Batı Afrika'da yer alan, başkenti Porto-Novo olan ülke.",
        "BELARUS":              "Doğu Avrupa'da Rusya ile sınır komşusu olan, başkenti Minsk olan ülke.",
        "BOLİVYA":              "Denize çıkışı olmayan, La Paz ve Sucre olmak üzere iki başkenti bulunan Güney Amerika ülkesi.",
        "BOSNA HERSEK":         "Balkanlar'da Saraybosna başkentli, çok etnikli Güneydoğu Avrupa ülkesi.",
        "BREZİLYA":             "Güney Amerika'nın en büyük ülkesi; Amazon ormanları ve karnavalıyla ünlüdür.",
        "BULGARİSTAN":          "Karadeniz kıyısında, başkenti Sofya olan Balkan ülkesi.",
        "BURKİNA FASO":         "Batı Afrika'da kara ile çevrili, başkenti Ouagadougou olan ülke.",
        "CEZAYİR":              "Afrika'nın en büyük ülkesi; Sahra Çölü'nün büyük bölümünü kapsar.",
        "ÇAD":                  "Orta Afrika'da çöl ve step coğrafyasıyla kaplı, başkenti N'Djamena olan ülke.",
        "ÇEK CUMHURİYETİ":      "Orta Avrupa'da tarihi Prag başkentli, çevresi kara ile çevrili ülke.",
        "ÇİN":                  "Dünyanın en kalabalık ülkesi; Büyük Çin Seddi ve ejder sembolüyle tanınır.",
        "DANİMARKA":            "İskandinavya'nın güneybatısında, başkenti Kopenhag olan monarşi.",
        "DOMİNİK CUMHURİYETİ":  "Karayipler'de Hispaniola adasını Haiti ile paylaşan, başkenti Santo Domingo olan ülke.",
        "EKVADOR":              "Güney Amerika'da Ekvator hattının üzerinden geçen, Galapagos Adaları'na ev sahipliği yapan ülke.",
        "EL SALVADOR":          "Orta Amerika'nın en küçük ve en kalabalık ülkesi; başkenti San Salvador'dur.",
        "ENDONEZYA":            "17.000'den fazla adadan oluşan, dünyanın en büyük takımada devleti.",
        "ERMENİSTAN":           "Kafkasya'da Erivan başkentli, Ararat Dağı'nı simgeleyen ülke.",
        "ESTONYA":              "Baltık Denizi kıyısında, başkenti Tallinn olan küçük Kuzey Avrupa ülkesi.",
        "ETİYOPYA":             "Afrika'nın en eski devletlerinden biri; kahvenin anavatanı olarak bilinir.",
        "FAS":                  "Kuzey Afrika'da Marakeş ve Fes gibi tarihi medinalara sahip ülke.",
        "FİJİ":                 "Güney Pasifik'te 330'dan fazla adadan oluşan tropik ada devleti.",
        "FİLDİŞİ SAHİLİ":       "Batı Afrika'da kakao üretimiyle öne çıkan, başkenti Yamoussoukro olan ülke.",
        "FİLİPİNLER":           "Güneydoğu Asya'da 7.000'i aşkın adadan oluşan, başkenti Manila olan takımada ülkesi.",
        "FİLİSTİN":             "Orta Doğu'da Gazze ve Batı Şeria'yı kapsayan, Kudüs'ü paylaşma talebiyle bilinen bölge.",
        "FİNLANDİYA":           "Binlerce göl ve ormanla kaplı, başkenti Helsinki olan Kuzey Avrupa ülkesi.",
        "FRANSA":               "Eyfel Kulesi ve aşk şehri Paris'e ev sahipliği yapan Batı Avrupa ülkesi.",
        "GABON":                "Orta Afrika'da ekvator ormanlarıyla kaplı, başkenti Libreville olan ülke.",
        "GAMBİYA":              "Afrika'nın en küçük ülkesi; Gambiya Nehri boyunca uzanır.",
        "GANA":                 "Batı Afrika'da ilk bağımsızlığını kazanan sub-Sahra ülkesi; başkenti Akra'dır.",
        "GİNE":                 "Batı Afrika'da, başkenti Konakri olan, boksit zengini ülke.",
        "GUYANA":               "Güney Amerika'nın kuzey kıyısında, başkenti Georgetown olan İngilizce konuşan ülke.",
        "GUATEMALA":            "Orta Amerika'da Maya uygarlığının izlerini taşıyan, başkenti Guatemala City olan ülke.",
        "GÜNEY AFRİKA":         "Afrika'nın güneyinde üç başkentli (Pretoria, Capetown, Bloemfontein) ülke.",
        "GÜNEY KORE":           "Kore Yarımadası'nın güneyinde, başkenti Seul olan teknoloji ve K-Pop ülkesi.",
        "GÜRCİSTAN":            "Kafkasya'da Karadeniz kıyısında, başkenti Tiflis olan ülke.",
        "HIRVATİSTAN":          "Adriyatik kıyıları ve Dubrovnik şehriyle ünlü Balkan ülkesi.",
        "HİNDİSTAN":            "Dünyanın en kalabalık ikinci ülkesi; Tac Mahal ve Ganj Nehri'yle ünlüdür.",
        "HOLLANDA":              "Yel değirmenleri, laleler ve kanallarıyla tanınan, başkenti Amsterdam olan ülke.",
        "HONDURAS":             "Orta Amerika'da Karayip kıyısı bulunan, başkenti Tegucigalpa olan ülke.",
        "IRAK":                 "Mezopotamya'nın kalbi olan, Bağdat başkentli Orta Doğu ülkesi.",
        "İRAN":                 "Pers medeniyetinin beşiği, Tahran başkentli Orta Doğu ülkesi.",
        "İRLANDA":              "Yeşil adalar ve Dublin başkentiyle tanınan, Atlantik kıyısındaki Celtic ülkesi.",
        "İNGİLTERE":            "Londra başkentli, Buckingham Sarayı ve Big Ben ile ünlü ada ülkesi.",
        "İSPANYA":              "Flamenco dansı, boğa güreşi ve Barselona şehriyle ünlü Güney Avrupa ülkesi.",
        "İSRAİL":               "Orta Doğu'da Kudüs'ü başkent kabul eden, üç semavi dine kutsal ülke.",
        "İSVEÇ":                "IKEA ve ABBA'nın anavatanı olan, Stockholm başkentli İskandinav ülkesi.",
        "İSVİÇRE":              "Alpler, saatler ve çikolatayla ünlü, tarafsız Orta Avrupa ülkesi.",
        "İTALYA":               "Roma, Venedik ve pizza-makarna kültürüyle ünlü Güney Avrupa ülkesi.",
        "İZLANDA":              "Kuzey Atlantik'te volkanik adada kurulan, başkenti Reykjavik olan ülke.",
        "JAMAİKA":              "Karayipler'de reggae müziği ve Bob Marley'in vatanı olan ada ülkesi.",
        "JAPONYA":              "Fuji Dağı, sakura çiçekleri ve teknolojisiyle ünlü Doğu Asya ada ülkesi.",
        "KAMBOÇYA":             "Angkor Wat tapınaklarıyla ünlü, Güneydoğu Asya'da başkenti Phnom Penh olan ülke.",
        "KAMERUN":              "Orta Afrika'da çeşitli ekosistemlere ev sahipliği yapan, başkenti Yaounde olan ülke.",
        "KANADA":               "Dünyanın en uzun sahil şeridine sahip, başkenti Ottawa olan kuzey ülkesi.",
        "KARADAĞ":              "Adriyatik kıyısında küçük bir Balkan ülkesi; başkenti Podgorica'dır.",
        "KATAR":                "Körfez'de doğal gaz zengini, Al-Thani hanedanının yönettiği yarımada ülkesi.",
        "KAZAKİSTAN":           "Dünyanın en büyük karayla çevrili ülkesi; başkenti Astana'dır.",
        "KENYA":                "Doğu Afrika'da safari ve Masai Mara'sıyla ünlü, Nairobi başkentli ülke.",
        "KIBRIS":               "Akdeniz'in üçüncü büyük adası; kuzey ve güney olarak ikiye bölünmüştür.",
        "KIRGIZİSTAN":          "Orta Asya'da Issık Göl ile ünlü, başkenti Bişkek olan dağlık ülke.",
        "KOLOMBİYA":            "Güney Amerika'nın kuzeybatısında, başkenti Bogota olan, kahvesiyle ünlü ülke.",
        "KONGO":                "Afrika'nın ikinci büyük ülkesi; Kongo Nehri'nin kıyısında uzanır.",
        "KOSOVA":               "Balkanlar'da Sırbistan'dan bağımsızlığını 2008'de ilan eden genç ülke.",
        "KOSTA RİKA":           "Orta Amerika'da biyoçeşitliliği ve çevre koruma politikasıyla öne çıkan ülke.",
        "KUVEYT":               "Körfez'de petrol zengini, başkenti Kuveyt Şehri olan küçük emirlik.",
        "KUZEY KORE":           "Kore Yarımadası'nın kuzeyinde, dışa kapalı tek parti yönetimindeki ülke.",
        "KÜBA":                 "Karayipler'de puro, salsa ve Che Guevara'nın simgesi olan ada ülkesi.",
        "LAOS":                 "Güneydoğu Asya'nın tek denize çıkışı olmayan ülkesi; başkenti Vientiane'dir.",
        "LETONYA":              "Baltık Denizi kıyısında, Riga başkentli Kuzey Avrupa ülkesi.",
        "LİBYA":                "Kuzey Afrika'da Sahara'nın büyük bölümünü kaplayan, başkenti Trablus olan ülke.",
        "LİHTENŞTAYN":          "İsviçre ve Avusturya arasında sıkışmış, dünyanın en küçük ülkelerinden biri.",
        "LİTVANYA":             "Baltık ülkelerinin en güneyindeki, başkenti Vilnius olan ülke.",
        "LÜBNAN":               "Orta Doğu'da Akdeniz kıyısında, sedir ağacını bayrağında taşıyan ülke.",
        "LÜKSEMBURG":           "Batı Avrupa'nın en küçük ülkelerinden biri ve en zengin ülkelerinden biri.",
        "MACARİSTAN":           "Orta Avrupa'da Tuna Nehri kıyısında, başkenti Budapeşte olan ülke.",
        "MAKEDONYA":            "Balkanlar'da Üsküp başkentli, Büyük İskender'in vatanı kabul edilen ülke.",
        "MALDİVLER":            "Hint Okyanusu'nda binden fazla mercan adasından oluşan ada devleti.",
        "MALEZYA":              "Güneydoğu Asya'da Petronas Kuleleri ve Borneo ormanlarıyla ünlü ülke.",
        "MALİ":                 "Batı Afrika'da Timbuktu şehri ve Niger Nehri'yle ünlü, başkenti Bamako olan ülke.",
        "MALTA":                "Akdeniz'de küçük ada ülkesi; tarihi Valletta şehri UNESCO mirası listesindedir.",
        "MEKSİKA":              "Aztek uygarlığının beşiği, Meksiko City başkentli Orta Amerika'nın kapısı.",
        "MISIR":                "Piramitler, Sfenks ve Nil Nehri ile dünya tarihinin simgesi olan Afrika ülkesi.",
        "MOĞOLİSTAN":           "Çengiz Han'ın vatanı; dünyanın en seyrek nüfuslu ülkelerinden biridir.",
        "MOLDOVA":              "Doğu Avrupa'da Romanya ile Ukrayna arasında kalan, başkenti Kişinev olan küçük ülke.",
        "MONAKO":               "Fransa'ya komşu dünyanın ikinci küçük ülkesi; kumarhane ve Formula 1 ile ünlüdür.",
        "MORİTANYA":            "Batı Afrika'da Sahra Çölü'nün büyük bölümünü kaplayan, başkenti Nuakşot olan ülke.",
        "MOZAMBİK":             "Doğu Afrika kıyısında, Hint Okyanusu'na açılan, başkenti Maputo olan ülke.",
        "MYANMAR":              "Güneydoğu Asya'da altın pagodaları ve pirinç tarlaları ile ünlü ülke.",
        "NAMİBYA":              "Afrika'nın güneyinde Namib Çölü'ne ev sahipliği yapan, başkenti Windhoek olan ülke.",
        "NEPAL":                "Everest Dağı'na ev sahipliği yapan, Himalayalar'ın kalbindeki Güney Asya ülkesi.",
        "NİJER":                "Sahra Çölü'nün büyük bölümünü kaplayan, Afrika'nın en yoksul ülkelerinden biri.",
        "NİJERYA":              "Afrika'nın en kalabalık ülkesi; Lagos ve petrol zengini Nijer Deltası ile bilinir.",
        "NORVEÇ":               "Fiyortları ve kuzey ışıkları ile ünlü, İskandinav yarımadasının batısındaki ülke.",
        "ÖZBEKİSTAN":           "İpek Yolu üzerindeki Semerkant ve Buhara şehirleriyle ünlü Orta Asya ülkesi.",
        "PAKİSTAN":             "Güney Asya'da İslamabad başkentli, nükleer güce sahip ülke.",
        "PANAMA":               "Kuzey ve Güney Amerika'yı birbirine bağlayan kanalıyla ünlü Orta Amerika ülkesi.",
        "PARAGUAY":             "Güney Amerika'da iki komşu ülke arasında kalan, Asuncion başkentli ülke.",
        "PERU":                 "İnka uygarlığının beşiği; Machu Picchu ve Amazon'un başlangıcına ev sahipliği yapar.",
        "POLONYA":              "Orta Avrupa'da Varşova başkentli, tarihsel olarak birçok uygarlığa ev sahipliği yapan ülke.",
        "PORTEKİZ":             "İberya Yarımadası'nın batısındaki, dünyayı ilk keşfeden denizcilerin ülkesi.",
        "ROMANYA":              "Karpat Dağları ve Drakula efsanesiyle ünlü, Bükreş başkentli Balkan ülkesi.",
        "RUSYA":                "Yüzölçümüyle dünyanın en büyük ülkesi; başkenti Moskova'dır.",
        "SENEGAL":              "Batı Afrika'da Dakar başkentli, pembe renkli Gül Gölü ile tanınan ülke.",
        "SEYŞELLER":            "Hint Okyanusu'nda 115 adadan oluşan, bal ayı cenneti tropik ülke.",
        "SIRBİSTAN":            "Balkanlar'da Belgrad başkentli, rakı ve çift başlı kartal ile bilinen ülke.",
        "SİNGAPUR":             "Güneydoğu Asya'da küçük ada üzerinde kurulu; dünyanın en gelişmiş şehir-devleti.",
        "SLOVAKYA":             "Karpat Dağları eteklerinde, başkenti Bratislava olan Orta Avrupa ülkesi.",
        "SLOVENYA":             "Adriyatik kıyısında ve Alplerde, Ljubljana başkentli küçük Orta Avrupa ülkesi.",
        "SOMALİ":               "Afrika Boynuzu'nda yer alan, Mogadişu başkentli, uzun kıyı şeridiyle bilinen ülke.",
        "SRİ LANKA":            "Hindistan'ın güneyindeki çay bahçeleri ve filleriyle ünlü ada ülkesi.",
        "SUDAN":                "Afrika'nın kuzeydoğusunda Nil kıyısındaki en büyük ülkelerden biri; başkenti Hartum.",
        "SURİYE":               "Orta Doğu'da Şam başkentli, Palmira antik kentiyle bilinen ülke.",
        "SUUDİ ARABİSTAN":      "İslam'ın kutsal şehirleri Mekke ve Medine'ye ev sahipliği yapan petrol zengini ülke.",
        "ŞİLİ":                 "Güney Amerika'nın batı kıyısında kuzeyin çölünden güneyin buzullarına uzanan ülke.",
        "TACİKİSTAN":           "Orta Asya'da Duşanbe başkentli, büyük bölümü Pamir Dağları'ndan oluşan ülke.",
        "TANZANYA":             "Doğu Afrika'da Kilimanjaro Dağı ve Serengeti'ye ev sahipliği yapan ülke.",
        "TAYLAND":              "Güneydoğu Asya'da Budist tapınakları ve Bangok başkentiyle ünlü ülke.",
        "TAYVAN":               "Çin kıyısı açıklarındaki, teknoloji üretimiyle öne çıkan ada ülkesi.",
        "TOGO":                 "Batı Afrika'da kıyıya ince bir şerit gibi uzanan, başkenti Lomé olan ülke.",
        "TRİNİDAD VE TOBAGO":   "Karayipler'in güneyinde iki adadan oluşan, başkenti Port of Spain olan ülke.",
        "TUNUS":                "Kuzey Afrika'da Akdeniz kıyısında, Kartaca uygarlığına beşiklik etmiş ülke.",
        "TÜRKİYE":              "Asya ve Avrupa'yı birbirine bağlayan, İstanbul ve Ankara'ya ev sahipliği yapan ülke.",
        "TÜRKMENİSTAN":         "Orta Asya'da Karakum Çölü ve gece gündüz yanan 'Cehennem Kapısı' ile bilinen ülke.",
        "UGANDA":               "Doğu Afrika'da kaynak Nil ve dağ gorillerine ev sahipliği yapan, Kampala başkentli ülke.",
        "UKRAYNA":              "Doğu Avrupa'nın en büyük ülkesi; Kiev başkentli ve buğday tarlaları ile bilinir.",
        "UMMAN":                "Arap Yarımadası'nın güneydoğusunda, Maskat başkentli, serin fiyortlarıyla ünlü ülke.",
        "URUGUAY":              "Güney Amerika'nın en küçük ülkelerinden biri; başkenti Montevideo'dur.",
        "ÜRDÜN":                "Orta Doğu'da Petra antik kenti ve Ölü Deniz'e ev sahipliği yapan Haşimi Krallığı.",
        "VENEZUELA":            "Güney Amerika'da Angel Şelalesi ve petrol rezervleriyle ünlü, Caracas başkentli ülke.",
        "VİETNAM":              "Güneydoğu Asya'da Ha Long Körfezi ve pirinç tarlaları ile ünlü ülke.",
        "YEMEN":                "Arap Yarımadası'nın güneyinde, Sana başkentli; kahvenin anavatanlarından sayılır.",
        "YENİ ZELANDA":         "Avustralya'nın güneydoğusunda, Hobbit filmlerinin çekildiği ada ülkesi.",
        "YUNANİSTAN":           "Antik medeniyetin beşiği; Akropolis ve Olimpiyat Oyunları'nın vatanı.",
        "ZAMBİYA":              "Orta Afrika'da Zambezi Nehri ve Victoria Şelalesi'ne ev sahipliği yapan, Lusaka başkentli ülke.",
        "ZİMBABVE":             "Güney Afrika'da Victoria Şelalesi ve büyük taş kalıntılarıyla ünlü, Harare başkentli ülke.",
    ]
}
