import Foundation

extension WordList {

    // MARK: - Words

    static let ulkelerWords: [WordEntry] = [
        WordEntry(word: "AFGANİSTAN", category: "Ülkeler"),
        WordEntry(word: "ALMANYA", category: "Ülkeler"),
        WordEntry(word: "AMERİKA", category: "Ülkeler"),
        WordEntry(word: "ANDORRA", category: "Ülkeler"),
        WordEntry(word: "ANGOLA", category: "Ülkeler"),
        WordEntry(word: "ARJANTİN", category: "Ülkeler"),
        WordEntry(word: "ARNAVUTLUK", category: "Ülkeler"),
        WordEntry(word: "AVUSTRALYA", category: "Ülkeler"),
        WordEntry(word: "AVUSTURYA", category: "Ülkeler"),
        WordEntry(word: "AZERBAYCAN", category: "Ülkeler"),
        WordEntry(word: "BAHREYN", category: "Ülkeler"),
        WordEntry(word: "BANGLADEŞ", category: "Ülkeler"),
        WordEntry(word: "BELÇİKA", category: "Ülkeler"),
        WordEntry(word: "BENİN", category: "Ülkeler"),
        WordEntry(word: "BELARUS", category: "Ülkeler"),
        WordEntry(word: "BOLİVYA", category: "Ülkeler"),
        WordEntry(word: "BOSNA HERSEK", category: "Ülkeler"),
        WordEntry(word: "BREZİLYA", category: "Ülkeler"),
        WordEntry(word: "BULGARİSTAN", category: "Ülkeler"),
        WordEntry(word: "BURKİNA FASO", category: "Ülkeler"),
        WordEntry(word: "CEZAYİR", category: "Ülkeler"),
        WordEntry(word: "ÇAD", category: "Ülkeler"),
        WordEntry(word: "ÇEK CUMHURİYETİ", category: "Ülkeler"),
        WordEntry(word: "ÇİN", category: "Ülkeler"),
        WordEntry(word: "DANİMARKA", category: "Ülkeler"),
        WordEntry(word: "DOMİNİK CUMHURİYETİ", category: "Ülkeler"),
        WordEntry(word: "EKVADOR", category: "Ülkeler"),
        WordEntry(word: "EL SALVADOR", category: "Ülkeler"),
        WordEntry(word: "ENDONEZYA", category: "Ülkeler"),
        WordEntry(word: "ERMENİSTAN", category: "Ülkeler"),
        WordEntry(word: "ESTONYA", category: "Ülkeler"),
        WordEntry(word: "ETİYOPYA", category: "Ülkeler"),
        WordEntry(word: "FAS", category: "Ülkeler"),
        WordEntry(word: "FİJİ", category: "Ülkeler"),
        WordEntry(word: "FİLDİŞİ SAHİLİ", category: "Ülkeler"),
        WordEntry(word: "FİLİPİNLER", category: "Ülkeler"),
        WordEntry(word: "FİLİSTİN", category: "Ülkeler"),
        WordEntry(word: "FİNLANDİYA", category: "Ülkeler"),
        WordEntry(word: "FRANSA", category: "Ülkeler"),
        WordEntry(word: "GABON", category: "Ülkeler"),
        WordEntry(word: "GAMBİYA", category: "Ülkeler"),
        WordEntry(word: "GANA", category: "Ülkeler"),
        WordEntry(word: "GİNE", category: "Ülkeler"),
        WordEntry(word: "GUYANA", category: "Ülkeler"),
        WordEntry(word: "GUATEMALA", category: "Ülkeler"),
        WordEntry(word: "GÜNEY AFRİKA", category: "Ülkeler"),
        WordEntry(word: "GÜNEY KORE", category: "Ülkeler"),
        WordEntry(word: "GÜRCİSTAN", category: "Ülkeler"),
        WordEntry(word: "HIRVATİSTAN", category: "Ülkeler"),
        WordEntry(word: "HİNDİSTAN", category: "Ülkeler"),
        WordEntry(word: "HOLLANDA", category: "Ülkeler"),
        WordEntry(word: "HONDURAS", category: "Ülkeler"),
        WordEntry(word: "IRAK", category: "Ülkeler"),
        WordEntry(word: "İRAN", category: "Ülkeler"),
        WordEntry(word: "İRLANDA", category: "Ülkeler"),
        WordEntry(word: "İNGİLTERE", category: "Ülkeler"),
        WordEntry(word: "İSPANYA", category: "Ülkeler"),
        WordEntry(word: "İSRAİL", category: "Ülkeler"),
        WordEntry(word: "İSVEÇ", category: "Ülkeler"),
        WordEntry(word: "İSVİÇRE", category: "Ülkeler"),
        WordEntry(word: "İTALYA", category: "Ülkeler"),
        WordEntry(word: "İZLANDA", category: "Ülkeler"),
        WordEntry(word: "JAMAİKA", category: "Ülkeler"),
        WordEntry(word: "JAPONYA", category: "Ülkeler"),
        WordEntry(word: "KAMBOÇYA", category: "Ülkeler"),
        WordEntry(word: "KAMERUN", category: "Ülkeler"),
        WordEntry(word: "KANADA", category: "Ülkeler"),
        WordEntry(word: "KARADAĞ", category: "Ülkeler"),
        WordEntry(word: "KATAR", category: "Ülkeler"),
        WordEntry(word: "KAZAKİSTAN", category: "Ülkeler"),
        WordEntry(word: "KENYA", category: "Ülkeler"),
        WordEntry(word: "KIBRIS", category: "Ülkeler"),
        WordEntry(word: "KIRGIZİSTAN", category: "Ülkeler"),
        WordEntry(word: "KOLOMBİYA", category: "Ülkeler"),
        WordEntry(word: "KONGO", category: "Ülkeler"),
        WordEntry(word: "KOSOVA", category: "Ülkeler"),
        WordEntry(word: "KOSTA RİKA", category: "Ülkeler"),
        WordEntry(word: "KUVEYT", category: "Ülkeler"),
        WordEntry(word: "KUZEY KORE", category: "Ülkeler"),
        WordEntry(word: "KÜBA", category: "Ülkeler"),
        WordEntry(word: "LAOS", category: "Ülkeler"),
        WordEntry(word: "LETONYA", category: "Ülkeler"),
        WordEntry(word: "LİBYA", category: "Ülkeler"),
        WordEntry(word: "LİHTENŞTAYN", category: "Ülkeler"),
        WordEntry(word: "LİTVANYA", category: "Ülkeler"),
        WordEntry(word: "LÜBNAN", category: "Ülkeler"),
        WordEntry(word: "LÜKSEMBURG", category: "Ülkeler"),
        WordEntry(word: "MACARİSTAN", category: "Ülkeler"),
        WordEntry(word: "MAKEDONYA", category: "Ülkeler"),
        WordEntry(word: "MALDİVLER", category: "Ülkeler"),
        WordEntry(word: "MALEZYA", category: "Ülkeler"),
        WordEntry(word: "MALİ", category: "Ülkeler"),
        WordEntry(word: "MALTA", category: "Ülkeler"),
        WordEntry(word: "MEKSİKA", category: "Ülkeler"),
        WordEntry(word: "MISIR", category: "Ülkeler"),
        WordEntry(word: "MOĞOLİSTAN", category: "Ülkeler"),
        WordEntry(word: "MOLDOVA", category: "Ülkeler"),
        WordEntry(word: "MONAKO", category: "Ülkeler"),
        WordEntry(word: "MORİTANYA", category: "Ülkeler"),
        WordEntry(word: "MOZAMBİK", category: "Ülkeler"),
        WordEntry(word: "MYANMAR", category: "Ülkeler"),
        WordEntry(word: "NAMİBYA", category: "Ülkeler"),
        WordEntry(word: "NEPAL", category: "Ülkeler"),
        WordEntry(word: "NİJER", category: "Ülkeler"),
        WordEntry(word: "NİJERYA", category: "Ülkeler"),
        WordEntry(word: "NORVEÇ", category: "Ülkeler"),
        WordEntry(word: "ÖZBEKİSTAN", category: "Ülkeler"),
        WordEntry(word: "PAKİSTAN", category: "Ülkeler"),
        WordEntry(word: "PANAMA", category: "Ülkeler"),
        WordEntry(word: "PARAGUAY", category: "Ülkeler"),
        WordEntry(word: "PERU", category: "Ülkeler"),
        WordEntry(word: "POLONYA", category: "Ülkeler"),
        WordEntry(word: "PORTEKİZ", category: "Ülkeler"),
        WordEntry(word: "ROMANYA", category: "Ülkeler"),
        WordEntry(word: "RUSYA", category: "Ülkeler"),
        WordEntry(word: "SENEGAL", category: "Ülkeler"),
        WordEntry(word: "SEYŞELLER", category: "Ülkeler"),
        WordEntry(word: "SIRBİSTAN", category: "Ülkeler"),
        WordEntry(word: "SİNGAPUR", category: "Ülkeler"),
        WordEntry(word: "SLOVAKYA", category: "Ülkeler"),
        WordEntry(word: "SLOVENYA", category: "Ülkeler"),
        WordEntry(word: "SOMALİ", category: "Ülkeler"),
        WordEntry(word: "SRİ LANKA", category: "Ülkeler"),
        WordEntry(word: "SUDAN", category: "Ülkeler"),
        WordEntry(word: "SURİYE", category: "Ülkeler"),
        WordEntry(word: "SUUDİ ARABİSTAN", category: "Ülkeler"),
        WordEntry(word: "ŞİLİ", category: "Ülkeler"),
        WordEntry(word: "TACİKİSTAN", category: "Ülkeler"),
        WordEntry(word: "TANZANYA", category: "Ülkeler"),
        WordEntry(word: "TAYLAND", category: "Ülkeler"),
        WordEntry(word: "TAYVAN", category: "Ülkeler"),
        WordEntry(word: "TOGO", category: "Ülkeler"),
        WordEntry(word: "TRİNİDAD VE TOBAGO", category: "Ülkeler"),
        WordEntry(word: "TUNUS", category: "Ülkeler"),
        WordEntry(word: "TÜRKİYE", category: "Ülkeler"),
        WordEntry(word: "TÜRKMENİSTAN", category: "Ülkeler"),
        WordEntry(word: "UGANDA", category: "Ülkeler"),
        WordEntry(word: "UKRAYNA", category: "Ülkeler"),
        WordEntry(word: "UMMAN", category: "Ülkeler"),
        WordEntry(word: "URUGUAY", category: "Ülkeler"),
        WordEntry(word: "ÜRDÜN", category: "Ülkeler"),
        WordEntry(word: "VENEZUELA", category: "Ülkeler"),
        WordEntry(word: "VİETNAM", category: "Ülkeler"),
        WordEntry(word: "YEMEN", category: "Ülkeler"),
        WordEntry(word: "YENİ ZELANDA", category: "Ülkeler"),
        WordEntry(word: "YUNANİSTAN", category: "Ülkeler"),
        WordEntry(word: "ZAMBİYA", category: "Ülkeler"),
        WordEntry(word: "ZİMBABVE", category: "Ülkeler"),
    ]

    // MARK: - Hints

    static let ulkelerHints: [String: String] = [:]
}
