import Foundation

extension WordList {

    // MARK: - Words

    static let sinemaPlusWords: [WordEntry] = [
        WordEntry(word: "YÖNETMEN",    category: "Sinema"),
        WordEntry(word: "SENARYO",     category: "Sinema"),
        WordEntry(word: "OYUNCU",      category: "Sinema"),
        WordEntry(word: "AKTÖR",       category: "Sinema"),
        WordEntry(word: "AKTRİS",      category: "Sinema"),
        WordEntry(word: "KOSTÜM",      category: "Sinema"),
        WordEntry(word: "PRODÜKSYON",  category: "Sinema"),
        WordEntry(word: "FRAGMAN",     category: "Sinema"),
        WordEntry(word: "JENERİK",     category: "Sinema"),
        WordEntry(word: "DUBLAJ",      category: "Sinema"),
        WordEntry(word: "ÇEKİM",       category: "Sinema"),
        WordEntry(word: "DEKOR",       category: "Sinema"),
        WordEntry(word: "PLATFORM",    category: "Sinema"),
        WordEntry(word: "FESTİVAL",    category: "Sinema"),
        WordEntry(word: "BELGESEL",    category: "Sinema"),
        WordEntry(word: "ANİMASYON",   category: "Sinema"),
        WordEntry(word: "GİŞE",        category: "Sinema"),
        WordEntry(word: "RÖPORTAJ",    category: "Sinema"),
        WordEntry(word: "KOLEKSİYON",  category: "Sinema"),
        WordEntry(word: "KARAKTER",    category: "Sinema"),
        WordEntry(word: "KORKU",       category: "Sinema"),
        WordEntry(word: "DRAM",        category: "Sinema"),
        WordEntry(word: "KOMEDİ",      category: "Sinema"),
        WordEntry(word: "AKSİYON",     category: "Sinema"),
        WordEntry(word: "GERİLİM",     category: "Sinema"),
        WordEntry(word: "KAMERA",      category: "Sinema"),
        WordEntry(word: "OYUNCULUK",   category: "Sinema"),
        WordEntry(word: "OSCAR",       category: "Sinema"),
        WordEntry(word: "PALME",       category: "Sinema"),
        WordEntry(word: "REMAKE",      category: "Sinema"),
        WordEntry(word: "SEQUEL",      category: "Sinema"),
        WordEntry(word: "PROLOG",      category: "Sinema"),
        WordEntry(word: "EPİLOG",      category: "Sinema"),
        WordEntry(word: "KURGU",       category: "Sinema"),
        WordEntry(word: "MONTAJ",      category: "Sinema"),
        WordEntry(word: "SET",         category: "Sinema"),
        WordEntry(word: "STÜDYO",      category: "Sinema"),
        WordEntry(word: "REPLİK",      category: "Sinema"),
        WordEntry(word: "FLAŞBEK",     category: "Sinema"),
        WordEntry(word: "MAKYAJ",      category: "Sinema"),
        WordEntry(word: "EFEKT",       category: "Sinema"),
        WordEntry(word: "SAHNE",       category: "Sinema"),
        WordEntry(word: "KADRO",       category: "Sinema"),
        WordEntry(word: "SEZON",       category: "Sinema"),
        WordEntry(word: "SERİ",        category: "Sinema"),
        WordEntry(word: "BÖLÜM",       category: "Sinema"),
        WordEntry(word: "MİZANSEN",    category: "Sinema"),
        WordEntry(word: "JANR",        category: "Sinema"),
        WordEntry(word: "YAPIMCI",     category: "Sinema"),
        WordEntry(word: "TRAJEDİ",     category: "Sinema"),
        WordEntry(word: "DESTAN",      category: "Sinema"),
        WordEntry(word: "MONOLOG",     category: "Sinema"),
        WordEntry(word: "DİYALOG",     category: "Sinema"),
        WordEntry(word: "ROMAN",       category: "Sinema"),
        WordEntry(word: "ALTYAZI",     category: "Sinema"),
        WordEntry(word: "BİYOGRAFİ",   category: "Sinema"),
        WordEntry(word: "GÖSTERİM",    category: "Sinema"),
    ]

    // MARK: - Hints

    static let sinemaPlusHints: [String: String] = [
        "YÖNETMEN":    "Bir filmin sanatsal vizyonunu belirleyip ekibi yöneten kişi.",
        "SENARYO":     "Bir filmin diyaloglarını ve sahneleri ayrıntılı olarak aktaran yazılı metin.",
        "OYUNCU":      "Sahnede ya da kameranın önünde bir karakteri canlandıran sanatçı.",
        "AKTÖR":       "Sinema ya da tiyatroda erkek bir karakteri oynayan erkek sanatçı.",
        "AKTRİS":      "Bir filmde ya da sahne eserinde kadın rolü üstlenen kadın sanatçı.",
        "KOSTÜM":      "Oyuncuların sahnede ya da filmde giydikleri döneme ya da karaktere özgü kıyafet.",
        "PRODÜKSYON":  "Bir filmi hayata geçirmek için gereken tüm organizasyon ve yapım süreci.",
        "FRAGMAN":     "Bir filmin gösterime girmeden önce yayınlanan kısa tanıtım klibi.",
        "JENERİK":     "Filmin başında ya da sonunda yönetmen ve oyuncuların adlarının gösterildiği bölüm.",
        "DUBLAJ":      "Yabancı dildeki seslerin yerli dilin sesleriyle yeniden kaydedilmesi işlemi.",
        "ÇEKİM":       "Kameranın duraksatılmadan kaydettiği tek ve kesintisiz görüntü birimi.",
        "DEKOR":       "Sahne ya da film setini bağlam ve atmosfer açısından dolduran sanatsal tasarım.",
        "PLATFORM":    "Film ve dizi içeriklerine internet üzerinden erişimi sağlayan dijital yayın servisi.",
        "FESTİVAL":    "Filmlerin jüri ve izleyicilerin önünde yarıştığı uluslararası sinema etkinliği.",
        "BELGESEL":    "Gerçek olayları ya da kişileri kurgusuz biçimde anlatan film türü.",
        "ANİMASYON":   "Çizim ya da dijital tekniklerle oluşturulan hareketli görüntü sanatı.",
        "GİŞE":        "Bilet satışları üzerinden ölçülen filmin ticari başarısı.",
        "RÖPORTAJ":    "Bir kişiyle yüz yüze ya da kameraya karşı yapılan sorulu cevaplı söyleşi.",
        "KOLEKSİYON":  "Bir yönetmen ya da seriye ait filmlerin bir arada sunulduğu özel derleme.",
        "KARAKTER":    "Bir hikayede yaşayan ve eylemleriyle olay örgüsünü harekete geçiren kurgu kişisi.",
        "KORKU":       "İzleyiciyi gerilim ve ürpertiyle etkileyen sinema türü.",
        "DRAM":        "İnsan duygularını ve çatışmaları derinlemesine ele alan film türü.",
        "KOMEDİ":      "Güldürü ve mizahı ön plana çıkaran eğlenceli film türü.",
        "AKSİYON":     "Hızlı tempo, dövüş sahneleri ve gerilimli çatışmaları içeren film türü.",
        "GERİLİM":     "İzleyiciyi sürekli merak ve endişe içinde tutan yoğun anlatı türü.",
        "KAMERA":      "Filmin görüntülerini kaydeden optik ve elektronik çekim cihazı.",
        "OYUNCULUK":   "Bir karakteri gerçekçi ve inandırıcı biçimde canlandırma sanatı.",
        "OSCAR":       "Akademi'nin her yıl en iyi film çalışmalarına verdiği prestijli altın heykelcik ödülü.",
        "PALME":       "Cannes Film Festivali'nin en iyi filme verdiği altın renkli büyük ödül.",
        "REMAKE":      "Daha önce çekilen bir filmin yeniden yapımı olan sinema eseri.",
        "SEQUEL":      "Bir filmin olaylarını devam ettiren ikinci ya da ilerleyen bölüm.",
        "PROLOG":      "Filmin ya da eserin asıl başlamasından önceki kısa giriş bölümü.",
        "EPİLOG":      "Hikayenin tamamlanmasının ardından gelen bitiş sonrası bölüm.",
        "KURGU":       "Ham görüntülerin anlam ve akıcılık kazanması için yapılan düzenleme ve birleştirme işi.",
        "MONTAJ":      "Görüntü ve seslerin belirli bir anlam yaratmak üzere sıralanıp birleştirilmesi sanatı.",
        "SET":         "Film çekimlerinin gerçekleştiği, sahne tasarımıyla donatılmış çalışma alanı.",
        "STÜDYO":      "Film ya da ses kaydının yapıldığı profesyonelce tasarlanmış üretim tesisi.",
        "REPLİK":      "Bir karakterin senaryoda söylediği belirlenmiş konuşma satırı.",
        "FLAŞBEK":     "Hikayenin zamanını geçmişe götürerek olayları geriye dönük anlatan sinema tekniği.",
        "MAKYAJ":      "Oyuncuların karaktere uygun görünmesi için uygulanan yüz ve vücut düzenlemesi.",
        "EFEKT":       "Dijital ya da pratik yöntemlerle oluşturulan görsel ya da ses efekti.",
        "SAHNE":       "Bir filmin belirli bir mekanda geçen ve kendi içinde bütünlük taşıyan bölümü.",
        "KADRO":       "Bir filmin çekiminde görev alan tüm oyuncu ve ekibin bütünü.",
        "SEZON":       "Bir dizi yapımın belirli bölümleri kapsayan yayın dönemi.",
        "SERİ":        "Aynı evren ya da karakterleri devam ettiren birden fazla filmden oluşan bütün.",
        "BÖLÜM":       "Bir dizi ya da mini serinin her hafta yayınlanan tek parçası.",
        "MİZANSEN":    "Yönetmenin kamera önünde oluşturduğu tüm görsel kompozisyon tasarımı.",
        "JANR":        "Filmlerin içerik ve anlatı özelliklerine göre ayrıldığı tür kategorisi.",
        "YAPIMCI":     "Bir filmin finansmanını sağlayarak genel yapım sürecini denetleyen kişi.",
        "TRAJEDİ":     "Kahramanın kaçınılmaz bir sona doğru ilerlediği dramatik anlatı türü.",
        "DESTAN":      "Kahramanlık ve tarihi olayları destansı bir üslupla anlatan uzun anlatı.",
        "MONOLOG":     "Bir karakterin sahne üzerinde tek başına yaptığı uzun ve içli konuşma.",
        "DİYALOG":     "İki ya da daha fazla karakterin birbirine yönelttiği konuşmalar dizisi.",
        "ROMAN":       "Sinema ve edebiyatın kesiştiği, sinemaya uyarlanan ya da esinlenen uzun hikaye.",
        "ALTYAZI":     "Yabancı dildeki diyalogların ekranın alt bölümünde yazıyla gösterimi.",
        "BİYOGRAFİ":   "Gerçek bir kişinin hayatını, başarılarını ve zorluklarını anlatan film türü.",
        "GÖSTERİM":    "Bir filmin seyirci karşısında perdede ilk kez izlenmeye sunulduğu etkinlik.",
    ]
}
