import Foundation

extension WordList {

    // MARK: - Words

    static let tarihWords: [WordEntry] = [
        WordEntry(word: "ALEMDAR", category: "Tarih"),
        WordEntry(word: "ALP ER TUNGA", category: "Tarih"),
        WordEntry(word: "ANTLAŞMA", category: "Tarih"),
        WordEntry(word: "ARIZ", category: "Tarih"),
        WordEntry(word: "ARŞİDÜK", category: "Tarih"),
        WordEntry(word: "ATABEYİ", category: "Tarih"),
        WordEntry(word: "AVARIZ", category: "Tarih"),
        WordEntry(word: "BALKAN SAVAŞLARI", category: "Tarih"),
        WordEntry(word: "BARIŞ", category: "Tarih"),
        WordEntry(word: "BEDESTEN", category: "Tarih"),
        WordEntry(word: "CEMİYETİ AKVAM", category: "Tarih"),
        WordEntry(word: "CÜLUS", category: "Tarih"),
        WordEntry(word: "CÜLUS BAHŞİŞİ", category: "Tarih"),
        WordEntry(word: "ÇANAKKALE SAVAŞI", category: "Tarih"),
        WordEntry(word: "ÇELEBİ", category: "Tarih"),
        WordEntry(word: "DARÜLFÜNUN", category: "Tarih"),
        WordEntry(word: "DEVRİM", category: "Tarih"),
        WordEntry(word: "DEFTERDAR", category: "Tarih"),
        WordEntry(word: "DERBENT", category: "Tarih"),
        WordEntry(word: "DEREBEYİ", category: "Tarih"),
        WordEntry(word: "DİRLİK", category: "Tarih"),
        WordEntry(word: "DİVAN", category: "Tarih"),
        WordEntry(word: "EMPERYALİZM", category: "Tarih"),
        WordEntry(word: "ENDERUN", category: "Tarih"),
        WordEntry(word: "ENDÜLÜS", category: "Tarih"),
        WordEntry(word: "ETNOGRAFYA", category: "Tarih"),
        WordEntry(word: "FATİH SULTAN MEHMET", category: "Tarih"),
        WordEntry(word: "FEODALİZM", category: "Tarih"),
        WordEntry(word: "FERMAN", category: "Tarih"),
        WordEntry(word: "FETRET", category: "Tarih"),
        WordEntry(word: "FETVA", category: "Tarih"),
        WordEntry(word: "FIRKA", category: "Tarih"),
        WordEntry(word: "FIKIH", category: "Tarih"),
        WordEntry(word: "GANİMET", category: "Tarih"),
        WordEntry(word: "GÖÇ", category: "Tarih"),
        WordEntry(word: "GÖÇEBE", category: "Tarih"),
        WordEntry(word: "HAKAN", category: "Tarih"),
        WordEntry(word: "HAN", category: "Tarih"),
        WordEntry(word: "HEGEMONYA", category: "Tarih"),
        WordEntry(word: "HİCRET", category: "Tarih"),
        WordEntry(word: "HİLAFET", category: "Tarih"),
        WordEntry(word: "HİSAR", category: "Tarih"),
        WordEntry(word: "HİYERARŞİ", category: "Tarih"),
        WordEntry(word: "HİYEROGLİF", category: "Tarih"),
        WordEntry(word: "İMPARATOR", category: "Tarih"),
        WordEntry(word: "İMPARATORLUK", category: "Tarih"),
        WordEntry(word: "İHTİLAL", category: "Tarih"),
        WordEntry(word: "İSTİLA", category: "Tarih"),
        WordEntry(word: "İSTİKLAL MAHKEMESİ", category: "Tarih"),
        WordEntry(word: "İTTİFAK", category: "Tarih"),
        WordEntry(word: "İTİLAF", category: "Tarih"),
        WordEntry(word: "KABOTAJ KANUNU", category: "Tarih"),
        WordEntry(word: "KADI", category: "Tarih"),
        WordEntry(word: "KADIASKER", category: "Tarih"),
        WordEntry(word: "KAĞAN", category: "Tarih"),
        WordEntry(word: "KALKOLİTİK", category: "Tarih"),
        WordEntry(word: "KALVENİZM", category: "Tarih"),
        WordEntry(word: "KAPİKULU", category: "Tarih"),
        WordEntry(word: "KAPİTALİZM", category: "Tarih"),
        WordEntry(word: "KAPİTÜLASYON", category: "Tarih"),
        WordEntry(word: "KAPTANI DERYA", category: "Tarih"),
        WordEntry(word: "KERVANSARAY", category: "Tarih"),
        WordEntry(word: "KİBELE", category: "Tarih"),
        WordEntry(word: "KİLİKYA", category: "Tarih"),
        WordEntry(word: "KONGRE", category: "Tarih"),
        WordEntry(word: "KRAL YOLU", category: "Tarih"),
        WordEntry(word: "KURGAN", category: "Tarih"),
        WordEntry(word: "KURTULUŞ SAVAŞI", category: "Tarih"),
        WordEntry(word: "KURULTAY", category: "Tarih"),
        WordEntry(word: "KUVAİ MİLLİYE", category: "Tarih"),
        WordEntry(word: "KÜLLİYE", category: "Tarih"),
        WordEntry(word: "KÜMBET", category: "Tarih"),
        WordEntry(word: "LAĞIMCI", category: "Tarih"),
        WordEntry(word: "LAHİT", category: "Tarih"),
        WordEntry(word: "LALA", category: "Tarih"),
        WordEntry(word: "LALE DEVRİ", category: "Tarih"),
        WordEntry(word: "LEJYON", category: "Tarih"),
        WordEntry(word: "LİYAKAT", category: "Tarih"),
        WordEntry(word: "LONCA", category: "Tarih"),
        WordEntry(word: "MAGNA CARTA", category: "Tarih"),
        WordEntry(word: "MAARİF", category: "Tarih"),
        WordEntry(word: "MAREŞAL", category: "Tarih"),
        WordEntry(word: "MEBUS", category: "Tarih"),
        WordEntry(word: "MECELLE", category: "Tarih"),
        WordEntry(word: "MEDENİYET", category: "Tarih"),
        WordEntry(word: "MEDRESE", category: "Tarih"),
        WordEntry(word: "MECLİSİ MEBUSAN", category: "Tarih"),
        WordEntry(word: "MEŞRUTİYET", category: "Tarih"),
        WordEntry(word: "MEŞVERET", category: "Tarih"),
        WordEntry(word: "MELİK", category: "Tarih"),
        WordEntry(word: "MİRAS", category: "Tarih"),
        WordEntry(word: "MİNARE", category: "Tarih"),
        WordEntry(word: "MONARŞİ", category: "Tarih"),
        WordEntry(word: "MÜBADELE", category: "Tarih"),
        WordEntry(word: "MÜDERRİS", category: "Tarih"),
        WordEntry(word: "MÜTAREKE", category: "Tarih"),
        WordEntry(word: "NİZAMI CEDİD", category: "Tarih"),
        WordEntry(word: "ORTAÇAĞ", category: "Tarih"),
        WordEntry(word: "PADİŞAH", category: "Tarih"),
        WordEntry(word: "PALEOLİTİK", category: "Tarih"),
        WordEntry(word: "PARLAMENTO", category: "Tarih"),
        WordEntry(word: "POLİTEİZM", category: "Tarih"),
        WordEntry(word: "REFORM", category: "Tarih"),
        WordEntry(word: "REJİM", category: "Tarih"),
        WordEntry(word: "RÖNESANS", category: "Tarih"),
        WordEntry(word: "RUHBAN", category: "Tarih"),
        WordEntry(word: "SADRAZAM", category: "Tarih"),
        WordEntry(word: "SALTANAT", category: "Tarih"),
        WordEntry(word: "SANAYİ İNKILABI", category: "Tarih"),
        WordEntry(word: "SAVAŞ", category: "Tarih"),
        WordEntry(word: "SEFER", category: "Tarih"),
        WordEntry(word: "SELÇUKLU", category: "Tarih"),
        WordEntry(word: "SENATO", category: "Tarih"),
        WordEntry(word: "SİPAHİ", category: "Tarih"),
        WordEntry(word: "SKOLASTİZM", category: "Tarih"),
        WordEntry(word: "ŞAMAN", category: "Tarih"),
        WordEntry(word: "ŞEHNAME", category: "Tarih"),
        WordEntry(word: "ŞEHREMİNİ", category: "Tarih"),
        WordEntry(word: "ŞEHZADE", category: "Tarih"),
        WordEntry(word: "ŞEYHÜLİSLAM", category: "Tarih"),
        WordEntry(word: "TASAVVUF", category: "Tarih"),
        WordEntry(word: "TEKFUR", category: "Tarih"),
        WordEntry(word: "TEOKRASİ", category: "Tarih"),
        WordEntry(word: "TİMAR", category: "Tarih"),
        WordEntry(word: "TUFAN", category: "Tarih"),
        WordEntry(word: "ULEMA", category: "Tarih"),
        WordEntry(word: "ULUFE", category: "Tarih"),
        WordEntry(word: "VELİAHT", category: "Tarih"),
        WordEntry(word: "VEZİR", category: "Tarih"),
        WordEntry(word: "ZAFER", category: "Tarih"),
        WordEntry(word: "ZAPTİYE", category: "Tarih"),
    ]

    // MARK: - Hints

    static let tarihHints: [String: String] = [
        "ATATÜRK":      "Türkiye Cumhuriyeti'nin kurucusu ve ilk cumhurbaşkanı.",
        "CUMHURİYET":   "1923'te ilan edilen, halkın egemenliğe dayandığı yönetim biçimi.",
        "DEVRİM":       "Köklü toplumsal ya da siyasi düzenin kısa sürede değiştirilmesi.",
        "FEODALİZM":    "Toprak karşılığı hizmet esasına dayalı Orta Çağ Avrupa yönetim sistemi.",
        "HİYEROGLİF":   "Antik Mısırlıların kullandığı resim yazısı sistemi.",
        "İMPARATORLUK": "Geniş toprakları idare eden tek hükümdar liderliğindeki büyük devlet.",
        "KURTULUŞ":     "İşgale karşı verilen bağımsızlık mücadelesi.",
        "OSMANLICA":    "Osmanlı İmparatorluğu döneminde kullanılan Türkçe-Arapça-Farsça dil karması.",
        "PAPİRÜS":      "Antik Mısırlıların yazmak için kullandığı bitkiden yapılmış malzeme.",
        "RÖNESANS":     "14-17. yüzyıllarda Avrupa'da sanat ve bilimin yeniden doğuşu.",
        "SEFERBERLİK":  "Bir ülkenin tüm kaynaklarının savaş için seferber edilmesi.",
        "TOPKAPI":      "İstanbul'da Osmanlı padişahlarının yüzyıllarca yaşadığı saray.",
        "BALKANLAR":    "Güneydoğu Avrupa'da çok sayıda ülkeyi barındıran coğrafi bölge.",
    ]
}
