import Foundation

extension WordList {

    // MARK: - Words

    static let gunlukWords: [WordEntry] = [
        WordEntry(word: "ANAHTAR", category: "Günlük"),
        WordEntry(word: "AYNA", category: "Günlük"),
        WordEntry(word: "BARDAK", category: "Günlük"),
        WordEntry(word: "BIÇAK", category: "Günlük"),
        WordEntry(word: "BUZDOLABI", category: "Günlük"),
        WordEntry(word: "ÇATAL", category: "Günlük"),
        WordEntry(word: "ÇAYDANLIK", category: "Günlük"),
        WordEntry(word: "ÇÖP", category: "Günlük"),
        WordEntry(word: "CÜZDAN",  category: "Günlük"),
        WordEntry(word: "DETERJAN", category: "Günlük"),
        WordEntry(word: "DOLAP",   category: "Günlük"),
        WordEntry(word: "DİŞFIRÇASI", category: "Günlük"),
        WordEntry(word: "FIRÇA", category: "Günlük"),
        WordEntry(word: "FIRIN", category: "Günlük"),
        WordEntry(word: "HALI", category: "Günlük"),
        WordEntry(word: "HAVLU", category: "Günlük"),
        WordEntry(word: "KAŞIK", category: "Günlük"),
        WordEntry(word: "KAPI",  category: "Günlük"),
        WordEntry(word: "KLİMA", category: "Günlük"),
        WordEntry(word: "ÇAKMAK", category: "Günlük"),
        WordEntry(word: "KOLTUK", category: "Günlük"),
        WordEntry(word: "LAMBA", category: "Günlük"),
        WordEntry(word: "MASA", category: "Günlük"),
        WordEntry(word: "MİKRODALGA", category: "Günlük"),
        WordEntry(word: "MİKSER", category: "Günlük"),
        WordEntry(word: "PENCERE", category: "Günlük"),
        WordEntry(word: "PERDE", category: "Günlük"),
        WordEntry(word: "SABUN", category: "Günlük"),
        WordEntry(word: "SANDALYE", category: "Günlük"),
        WordEntry(word: "SÜPÜRGE", category: "Günlük"),
        WordEntry(word: "ŞAMPUAN", category: "Günlük"),
        WordEntry(word: "ŞEMSİYE", category: "Günlük"),
        WordEntry(word: "TABAK", category: "Günlük"),
        WordEntry(word: "TARAK", category: "Günlük"),
        WordEntry(word: "TELEVİZYON", category: "Günlük"),
        WordEntry(word: "TERLİK", category: "Günlük"),
        WordEntry(word: "YASTIK", category: "Günlük"),
        WordEntry(word: "YORGAN", category: "Günlük"),
    ]

    // MARK: - Hints

    static let gunlukHints: [String: String] = [
        "ANAHTAR":      "Kilidi açmak veya kapatmak için kullanılan küçük metal alet.",
        "AYNA":         "Yüzeyi yansıtıcı, görüntünüzü görmek için kullandığınız nesne.",
        "BARDAK":       "İçecek içmek için kullanılan cam, plastik ya da seramik kap.",
        "BIÇAK":        "Yiyecek kesmek için kullanılan, keskin ağızlı mutfak aleti.",
        "BUZDOLABI":    "Yiyecekleri soğuk tutarak taze kalmasını sağlayan büyük elektrikli cihaz.",
        "ÇATAL":        "Yemek yerken yiyeceği saplamak ve tutmak için kullanılan dişli alet.",
        "ÇAYDANLIK":    "Su kaynatmak ve çay demlendirmek için kullanılan metal ya da porselen kap.",
        "ÇÖP":          "Atık ve istenmeyen maddelerin toplandığı, atılan şey.",
        "CÜZDAN":       "Para, kart ve kimlik belgelerini taşımak için kullanılan küçük deri ya da kumaş kılıf.",
        "DETERJAN":     "Bulaşık ya da çamaşır temizlemek için kullanılan kimyasal temizleyici.",
        "DOLAP":        "Giysi, eşya veya mutfak malzemeleri saklamak için kullanılan kapaklı mobilya.",
        "DİŞFIRÇASI":   "Dişleri temizlemek için sabah ve akşam düzenli kullanılan hijyen aleti.",
        "FIRÇA":        "Boyama ya da temizlik için kıl veya sentetik liflerden yapılmış alet.",
        "FIRIN":        "Yiyecekleri pişirmek için kullanılan ısıtmalı mutfak cihazı.",
        "HALI":         "Zemine serilen, dokuma ya da makine yapımı yer döşemesi.",
        "HAVLU":        "Yüz ve vücudu kurulamak için kullanılan yumuşak tekstil ürünü.",
        "KAŞIK":        "Çorba içmek ve yiyecek almak için kullanılan, yuvarlak uçlu yemek aleti.",
        "KAPI":         "Odaya ya da binaya giriş çıkışı sağlayan, açılıp kapanan bölme.",
        "KLİMA":        "Ortamın sıcaklık ve nemini ayarlayan soğutma ya da ısıtma cihazı.",
        "ÇAKMAK":       "Gaz veya benzin ile alev oluşturan, ateşlemek için kullanılan taşınabilir alet.",
        "KOLTUK":       "Sırtlıklı ve kolçaklı, rahatça oturmak için tasarlanmış mobilya.",
        "LAMBA":        "Elektrik ya da yakıt ile ışık üreten aydınlatma aleti.",
        "MASA":         "Üzerine eşya koyulan ya da üstünde çalışılan, düz yüzeyli mobilya.",
        "MİKRODALGA":   "Mikrodalga radyasyonuyla yiyecekleri kısa sürede ısıtan mutfak cihazı.",
        "MİKSER":       "Malzemeleri karıştırmak veya çırpmak için kullanılan elektrikli mutfak aleti.",
        "PENCERE":      "Dışarısı ile içerisi arasında ışık ve hava geçişini sağlayan, camlı açıklık.",
        "PERDE":        "Pencere ya da sahneyi örtmek için kullanılan kumaş örtü.",
        "SABUN":        "El ve vücudu temizlemek için kullanılan, suyla köpüren hijyen ürünü.",
        "SANDALYE":     "Sırtlık ve dört bacaktan oluşan, kolçaksız oturma mobilyası.",
        "SÜPÜRGE":      "Yerdeki toz ve kiri süpürerek toplamak için kullanılan temizlik aleti.",
        "ŞAMPUAN":      "Saçı yıkamak ve bakımını yapmak için kullanılan sıvı ürün.",
        "ŞEMSİYE":      "Yağmur ya da güneşten korunmak için açılıp kapanan taşınabilir örtü.",
        "TABAK":        "Yemek servis etmek ve yemek için kullanılan, genellikle yuvarlak düz kap.",
        "TARAK":        "Saçı düzenlemek ve taramak için kullanılan, dişli plastik ya da metal alet.",
        "TELEVİZYON":   "Görüntü ve ses yayını alan, haber ve eğlence için izlenen elektronik ekran.",
        "TERLİK":       "Ev içinde rahatça giyilen, kolay çıkarılan yumuşak ayak giysisi.",
        "YASTIK":       "Uyurken başın altına konan, yumuşak dolgulu uyku aksesuarı.",
        "YORGAN":       "Soğuk gecelerde üste örtülen, dolgulu ve kumaş kaplı ısıtıcı örtü.",
    ]
}
