import Foundation

extension WordList {

    // MARK: - Words

    static let mitolojiWords: [WordEntry] = [
        WordEntry(word: "AFRODİT", category: "Mitoloji"),
        WordEntry(word: "AKHİLLES", category: "Mitoloji"),
        WordEntry(word: "APOLLO", category: "Mitoloji"),
        WordEntry(word: "ARES", category: "Mitoloji"),
        WordEntry(word: "ARTEMİS", category: "Mitoloji"),
        WordEntry(word: "ATHENA", category: "Mitoloji"),
        WordEntry(word: "DAEDALUS", category: "Mitoloji"),
        WordEntry(word: "DEMETER", category: "Mitoloji"),
        WordEntry(word: "DİONYSOS", category: "Mitoloji"),
        WordEntry(word: "EROS", category: "Mitoloji"),
        WordEntry(word: "HADES", category: "Mitoloji"),
        WordEntry(word: "HECATE", category: "Mitoloji"),
        WordEntry(word: "HEPHAISTOS", category: "Mitoloji"),
        WordEntry(word: "HERA", category: "Mitoloji"),
        WordEntry(word: "HERAKLES", category: "Mitoloji"),
        WordEntry(word: "HESTİA", category: "Mitoloji"),
        WordEntry(word: "HELİOS", category: "Mitoloji"),
        WordEntry(word: "HERMES", category: "Mitoloji"),
        WordEntry(word: "İKARUS", category: "Mitoloji"),
        WordEntry(word: "KRONOS", category: "Mitoloji"),
        WordEntry(word: "LABİRENT", category: "Mitoloji"),
        WordEntry(word: "MEDUSA", category: "Mitoloji"),
        WordEntry(word: "MİNOTAUR", category: "Mitoloji"),
        WordEntry(word: "NARKİSSOS", category: "Mitoloji"),
        WordEntry(word: "ODYSSEUS", category: "Mitoloji"),
        WordEntry(word: "PEGASUS", category: "Mitoloji"),
        WordEntry(word: "PERSEFONE", category: "Mitoloji"),
        WordEntry(word: "PERSEUS", category: "Mitoloji"),
        WordEntry(word: "POSEİDON", category: "Mitoloji"),
        WordEntry(word: "SELENE", category: "Mitoloji"),
        WordEntry(word: "SFENKS", category: "Mitoloji"),
        WordEntry(word: "THESEUS", category: "Mitoloji"),
        WordEntry(word: "TİTAN", category: "Mitoloji"),
        WordEntry(word: "TRUVA", category: "Mitoloji"),
        WordEntry(word: "ZEUS", category: "Mitoloji"),
    ]

    // MARK: - Hints

    static let mitolojiHints: [String: String] = [
        "AFRODIT":      "Yunan mitolojisinde aşk ve güzellik tanrıçası.",
        "APOLLON":      "Güneş, müzik ve kehanete hükmeden Yunan tanrısı.",
        "ARES":         "Savaş ve şiddetin Yunan mitolojisindeki tanrısı.",
        "ATİNA":        "Yunan mitolojisinde bilgelik ve savaş stratejisi tanrıçası.",
        "DİONİSOS":     "Şarap ve neşenin Yunan tanrısı, tiyatronun koruyucusu.",
        "HEFAİSTOS":    "Ateş ve demirciliğin Yunan mitolojisindeki tanrısı.",
        "HERMES":       "Haberciler, tüccarlar ve yolcuların kanatlı sandallı Yunan tanrısı.",
        "HERA":         "Zeus'un eşi, evlilik ve aile koruyucusu Yunan tanrıçası.",
        "KRONOS":       "Titanların lideri, Yunan mitolojisinde zamanı temsil eder.",
        "MEDUSA":       "Bakışı taşa çeviren, saçları yılan olan Yunan mitoloji canavarı.",
        "MİNOTAUR":     "Girit labirentinde yaşayan, yarı insan yarı boğa varlık.",
        "PERSEFONİ":    "Yeraltı dünyasının kraliçesi, Demeter'in kızı.",
        "POSEYDON":     "Denizlere, depremlere ve fırtınalara hükmeden Yunan tanrısı.",
        "PROMETHEUS":   "İnsanlara ateşi veren, cezası olarak bağlanan Yunan titan kahraman.",
        "ZEFİR":        "Batı rüzgarını temsil eden Yunan mitolojisi tanrısı.",
        "ZEUS":         "Yunan mitolojisinin en güçlü tanrısı, Olimpos'un hükümdarı.",
        "HERAKLİS":     "On iki büyük görevi tamamlayan Yunan mitolojisinin en güçlü kahramanı.",
        "ODYSSEUS":     "Truva Savaşı'ndan sonra uzun yolculuğa çıkan kurnaz Yunan kahraman.",
        "AKİLLES":      "Topuğu dışında kırılmaz olan, en büyük Yunan savaşçısı.",
        "KIBELE":       "Anadolu'nun en eski tanrıçası, bereket ve doğanın simgesi.",
        "AFRODİT":      "Yunan mitolojisinde aşk, güzellik ve arzunun tanrıçası.",
        "AKHİLLES":     "Topuğu dışında yenilmez olan, Truva'nın en büyük Yunan savaşçısı.",
        "APOLLO":       "Güneş, müzik, şiir ve kehanetin parlak Yunan tanrısı.",
        "ARTEMİS":      "Av ve Ay'ın tanrıçası, Apollo'nun ikiz kız kardeşi.",
        "ATHENA":       "Bilgelik, adalet ve savaş stratejisinin Yunan tanrıçası.",
        "DAEDALUS":     "Girit labirentini inşa eden, oğlu İkaros ile uçmaya çalışan usta mimar.",
        "DEMETER":      "Tahıl ve hasadın tanrıçası, Persephone'nin annesi.",
        "DİONYSOS":     "Şarap, şenlik ve tiyatronun Yunan tanrısı.",
        "EROS":         "Aşk ve arzunun Yunan tanrısı, kanatlı okçu çocuk.",
        "HADES":        "Yeraltı dünyasını yöneten, ölülerin tanrısı.",
        "HECATE":       "Büyü, gece ve kavşakların gizemli Yunan tanrıçası.",
        "HEPHAISTOS":   "Ateş ve demirciliğin çirkin ama yetenekli Yunan tanrısı.",
        "HERAKLES":     "On iki büyük görevi tamamlayan Yunan mitolojisinin en güçlü kahramanı.",
        "HESTİA":       "Ocak ateşi ve ev hayatının sessiz Yunan tanrıçası.",
        "HELİOS":       "Güneş arabası süren, gökyüzünü her gün aşan ışık tanrısı.",
        "İKARUS":       "Babası Daedalus'un yaptığı wax kanatlı uçarken Güneş'e yaklaşıp düşen genç.",
        "LABİRENT":     "Minotaur'un hapsedildiği, çıkışı neredeyse imkânsız karmaşık yapı.",
        "NARKİSSOS":    "Kendi yansımasına âşık olup eriyen, narsisizmin simgesi Yunan genci.",
        "PEGASUS":      "Göksel beyaz kanatlı at, Perseus ve Bellerophon'un bineği.",
        "PERSEFONE":    "Yılın bir bölümünü yeraltında geçiren, mevsimlerin simgesi tanrıça.",
        "PERSEUS":      "Medusa'yı öldüren, kahraman Yunan savaşçısı.",
        "POSEİDON":     "Denizlerin, fırtınaların ve depremlerin güçlü Yunan tanrısı.",
        "SELENE":       "Ay'ı temsil eden, gece gökyüzünde araba süren tanrıça.",
        "SFENKS":       "Yanıtlanamayan bulmacalar soran, yarı insan yarı aslan mitolojik varlık.",
        "THESEUS":      "Labirente girip Minotaur'u öldüren Atina'nın kahraman prensi.",
        "TİTAN":        "Zeus öncesi dünyaya hükmeden, dev güçlü tanrısal ırkın genel adı.",
        "TRUVA":        "On yıl süren ünlü savaşa sahne olan, ağaç at hilesini barındıran antik şehir.",
    ]
}
