import Foundation

extension WordList {

    // MARK: - Words

    static let teknolojiWords: [WordEntry] = [
        WordEntry(word: "ALGORİTMA", category: "Teknoloji"),
        WordEntry(word: "ANAKART", category: "Teknoloji"),
        WordEntry(word: "ANALİTİK", category: "Teknoloji"),
        WordEntry(word: "ARAYÜZ", category: "Teknoloji"),
        WordEntry(word: "BATARYA", category: "Teknoloji"),
        WordEntry(word: "BELLEK", category: "Teknoloji"),
        WordEntry(word: "BİLGİSAYAR", category: "Teknoloji"),
        WordEntry(word: "BLOK ZİNCİR", category: "Teknoloji"),
        WordEntry(word: "BLUETOOTH", category: "Teknoloji"),
        WordEntry(word: "BULUT", category: "Teknoloji"),
        WordEntry(word: "DİJİTAL", category: "Teknoloji"),
        WordEntry(word: "DONANIM", category: "Teknoloji"),
        WordEntry(word: "DRONE", category: "Teknoloji"),
        WordEntry(word: "EKRAN", category: "Teknoloji"),
        WordEntry(word: "EKRAN KARTI", category: "Teknoloji"),
        WordEntry(word: "GELİŞTİRİCİ", category: "Teknoloji"),
        WordEntry(word: "GÜVENLİK", category: "Teknoloji"),
        WordEntry(word: "HARD DİSK", category: "Teknoloji"),
        WordEntry(word: "HOLOGRAM", category: "Teknoloji"),
        WordEntry(word: "İNTERNET", category: "Teknoloji"),
        WordEntry(word: "İŞLEMCİ", category: "Teknoloji"),
        WordEntry(word: "KABLOSUZ", category: "Teknoloji"),
        WordEntry(word: "KAMERA", category: "Teknoloji"),
        WordEntry(word: "KLAVYE", category: "Teknoloji"),
        WordEntry(word: "KRİPTO", category: "Teknoloji"),
        WordEntry(word: "LAZER", category: "Teknoloji"),
        WordEntry(word: "METAVERSE", category: "Teknoloji"),
        WordEntry(word: "MODEM", category: "Teknoloji"),
        WordEntry(word: "MONİTÖR", category: "Teknoloji"),
        WordEntry(word: "ÖNBELLEK", category: "Teknoloji"),
        WordEntry(word: "OTOMASYON", category: "Teknoloji"),
        WordEntry(word: "PLATFORM", category: "Teknoloji"),
        WordEntry(word: "PODCAST", category: "Teknoloji"),
        WordEntry(word: "PROGRAMLAMA", category: "Teknoloji"),
        WordEntry(word: "PROTOKOL", category: "Teknoloji"),
        WordEntry(word: "ROBOT", category: "Teknoloji"),
        WordEntry(word: "SANAL", category: "Teknoloji"),
        WordEntry(word: "SENSÖR", category: "Teknoloji"),
        WordEntry(word: "SİBER", category: "Teknoloji"),
        WordEntry(word: "STREAMING", category: "Teknoloji"),
        WordEntry(word: "SUNUCU", category: "Teknoloji"),
        WordEntry(word: "ŞİFRE", category: "Teknoloji"),
        WordEntry(word: "ŞİFRELEME", category: "Teknoloji"),
        WordEntry(word: "TABLET", category: "Teknoloji"),
        WordEntry(word: "UYGULAMA", category: "Teknoloji"),
        WordEntry(word: "UYDU", category: "Teknoloji"),
        WordEntry(word: "VERİ", category: "Teknoloji"),
        WordEntry(word: "VERİTABANI", category: "Teknoloji"),
        WordEntry(word: "YAPAY ZEKA", category: "Teknoloji"),
        WordEntry(word: "YAZICI", category: "Teknoloji"),
        WordEntry(word: "YAZILIM", category: "Teknoloji"),
        WordEntry(word: "YAZILIMCI", category: "Teknoloji"),
    ]

    // MARK: - Hints

    static let teknolojiHints: [String: String] = [
        "ALGORİTMA":    "Bir problemi çözmek için adım adım izlenen yönerge dizisi.",
        "ANAKART":      "Bilgisayarın tüm bileşenlerini birbirine bağlayan ana devre kartı.",
        "ARAYÜZ":       "Kullanıcı ile yazılım arasındaki etkileşim katmanı.",
        "BATARYA":      "Cihazlara taşınabilir elektrik sağlayan şarj edilebilir güç kaynağı.",
        "BELLEK":       "Verilerin geçici olarak saklandığı, işlemcinin hızla eriştiği depo.",
        "BİLGİSAYAR":   "Veri işleyen, depolayan ve çıktı üreten elektronik cihaz.",
        "BLOK ZİNCİR":  "İşlemlerin dağıtık ağda güvenle saklandığı dijital kayıt sistemi.",
        "BLUETOOTH":    "Kısa mesafede cihazlar arası kablosuz veri aktarım teknolojisi.",
        "BULUT":        "İnternette veri depolama ve işleme altyapısı.",
        "DİJİTAL":      "Bilginin ikili (0 ve 1) formatında temsil edildiği elektronik sistem.",
        "DONANIM":      "Bilgisayarın fiziksel parçaları; işlemci, ekran, klavye gibi.",
        "DRONE":        "Uzaktan kumandalı, havada uçan insansız hava aracı.",
        "EKRAN":        "Görüntünün gösterildiği elektronik yüzey.",
        "EKRAN KARTI":  "Grafik işlemleri yapan, monitöre görüntü gönderen bilgisayar bileşeni.",
        "GELİŞTİRİCİ":  "Yazılım ve uygulama yazan, hata gideren bilgisayar uzmanı.",
        "HARD DİSK":    "Verilerin kalıcı olarak saklandığı manyetik depolama ünitesi.",
        "HOLOGRAM":     "Lazerle oluşturulan üç boyutlu ışık imgesi.",
        "İNTERNET":     "Dünya genelinde bilgisayarları birbirine bağlayan küresel ağ.",
        "İŞLEMCİ":      "Bilgisayarın beyni, tüm hesaplama işlemlerini yapan çip.",
        "KABLOSUZ":     "Fiziksel kablo olmaksızın elektromanyetik dalgayla çalışan iletişim.",
        "KAMERA":       "Işığı algılayan lensiyle fotoğraf veya video kaydeden cihaz.",
        "KLAVYE":       "Karakterleri bilgisayara girmek için kullanılan tuş takımı.",
        "KRİPTO":       "Matematiksel şifreleme yöntemleriyle korunan dijital para birimi.",
        "LAZER":        "Tek renk ışık demetleri üreten yüksek yoğunluklu ışık kaynağı.",
        "METAVERSE":    "Sanal gerçeklik ve internet arasında oluşan dijital evren kavramı.",
        "MODEM":        "İnternet bağlantısını sağlayan ağ cihazı.",
        "MONİTÖR":      "Bilgisayarın görüntü çıktısını gösteren ekran birimi.",
        "ÖNBELLEK":     "Sık erişilen verinin hızlı ulaşılabilmesi için ayrılan küçük bellek alanı.",
        "OTOMASYON":    "İnsan müdahalesini azaltarak sistemlerin otomatik çalıştırılması.",
        "PLATFORM":     "Uygulama ve hizmetlerin üzerine kurulduğu yazılım altyapısı.",
        "PODCAST":      "İnternet üzerinden abonelikle dinlenen ses yayını formatı.",
        "PROGRAMLAMA":  "Bilgisayara belirli görevleri yaptırmak için kod yazma süreci.",
        "PROTOKOL":     "Ağ iletişiminde cihazların uyması gereken kurallar bütünü.",
        "ROBOT":        "Görevleri otomatik olarak yapan, programlanabilen makine.",
        "SANAL":        "Gerçek olmayan, bilgisayar ortamında simüle edilen kavram veya ortam.",
        "SENSÖR":       "Fiziksel büyüklükleri algılayıp elektrik sinyaline çeviren cihaz.",
        "SİBER":        "İnternet veya bilgisayar ağlarıyla ilgili olan.",
        "STREAMING":    "İçeriklerin indirilmeden, anlık olarak izlenip dinlenmesi.",
        "SUNUCU":       "İnternet üzerinde hizmet sunan güçlü bilgisayar sistemi.",
        "ŞİFRE":        "Yetkisiz erişimi engellemek için kullanılan gizli karakter dizisi.",
        "ŞİFRELEME":    "Verileri yetkisiz erişime karşı korumak için dönüştürme işlemi.",
        "TABLET":       "Dokunmatik ekranlı, taşınabilir düz bilgisayar.",
        "UYGULAMA":     "Mobil ya da masaüstünde belirli işlevi yerine getiren yazılım.",
        "UYDU":         "Yerkürenin etrafında dönen, iletişim veya gözlem yapan uzay aracı.",
        "VERİ":         "İşlenmek üzere toplanan ham bilgi ya da rakamlar.",
        "VERİTABANI":   "Verilerin düzenli biçimde saklandığı ve sorgulandığı sistem.",
        "YAPAY ZEKA":   "Makinelerin insan gibi öğrenip karar verebildiği teknoloji alanı.",
        "YAZICI":       "Dijital belgeleri kağıda basan çevre birimi.",
        "YAZILIM":      "Bilgisayara görev tanımlayan program ve kod bütünü.",
    ]
}
