import Foundation

extension WordList {

    // MARK: - Words

    static let sehirlerWords: [WordEntry] = [
        WordEntry(word: "ADANA", category: "Şehirler"),
        WordEntry(word: "ADIYAMAN", category: "Şehirler"),
        WordEntry(word: "AFYONKARAHİSAR", category: "Şehirler"),
        WordEntry(word: "AĞRI", category: "Şehirler"),
        WordEntry(word: "AMASYA", category: "Şehirler"),
        WordEntry(word: "ANKARA", category: "Şehirler"),
        WordEntry(word: "ANTALYA", category: "Şehirler"),
        WordEntry(word: "ARTVİN", category: "Şehirler"),
        WordEntry(word: "AYDIN", category: "Şehirler"),
        WordEntry(word: "BALIKESİR", category: "Şehirler"),
        WordEntry(word: "BİLECİK", category: "Şehirler"),
        WordEntry(word: "BİNGÖL", category: "Şehirler"),
        WordEntry(word: "BİTLİS", category: "Şehirler"),
        WordEntry(word: "BOLU", category: "Şehirler"),
        WordEntry(word: "BURDUR", category: "Şehirler"),
        WordEntry(word: "BURSA", category: "Şehirler"),
        WordEntry(word: "ÇANAKKALE", category: "Şehirler"),
        WordEntry(word: "ÇANKIRI", category: "Şehirler"),
        WordEntry(word: "ÇORUM", category: "Şehirler"),
        WordEntry(word: "DENİZLİ", category: "Şehirler"),
        WordEntry(word: "DİYARBAKIR", category: "Şehirler"),
        WordEntry(word: "EDİRNE", category: "Şehirler"),
        WordEntry(word: "ELAZIĞ", category: "Şehirler"),
        WordEntry(word: "ERZİNCAN", category: "Şehirler"),
        WordEntry(word: "ERZURUM", category: "Şehirler"),
        WordEntry(word: "ESKİŞEHİR", category: "Şehirler"),
        WordEntry(word: "GAZİANTEP", category: "Şehirler"),
        WordEntry(word: "GİRESUN", category: "Şehirler"),
        WordEntry(word: "GÜMÜŞHANE", category: "Şehirler"),
        WordEntry(word: "HAKKARİ", category: "Şehirler"),
        WordEntry(word: "HATAY", category: "Şehirler"),
        WordEntry(word: "ISPARTA", category: "Şehirler"),
        WordEntry(word: "MERSİN", category: "Şehirler"),
        WordEntry(word: "İSTANBUL", category: "Şehirler"),
        WordEntry(word: "İZMİR", category: "Şehirler"),
        WordEntry(word: "KARS", category: "Şehirler"),
        WordEntry(word: "KASTAMONU", category: "Şehirler"),
        WordEntry(word: "KAYSERİ", category: "Şehirler"),
        WordEntry(word: "KIRKLARELİ", category: "Şehirler"),
        WordEntry(word: "KIRŞEHİR", category: "Şehirler"),
        WordEntry(word: "KOCAELİ", category: "Şehirler"),
        WordEntry(word: "KONYA", category: "Şehirler"),
        WordEntry(word: "KÜTAHYA", category: "Şehirler"),
        WordEntry(word: "MALATYA", category: "Şehirler"),
        WordEntry(word: "MANİSA", category: "Şehirler"),
        WordEntry(word: "KAHRAMANMARAŞ", category: "Şehirler"),
        WordEntry(word: "MARDİN", category: "Şehirler"),
        WordEntry(word: "MUĞLA", category: "Şehirler"),
        WordEntry(word: "MUŞ", category: "Şehirler"),
        WordEntry(word: "NEVŞEHİR", category: "Şehirler"),
        WordEntry(word: "NİĞDE", category: "Şehirler"),
        WordEntry(word: "ORDU", category: "Şehirler"),
        WordEntry(word: "RİZE", category: "Şehirler"),
        WordEntry(word: "SAKARYA", category: "Şehirler"),
        WordEntry(word: "SAMSUN", category: "Şehirler"),
        WordEntry(word: "SİİRT", category: "Şehirler"),
        WordEntry(word: "SİNOP", category: "Şehirler"),
        WordEntry(word: "SİVAS", category: "Şehirler"),
        WordEntry(word: "TEKİRDAĞ", category: "Şehirler"),
        WordEntry(word: "TOKAT", category: "Şehirler"),
        WordEntry(word: "TRABZON", category: "Şehirler"),
        WordEntry(word: "TUNCELİ", category: "Şehirler"),
        WordEntry(word: "ŞANLIURFA", category: "Şehirler"),
        WordEntry(word: "UŞAK", category: "Şehirler"),
        WordEntry(word: "VAN", category: "Şehirler"),
        WordEntry(word: "YOZGAT", category: "Şehirler"),
        WordEntry(word: "ZONGULDAK", category: "Şehirler"),
        WordEntry(word: "AKSARAY", category: "Şehirler"),
        WordEntry(word: "BAYBURT", category: "Şehirler"),
        WordEntry(word: "KARAMAN", category: "Şehirler"),
        WordEntry(word: "KIRIKKALE", category: "Şehirler"),
        WordEntry(word: "BATMAN", category: "Şehirler"),
        WordEntry(word: "ŞIRNAK", category: "Şehirler"),
        WordEntry(word: "BARTIN", category: "Şehirler"),
        WordEntry(word: "ARDAHAN", category: "Şehirler"),
        WordEntry(word: "IĞDIR", category: "Şehirler"),
        WordEntry(word: "YALOVA", category: "Şehirler"),
        WordEntry(word: "KARABÜK", category: "Şehirler"),
        WordEntry(word: "KİLİS", category: "Şehirler"),
        WordEntry(word: "OSMANİYE", category: "Şehirler"),
        WordEntry(word: "DÜZCE", category: "Şehirler"),
    ]

    // MARK: - Hints

    static let sehirlerHints: [String: String] = [
        "ADANA":        "Türkiye'nin güneyinde, Seyhan Nehri kenarında kurulu büyük şehir.",
        "ADIYAMAN":     "Nemrut Dağı tümülüsüyle ünlü, Güneydoğu Anadolu şehri.",
        "AFYONKARAHİSAR": "Kaymağı, sucuğu ve haşhaşıyla tanınan İç Anadolu şehri.",
        "AĞRI":         "Türkiye'nin en yüksek dağına, Ağrı Dağı'na ev sahipliği yapan şehir.",
        "AMASYA":       "Pontos krallığının başkenti, elma ve tarihi konakları ile bilinen şehir.",
        "ANKARA":       "Türkiye Cumhuriyeti'nin başkenti, ülkenin en kalabalık ikinci şehri.",
        "ANTALYA":      "Türkiye'nin turizm başkenti sayılan, Akdeniz kıyısı şehir.",
        "ARTVİN":       "Karadeniz ile Gürcistan sınırına yakın, dağlık ve yeşil Doğu Karadeniz ili.",
        "AYDIN":        "İncir üretimi ve tarihi Efes harabeleriyle ünlü Ege ili.",
        "BALIKESİR":    "Ege ile Marmara arasında köprü konumunda, sanayi ve tarım şehri.",
        "BURSA":        "Osmanlı'nın ilk başkenti, Uludağ'a yakın sanayi ve kültür kenti.",
        "ÇANAKKALE":    "1915 deniz savaşıyla tarihe geçen, boğaz kıyısındaki şehir.",
        "DENİZLİ":      "Pamukkale travertenlerinin hemen yanında konumlanan Ege şehri.",
        "DİYARBAKIR":   "Güneydoğu Anadolu'da tarihi siyah bazalt surlarıyla ünlü şehir.",
        "EDİRNE":       "Osmanlı'nın üç başkentinden biri, Selimiye Camii ile ünlü.",
        "ELAZIĞ":       "Hazar Gölü kıyısındaki Doğu Anadolu şehri.",
        "ERZİNCAN":     "Doğu Anadolu'da tulum peyniri ve kemah kalesiyle tanınan şehir.",
        "ERZURUM":      "Doğu Anadolu'nun en soğuk ve yüksek şehirlerinden biri.",
        "ESKİŞEHİR":    "Genç nüfusuyla, Porsuk Çayı kıyısında kurulu, üniversite şehri.",
        "GAZİANTEP":    "Fıstıklı baklavası ve gastronomiyle dünyaca ünlü Türk şehri.",
        "GİRESUN":      "Fındık üretiminin merkezi, Karadeniz kıyısında şirin il.",
        "GÜMÜŞHANE":    "Doğu Karadeniz'de, eski gümüş madeni bölgesinde kurulu şehir.",
        "HAKKARİ":      "Türkiye'nin en dağlık ve ulaşılması güç doğu sınırı ilidir.",
        "HATAY":        "Suriye sınırında, çok kültürlü yapısıyla tanınan antik Antakya şehri.",
        "ISPARTA":      "Gül yağı üretiminde dünyaca ünlü, göl şehirleri bölgesindeki il.",
        "İSTANBUL":     "İki kıtaya yayılan, Türkiye'nin en kalabalık ve tarihi şehri.",
        "İZMİR":        "Ege kıyısında körfez kenarında kurulu, Türkiye'nin üçüncü büyük şehri.",
        "KARS":         "Doğu Anadolu'nun soğuk şehri, Ani harabeleri ve kaşar peyniriyle ünlü.",
        "KASTAMONU":    "Batı Karadeniz'de, yöresel pastırmasıyla tanınan il.",
        "KAYSERİ":      "Erciyes Dağı eteklerinde, sucuğu ve pastırmasıyla ünlü İç Anadolu şehri.",
        "KOCAELİ":      "Marmara kıyısındaki sanayi kenti, eski adı İzmit.",
        "KONYA":        "Mevlana'nın şehri, Türkiye'nin en büyük yüzölçümlü şehri.",
        "KÜTAHYA":      "Çini ve seramik sanatının merkezi, tarihi kaleleriyle bilinen il.",
        "MALATYA":      "Kayısı üretiminde Türkiye'nin başkenti sayılan Doğu Anadolu ili.",
        "MANİSA":       "Mesir Macunu festivaliyle ünlü, Ege'nin tarihi şehri.",
        "KAHRAMANMARAŞ":"Maraş dondurmasının çok özel çekilme yöntemiyle ünlü şehir.",
        "MARDİN":       "Taş yapılarıyla dikkat çeken, Mezopotamya ovasına bakan tarihi şehir.",
        "MUĞLA":        "Bodrum ve Marmaris gibi tatil beldeleriyle Ege ve Akdeniz'in gözdesi.",
        "NEVŞEHİR":     "Kapadokya bölgesinin merkezi, peri bacaları ve yer altı şehirleriyle ünlü.",
        "ORDU":         "Fındık bahçeleri ve Boztepe'siyle Karadeniz kıyısında bir il.",
        "RİZE":         "Çay üretiminin kalbi, yemyeşil dağları olan Doğu Karadeniz şehri.",
        "SAMSUN":       "Karadeniz kıyısında, Atatürk'ün milli mücadeleye başladığı şehir.",
        "SİVAS":        "1919 kongresine ev sahipliği yapan, İç Anadolu'nun köklü şehri.",
        "TEKİRDAĞ":     "Marmara kıyısında, köftesi ve rakısıyla ünlü Trakya şehri.",
        "TOKAT":        "Türkiye'nin şeker pancarı ve Horozlu ekmekle bilinen Karadeniz ili.",
        "TRABZON":      "Karadeniz'in incisi, sarp dağlar ve yemyeşil ormanlarla çevrili.",
        "VAN":          "Van Gölü kıyısındaki doğu şehri, Van kedisi ve otlu peyniriyle ünlü.",
        "YOZGAT":       "İç Anadolu'nun en az kalabalık illerinden, tahıl tarımıyla tanınan il.",
        "ZONGULDAK":    "Türkiye'nin kömür madenciliğinin başkenti, Batı Karadeniz kıyısı.",
        "KARABÜK":      "Türkiye'nin ilk büyük demir-çelik tesisine ev sahipliği yapan Karadeniz ili.",
        "BATMAN":       "Petrol üretimiyle tanınan, güneydoğu Türkiye'nin genç şehri.",
        "DÜZCE":        "1999 depreminden sonra yeniden yapılanan Batı Karadeniz şehri.",
        "MERSİN":       "Akdeniz kıyısında, Türkiye'nin en büyük limanlarından birine sahip şehir.",
    ]
}
