import Foundation

extension WordList {

    // MARK: - Words

    static let bilimPlusWords: [WordEntry] = [
        WordEntry(word: "ALGORİTMA",   category: "Bilim+"),
        WordEntry(word: "AŞIRELİTAY",  category: "Bilim+"),
        WordEntry(word: "ANTİBİYOTİK", category: "Bilim+"),
        WordEntry(word: "ATOM",        category: "Bilim+"),
        WordEntry(word: "BAKTERİ",     category: "Bilim+"),
        WordEntry(word: "BİLİŞİM",     category: "Bilim+"),
        WordEntry(word: "BİYOLOJİ",    category: "Bilim+"),
        WordEntry(word: "BLOKZİNCİR",  category: "Bilim+"),
        WordEntry(word: "BULUT",       category: "Bilim+"),
        WordEntry(word: "DENKLEM",     category: "Bilim+"),
        WordEntry(word: "DERİÖĞRENME", category: "Bilim+"),
        WordEntry(word: "DEVRE",       category: "Bilim+"),
        WordEntry(word: "DNA",         category: "Bilim+"),
        WordEntry(word: "ELEKTRON",    category: "Bilim+"),
        WordEntry(word: "ENZİM",       category: "Bilim+"),
        WordEntry(word: "EVRİM",       category: "Bilim+"),
        WordEntry(word: "FİZİK",       category: "Bilim+"),
        WordEntry(word: "FOTON",       category: "Bilim+"),
        WordEntry(word: "GENETİK",     category: "Bilim+"),
        WordEntry(word: "GRAVİTON",    category: "Bilim+"),
        WordEntry(word: "HİDROJEN",    category: "Bilim+"),
        WordEntry(word: "HİPOTEZ",     category: "Bilim+"),
        WordEntry(word: "HUBBLE",      category: "Bilim+"),
        WordEntry(word: "İSTATİSTİK",  category: "Bilim+"),
        WordEntry(word: "KAOS",        category: "Bilim+"),
        WordEntry(word: "KİMYA",       category: "Bilim+"),
        WordEntry(word: "KLON",        category: "Bilim+"),
        WordEntry(word: "KROMOZOM",    category: "Bilim+"),
        WordEntry(word: "KUANTUM",     category: "Bilim+"),
        WordEntry(word: "LABORATUVAR", category: "Bilim+"),
        WordEntry(word: "LİTYUM",      category: "Bilim+"),
        WordEntry(word: "MATEMATİK",   category: "Bilim+"),
        WordEntry(word: "MİKROSKOP",   category: "Bilim+"),
        WordEntry(word: "MOLEKÜL",     category: "Bilim+"),
        WordEntry(word: "NANOTEKNOLOJİ", category: "Bilim+"),
        WordEntry(word: "NEBULA",      category: "Bilim+"),
        WordEntry(word: "NÖROZON",     category: "Bilim+"),
        WordEntry(word: "OKSİJEN",     category: "Bilim+"),
        WordEntry(word: "ORBİTAL",     category: "Bilim+"),
        WordEntry(word: "PANDEMİ",     category: "Bilim+"),
        WordEntry(word: "PARÇACIK",    category: "Bilim+"),
        WordEntry(word: "PROTON",      category: "Bilim+"),
        WordEntry(word: "RADYASYON",   category: "Bilim+"),
        WordEntry(word: "REAKTÖR",     category: "Bilim+"),
        WordEntry(word: "ROBOT",       category: "Bilim+"),
        WordEntry(word: "SİNAPS",      category: "Bilim+"),
        WordEntry(word: "SİSTEM",      category: "Bilim+"),
        WordEntry(word: "SUPERNOVA",   category: "Bilim+"),
        WordEntry(word: "TEORİ",       category: "Bilim+"),
        WordEntry(word: "TERMODİNAMİK", category: "Bilim+"),
        WordEntry(word: "TESLA",       category: "Bilim+"),
        WordEntry(word: "TİTAN",       category: "Bilim+"),
        WordEntry(word: "TÜRBİN",      category: "Bilim+"),
        WordEntry(word: "VAKUM",       category: "Bilim+"),
        WordEntry(word: "VİRÜS",       category: "Bilim+"),
        WordEntry(word: "YERÇEKİMİ",   category: "Bilim+"),
        WordEntry(word: "YAPAYZEKA",   category: "Bilim+"),
        WordEntry(word: "ZAMAN",       category: "Bilim+"),
        WordEntry(word: "ZEKA",        category: "Bilim+"),
        WordEntry(word: "ZİNCİR",      category: "Bilim+"),
    ]

    // MARK: - Hints

    static let bilimPlusHints: [String: String] = [
        "ALGORİTMA":       "Bilgisayarların adım adım izlediği problem çözme tarifi.",
        "AŞIRELİTAY":      "Işık hızına yakın hareket eden parçacıkları inceleyen fiziğin dalı.",
        "ANTİBİYOTİK":     "Bakterileri öldürmek için doktorların yazdığı ilaç türü.",
        "ATOM":            "Maddenin kimyasal özelliklerini koruyan en küçük yapı taşı.",
        "BAKTERİ":         "Tek hücreli, çıplak gözle görülemeyen mikroorganizma.",
        "BİLİŞİM":         "Bilgi ve iletişim teknolojilerini kapsayan modern bilim dalı.",
        "BİYOLOJİ":        "Canlıların yapısını, işlevini ve evrimini araştıran bilim.",
        "BLOKZİNCİR":      "Verilerin merkezi olmayan dağıtık bir yapıda saklandığı teknoloji.",
        "BULUT":           "İnternete bağlı sunucularda veri depolamayı sağlayan sistem.",
        "DENKLEM":         "İki tarafı birbirine eşit olan matematiksel ifade.",
        "DERİÖĞRENME":     "Sinir ağlarının katmanlar aracılığıyla öğrendiği yapay zeka yöntemi.",
        "DEVRE":           "Elektrik akımının iletkenler üzerinde oluşturduğu kapalı yol.",
        "DNA":             "Canlıların kalıtsal bilgisini taşıyan çift sarmal molekül.",
        "ELEKTRON":        "Atomun çekirdeğini yörüngede dolanan negatif yüklü parçacık.",
        "ENZİM":           "Hücredeki kimyasal tepkimeleri hızlandıran protein yapılı katalizör.",
        "EVRİM":           "Canlı türlerinin nesiller boyunca değişip dönüştüğü süreç.",
        "FİZİK":           "Madde, enerji ve doğa yasalarını inceleyen temel bilim dalı.",
        "FOTON":           "Işığı oluşturan ve kütlesiz olan temel enerji paketi.",
        "GENETİK":         "Kalıtımı ve genlerin aktarımını araştıran biyoloji dalı.",
        "GRAVİTON":        "Yerçekimi kuvvetini taşıdığı varsayılan teorik parçacık.",
        "HİDROJEN":        "Evrendeki en hafif ve en bol bulunan element.",
        "HİPOTEZ":         "Bilimsel bir deneyin başında öne sürülen test edilebilir öngörü.",
        "HUBBLE":          "Dünya yörüngesinde dolaşan ve galaksileri gözlemleyen uzay teleskobu.",
        "İSTATİSTİK":      "Verileri toplayıp analiz ederek sonuçlar çıkaran matematik dalı.",
        "KAOS":            "Küçük değişikliklerin büyük ve öngörülemeyen sonuçlara yol açtığı durum.",
        "KİMYA":           "Maddenin yapısını ve dönüşümlerini inceleyen bilim dalı.",
        "KLON":            "Bir organizmadan aynı genetik bilgiyle üretilen kopya.",
        "KROMOZOM":        "DNA'nın hücre çekirdeğinde düzenli paketlendiği yapı.",
        "KUANTUM":         "Atom altı parçacıkların davranışını açıklayan fizik teorisi.",
        "LABORATUVAR":     "Bilimsel deneylerin kontrollü koşullarda yapıldığı özel mekan.",
        "LİTYUM":          "Şarj edilebilir pillerde yaygın kullanılan hafif metal element.",
        "MATEMATİK":       "Sayıları, şekilleri ve ilişkileri mantık çerçevesinde inceleyen bilim.",
        "MİKROSKOP":       "Gözle görülemeyen nesneleri büyüterek inceleyen optik alet.",
        "MOLEKÜL":         "İki veya daha fazla atomun bir araya gelerek oluşturduğu yapı.",
        "NANOTEKNOLOJİ":   "Maddeyi nanometre ölçeğinde tasarlayıp manipüle eden teknoloji alanı.",
        "NEBULA":          "Uzayda yeni yıldızların doğduğu gaz ve toz bulutu.",
        "NÖROZON":         "Sinir hücrelerinin aktif ateşlenme bölgesini tanımlayan kavram.",
        "OKSİJEN":         "Solunumu sağlayan ve yanmayı destekleyen renksiz gaz elementi.",
        "ORBİTAL":         "Bir elektronu bulunma ihtimali yüksek olan bölgeyi tanımlayan kavram.",
        "PANDEMİ":         "Bir hastalığın tüm dünyaya yayılarak küresel salgına dönüştüğü durum.",
        "PARÇACIK":        "Maddenin ya da radyasyonun en küçük bileşen birimi.",
        "PROTON":          "Atom çekirdeğinde yer alan pozitif yüklü temel parçacık.",
        "RADYASYON":       "Yüksek enerjili dalga veya parçacıkların yayılması şeklinde gerçekleşen enerji transferi.",
        "REAKTÖR":         "Nükleer fisyon ya da füzyon tepkimelerinin kontrollü yürütüldüğü tesis.",
        "ROBOT":           "Programlanarak tekrarlayan görevleri otomatik olarak yerine getiren makine.",
        "SİNAPS":          "İki sinir hücresi arasında sinyal iletiminin gerçekleştiği bağlantı noktası.",
        "SİSTEM":          "Ortak bir amaca yönelik birbiriyle etkileşen parçalardan oluşan bütün.",
        "SUPERNOVA":       "Büyük kütleli bir yıldızın ömrünü devasa bir patlamayla noktalayan olay.",
        "TEORİ":           "Gözlem ve kanıtlarla desteklenen, doğayı açıklayan bilimsel çerçeve.",
        "TERMODİNAMİK":    "Isı, iş ve enerji dönüşümlerini inceleyen fizik dalı.",
        "TESLA":           "Manyetik akı yoğunluğunun SI biriminin adını veren bilim insanı.",
        "TİTAN":           "Satürn'ün en büyük uydusu ve kalın atmosfere sahip gök cismi.",
        "TÜRBİN":          "Akışkan enerjisini dönerek mekanik güce dönüştüren makine.",
        "VAKUM":           "Maddenin neredeyse hiç bulunmadığı, basıncın sıfıra yakın olduğu ortam.",
        "VİRÜS":           "Canlı hücreye girerek çoğalan ve hastalığa neden olan mikroskobik etken.",
        "YERÇEKİMİ":       "Kütleli cisimlerin birbirini çektiği evrensel kuvvet.",
        "YAPAYZEKA":       "Makinelerin insan benzeri düşünme ve öğrenme yeteneği kazandığı teknoloji.",
        "ZAMAN":           "Olayların birbirini izlediği, geri döndürülemeyen fiziksel boyut.",
        "ZEKA":            "Öğrenme, problem çözme ve uyum sağlama kapasitesi.",
        "ZİNCİR":          "Halkaların arka arkaya bağlanmasıyla oluşan, kimyada de kullanılan yapı.",
    ]
}
