import Foundation

extension WordList {

    // MARK: - Words

    static let muzikPlusWords: [WordEntry] = [
        WordEntry(word: "SENFONİ",         category: "Müzik+"),
        WordEntry(word: "ORKESTRA",        category: "Müzik+"),
        WordEntry(word: "MAESTRO",         category: "Müzik+"),
        WordEntry(word: "SOLO",            category: "Müzik+"),
        WordEntry(word: "DÜETO",           category: "Müzik+"),
        WordEntry(word: "ARYA",            category: "Müzik+"),
        WordEntry(word: "OPERA",           category: "Müzik+"),
        WordEntry(word: "BALAD",           category: "Müzik+"),
        WordEntry(word: "RİTM",            category: "Müzik+"),
        WordEntry(word: "TEMPO",           category: "Müzik+"),
        WordEntry(word: "AKORD",           category: "Müzik+"),
        WordEntry(word: "NOTA",            category: "Müzik+"),
        WordEntry(word: "ENSTRÜMAN",       category: "Müzik+"),
        WordEntry(word: "PİYANO",          category: "Müzik+"),
        WordEntry(word: "GİTAR",           category: "Müzik+"),
        WordEntry(word: "BATERİ",          category: "Müzik+"),
        WordEntry(word: "SAKSOFON",        category: "Müzik+"),
        WordEntry(word: "TROMPET",         category: "Müzik+"),
        WordEntry(word: "KEMAN",           category: "Müzik+"),
        WordEntry(word: "VİYOLONSEL",      category: "Müzik+"),
        WordEntry(word: "ARP",             category: "Müzik+"),
        WordEntry(word: "FLÜT",            category: "Müzik+"),
        WordEntry(word: "KLARNET",         category: "Müzik+"),
        WordEntry(word: "AKKORDION",       category: "Müzik+"),
        WordEntry(word: "BAĞLAMA",         category: "Müzik+"),
        WordEntry(word: "KANUN",           category: "Müzik+"),
        WordEntry(word: "UD",              category: "Müzik+"),
        WordEntry(word: "ZURNA",           category: "Müzik+"),
        WordEntry(word: "DAVUL",           category: "Müzik+"),
        WordEntry(word: "TANBUR",          category: "Müzik+"),
        WordEntry(word: "DEF",             category: "Müzik+"),
        WordEntry(word: "MAKAM",           category: "Müzik+"),
        WordEntry(word: "USUL",            category: "Müzik+"),
        WordEntry(word: "TÜRKÜ",           category: "Müzik+"),
        WordEntry(word: "ARABESK",         category: "Müzik+"),
        WordEntry(word: "POP",             category: "Müzik+"),
        WordEntry(word: "ROCK",            category: "Müzik+"),
        WordEntry(word: "JAZZ",            category: "Müzik+"),
        WordEntry(word: "BLUES",           category: "Müzik+"),
        WordEntry(word: "REGGAE",          category: "Müzik+"),
        WordEntry(word: "RAP",             category: "Müzik+"),
        WordEntry(word: "HIPHOP",          category: "Müzik+"),
        WordEntry(word: "ELEKTRO",         category: "Müzik+"),
        WordEntry(word: "TECHNO",          category: "Müzik+"),
        WordEntry(word: "ALBÜM",           category: "Müzik+"),
        WordEntry(word: "STÜDYO",          category: "Müzik+"),
        WordEntry(word: "PRODÜKTÖR",       category: "Müzik+"),
        WordEntry(word: "KONSERT",         category: "Müzik+"),
        WordEntry(word: "FESTİVAL",        category: "Müzik+"),
        WordEntry(word: "TURNE",           category: "Müzik+"),
        WordEntry(word: "BANDO",           category: "Müzik+"),
        WordEntry(word: "KORO",            category: "Müzik+"),
        WordEntry(word: "ŞARKI",           category: "Müzik+"),
        WordEntry(word: "MELODİ",          category: "Müzik+"),
        WordEntry(word: "ARMONİ",          category: "Müzik+"),
        WordEntry(word: "BESTECİ",         category: "Müzik+"),
        WordEntry(word: "GİTARİST",        category: "Müzik+"),
        WordEntry(word: "BATERİSTLER",     category: "Müzik+"),
        WordEntry(word: "VOKAL",           category: "Müzik+"),
        WordEntry(word: "MİKROFON",        category: "Müzik+"),
    ]

    // MARK: - Hints

    static let muzikPlusHints: [String: String] = [
        "SENFONİ":         "Orkestranın bütün bölümleriyle seslendirdiği büyük çaplı müzik eseri.",
        "ORKESTRA":        "Farklı çalgıcılardan oluşan büyük toplu müzik topluluğu.",
        "MAESTRO":         "Orkestrayı yöneten ve müzik sanatında usta olan şef.",
        "SOLO":            "Tek bir sanatçının sahne alarak kendi başına icra ettiği performans.",
        "DÜETO":           "İki sanatçının birlikte seslendirdiği müzik ya da şarkı.",
        "ARYA":            "Operada tek bir ses tarafından söylenen uzun ve dramatik parça.",
        "OPERA":           "Müzik, şan ve sahne oyununun bir araya geldiği dramatik sanat formu.",
        "BALAD":           "Genellikle aşk ya da hüzün temalı yavaş tempolu şarkı türü.",
        "RİTM":            "Müzikte seslerin düzenli aralıklarla tekrar eden vurgu düzeni.",
        "TEMPO":           "Müziğin hızını belirleyen ve dakikadaki vuruş sayısını gösteren ölçü.",
        "AKORD":           "Aynı anda çalınan üç ya da daha fazla notanın bir arada oluşturduğu ses.",
        "NOTA":            "Bir sesin yüksekliğini ve süresini gösteren müzik sembolü.",
        "ENSTRÜMAN":       "Müzik üretmek amacıyla kullanılan her türlü çalgı aleti.",
        "PİYANO":          "Tuşlara basıldığında tellerin vurulmasıyla ses çıkaran büyük klavyeli çalgı.",
        "GİTAR":           "Teller titreştirilerek çalınan, sapı ve gövdesi olan yaylı/mızraplı çalgı.",
        "BATERİ":          "Davul, zil ve diğer vurmalı çalgılardan oluşan büyük ritim seti.",
        "SAKSOFON":        "Ağızlığa üfleyerek çalınan, genellikle cazda kullanılan metal nefesli çalgı.",
        "TROMPET":         "Parlak tınısıyla tanınan, ventilli bakır nefesli çalgı.",
        "KEMAN":           "Yay sürtülerek çalınan telli çalgıların en incesi ve en keskin tınılısı.",
        "VİYOLONSEL":      "Keman ailesinin en büyük üyelerinden, derin sesli yaylı çalgı.",
        "ARP":             "Dikey çerçeveye gerilmiş teller titreştirilerek çalınan antik görünümlü çalgı.",
        "FLÜT":            "Üfleyerek çalınan, insan sesine en yakın tona sahip tahta nefesli.",
        "KLARNET":         "Kamışlı ağızlığıyla üflenerek çalınan, geniş ses aralıklı nefesli çalgı.",
        "AKKORDION":       "Körük sıkıştırılarak çalınan ve tuş ile düğmeleri olan taşınabilir çalgı.",
        "BAĞLAMA":         "Türk halk müziğinin simgesi sayılan saplı telli çalgı.",
        "KANUN":           "Mızrapla çalınan, Türk ve Arap müziğine özgü yatay telli çalgı.",
        "UD":              "Armut biçimindeki gövdesiyle Doğu müziğinin en eski telli çalgısı.",
        "ZURNA":           "Davulla birlikte çalınan, keskin ve güçlü sesli tahta nefesli çalgı.",
        "DAVUL":           "Tokmaklarla vurulan, köy düğünleri ve askeri müziğin vazgeçilmez ritim aleti.",
        "TANBUR":          "Uzun saplı ve çok telli, Osmanlı klasik müziğinin temel çalgısı.",
        "DEF":             "Çerçeveli, tenli ve zilli küçük vurmalı çalgı.",
        "MAKAM":           "Türk ve Arap müziğinde melodinin kurulduğu ses dizisi çerçevesi.",
        "USUL":            "Türk müziğinde belirli vuruşların tekrarlandığı ritim kalıbı.",
        "TÜRKÜ":           "Anadolu halk geleneğinden gelen, sözlü halk müziği türü.",
        "ARABESK":         "Hüzünlü sözleri ve Doğu motifleriyle öne çıkan Türk popüler müzik akımı.",
        "POP":             "Geniş kitlelere hitap eden, yaygın melodi ve ritimlerden oluşan müzik türü.",
        "ROCK":            "Elektro gitar ve güçlü ritmiyle öne çıkan Batı kökenli müzik türü.",
        "JAZZ":            "Doğaçlama ve senkop ritmiyle öne çıkan Afro-Amerikan kökenli müzik türü.",
        "BLUES":           "Hüzünlü sözleri ve çekici melodisiyle tanınan Amerikalı müzik türü.",
        "REGGAE":          "Jamaica kökenli, yavaş senkoplu ritmiyle tanınan müzik türü.",
        "RAP":             "Hızlı ve ölçülü sözlerin ritimle okunduğu hiphop kökenli müzik stili.",
        "HIPHOP":          "Rap, DJ'lik ve dans kültürünü bir araya getiren kentsel müzik hareketi.",
        "ELEKTRO":         "Sentezleyici ve elektronik ritim makinelerinin egemen olduğu müzik türü.",
        "TECHNO":          "Dansa yönelik, hızlı tempolu elektronik müzik stili.",
        "ALBÜM":           "Bir sanatçının şarkılarını bir arada sunan müzik koleksiyonu.",
        "STÜDYO":          "Müzisyenlerin ses kaydettiği akustik olarak tasarlanmış mekan.",
        "PRODÜKTÖR":       "Müzik projesinin yapım sürecini yöneten sanatsal yönetici.",
        "KONSERT":         "Sanatçıların canlı olarak sahne alıp müzik icra ettiği gösteri.",
        "FESTİVAL":        "Birden fazla sanatçının yer aldığı büyük çaplı açık hava müzik etkinliği.",
        "TURNE":           "Sanatçının birden fazla şehirde art arda konser verdiği gezi programı.",
        "BANDO":           "Tören ve geçitlerde yürüyerek çalan üflemeli ve vurmalı çalgı topluluğu.",
        "KORO":            "Birlikte şarkı söyleyen büyük gruptan oluşan ses topluluğu.",
        "ŞARKI":           "Güftesi ve bestesiyle oluşturulan, sesle icra edilen müzik eseri.",
        "MELODİ":          "Ardarda gelen notaların oluşturduğu akılda kalıcı ezgi çizgisi.",
        "ARMONİ":          "Birden fazla sesin aynı anda uyumlu biçimde bir araya gelmesi.",
        "BESTECİ":         "Müzik eserlerini notaya döken yaratıcı sanatçı.",
        "GİTARİST":        "Gitar çalmayı meslek edinmiş ya da uzmanlaşmış müzisyen.",
        "BATERİSTLER":     "Bateride ritim tutmayı meslek edinen müzisyenler topluluğu.",
        "VOKAL":           "Bir müzik grubunda şarkı söyleme görevini üstlenen ses sanatçısı.",
        "MİKROFON":        "Ses dalgalarını elektrik sinyaline dönüştürerek ses yükseltmeye yarayan cihaz.",
    ]
}
