import Foundation

extension WordList {

    // MARK: - Words

    static let tarihWords: [WordEntry] = [
        WordEntry(word: "ALEMDAR", category: "Tarih"),
        WordEntry(word: "ALP ER TUNGA", category: "Tarih"),
        WordEntry(word: "ANTLAŞMA", category: "Tarih"),
        WordEntry(word: "ARIZ", category: "Tarih"),
        WordEntry(word: "ARŞİDÜK", category: "Tarih"),
        WordEntry(word: "ATABEYİ", category: "Tarih"),
        WordEntry(word: "AVARIZ", category: "Tarih"),
        WordEntry(word: "BALKAN SAVAŞLARI", category: "Tarih"),
        WordEntry(word: "BARIŞ", category: "Tarih"),
        WordEntry(word: "BEDESTEN", category: "Tarih"),
        WordEntry(word: "CEMİYETİ AKVAM", category: "Tarih"),
        WordEntry(word: "CÜLUS", category: "Tarih"),
        WordEntry(word: "CÜLUS BAHŞİŞİ", category: "Tarih"),
        WordEntry(word: "ÇANAKKALE SAVAŞI", category: "Tarih"),
        WordEntry(word: "ÇELEBİ", category: "Tarih"),
        WordEntry(word: "DARÜLFÜNUN", category: "Tarih"),
        WordEntry(word: "DEVRİM", category: "Tarih"),
        WordEntry(word: "DEFTERDAR", category: "Tarih"),
        WordEntry(word: "DERBENT", category: "Tarih"),
        WordEntry(word: "DEREBEYİ", category: "Tarih"),
        WordEntry(word: "DİRLİK", category: "Tarih"),
        WordEntry(word: "DİVAN", category: "Tarih"),
        WordEntry(word: "EMPERYALİZM", category: "Tarih"),
        WordEntry(word: "ENDERUN", category: "Tarih"),
        WordEntry(word: "ENDÜLÜS", category: "Tarih"),
        WordEntry(word: "ETNOGRAFYA", category: "Tarih"),
        WordEntry(word: "FATİH SULTAN MEHMET", category: "Tarih"),
        WordEntry(word: "FEODALİZM", category: "Tarih"),
        WordEntry(word: "FERMAN", category: "Tarih"),
        WordEntry(word: "FETRET", category: "Tarih"),
        WordEntry(word: "FETVA", category: "Tarih"),
        WordEntry(word: "FIRKA", category: "Tarih"),
        WordEntry(word: "FIKIH", category: "Tarih"),
        WordEntry(word: "GANİMET", category: "Tarih"),
        WordEntry(word: "GÖÇ", category: "Tarih"),
        WordEntry(word: "GÖÇEBE", category: "Tarih"),
        WordEntry(word: "HAKAN", category: "Tarih"),
        WordEntry(word: "HAN", category: "Tarih"),
        WordEntry(word: "HEGEMONYA", category: "Tarih"),
        WordEntry(word: "HİCRET", category: "Tarih"),
        WordEntry(word: "HİLAFET", category: "Tarih"),
        WordEntry(word: "HİSAR", category: "Tarih"),
        WordEntry(word: "HİYERARŞİ", category: "Tarih"),
        WordEntry(word: "HİYEROGLİF", category: "Tarih"),
        WordEntry(word: "İMPARATOR", category: "Tarih"),
        WordEntry(word: "İMPARATORLUK", category: "Tarih"),
        WordEntry(word: "İHTİLAL", category: "Tarih"),
        WordEntry(word: "İSTİLA", category: "Tarih"),
        WordEntry(word: "İSTİKLAL MAHKEMESİ", category: "Tarih"),
        WordEntry(word: "İTTİFAK", category: "Tarih"),
        WordEntry(word: "İTİLAF", category: "Tarih"),
        WordEntry(word: "KABOTAJ KANUNU", category: "Tarih"),
        WordEntry(word: "KADI", category: "Tarih"),
        WordEntry(word: "KADIASKER", category: "Tarih"),
        WordEntry(word: "KAĞAN", category: "Tarih"),
        WordEntry(word: "KALKOLİTİK", category: "Tarih"),
        WordEntry(word: "KALVENİZM", category: "Tarih"),
        WordEntry(word: "KAPİKULU", category: "Tarih"),
        WordEntry(word: "KAPİTALİZM", category: "Tarih"),
        WordEntry(word: "KAPİTÜLASYON", category: "Tarih"),
        WordEntry(word: "KAPTANI DERYA", category: "Tarih"),
        WordEntry(word: "KERVANSARAY", category: "Tarih"),
        WordEntry(word: "KİBELE", category: "Tarih"),
        WordEntry(word: "KİLİKYA", category: "Tarih"),
        WordEntry(word: "KONGRE", category: "Tarih"),
        WordEntry(word: "KRAL YOLU", category: "Tarih"),
        WordEntry(word: "KURGAN", category: "Tarih"),
        WordEntry(word: "KURTULUŞ SAVAŞI", category: "Tarih"),
        WordEntry(word: "KURULTAY", category: "Tarih"),
        WordEntry(word: "KUVAİ MİLLİYE", category: "Tarih"),
        WordEntry(word: "KÜLLİYE", category: "Tarih"),
        WordEntry(word: "KÜMBET", category: "Tarih"),
        WordEntry(word: "LAĞIMCI", category: "Tarih"),
        WordEntry(word: "LAHİT", category: "Tarih"),
        WordEntry(word: "LALA", category: "Tarih"),
        WordEntry(word: "LALE DEVRİ", category: "Tarih"),
        WordEntry(word: "LEJYON", category: "Tarih"),
        WordEntry(word: "LİYAKAT", category: "Tarih"),
        WordEntry(word: "LONCA", category: "Tarih"),
        WordEntry(word: "MAGNA CARTA", category: "Tarih"),
        WordEntry(word: "MAARİF", category: "Tarih"),
        WordEntry(word: "MAREŞAL", category: "Tarih"),
        WordEntry(word: "MEBUS", category: "Tarih"),
        WordEntry(word: "MECELLE", category: "Tarih"),
        WordEntry(word: "MEDENİYET", category: "Tarih"),
        WordEntry(word: "MEDRESE", category: "Tarih"),
        WordEntry(word: "MECLİSİ MEBUSAN", category: "Tarih"),
        WordEntry(word: "MEŞRUTİYET", category: "Tarih"),
        WordEntry(word: "MEŞVERET", category: "Tarih"),
        WordEntry(word: "MELİK", category: "Tarih"),
        WordEntry(word: "MİRAS", category: "Tarih"),
        WordEntry(word: "MİNARE", category: "Tarih"),
        WordEntry(word: "MONARŞİ", category: "Tarih"),
        WordEntry(word: "MÜBADELE", category: "Tarih"),
        WordEntry(word: "MÜDERRİS", category: "Tarih"),
        WordEntry(word: "MÜTAREKE", category: "Tarih"),
        WordEntry(word: "NİZAMI CEDİD", category: "Tarih"),
        WordEntry(word: "ORTAÇAĞ", category: "Tarih"),
        WordEntry(word: "PADİŞAH", category: "Tarih"),
        WordEntry(word: "PALEOLİTİK", category: "Tarih"),
        WordEntry(word: "PARLAMENTO", category: "Tarih"),
        WordEntry(word: "POLİTEİZM", category: "Tarih"),
        WordEntry(word: "REFORM", category: "Tarih"),
        WordEntry(word: "REJİM", category: "Tarih"),
        WordEntry(word: "RÖNESANS", category: "Tarih"),
        WordEntry(word: "RUHBAN", category: "Tarih"),
        WordEntry(word: "SADRAZAM", category: "Tarih"),
        WordEntry(word: "SALTANAT", category: "Tarih"),
        WordEntry(word: "SANAYİ İNKILABI", category: "Tarih"),
        WordEntry(word: "SAVAŞ", category: "Tarih"),
        WordEntry(word: "SEFER", category: "Tarih"),
        WordEntry(word: "SELÇUKLU", category: "Tarih"),
        WordEntry(word: "SENATO", category: "Tarih"),
        WordEntry(word: "SİPAHİ", category: "Tarih"),
        WordEntry(word: "SKOLASTİZM", category: "Tarih"),
        WordEntry(word: "ŞAMAN", category: "Tarih"),
        WordEntry(word: "ŞEHNAME", category: "Tarih"),
        WordEntry(word: "ŞEHREMİNİ", category: "Tarih"),
        WordEntry(word: "ŞEHZADE", category: "Tarih"),
        WordEntry(word: "ŞEYHÜLİSLAM", category: "Tarih"),
        WordEntry(word: "TASAVVUF", category: "Tarih"),
        WordEntry(word: "TEKFUR", category: "Tarih"),
        WordEntry(word: "TEOKRASİ", category: "Tarih"),
        WordEntry(word: "TİMAR", category: "Tarih"),
        WordEntry(word: "TUFAN", category: "Tarih"),
        WordEntry(word: "ULEMA", category: "Tarih"),
        WordEntry(word: "ULUFE", category: "Tarih"),
        WordEntry(word: "VELİAHT", category: "Tarih"),
        WordEntry(word: "VEZİR", category: "Tarih"),
        WordEntry(word: "ZAFER", category: "Tarih"),
        WordEntry(word: "ZAPTİYE", category: "Tarih"),
    ]

    // MARK: - Hints

    static let tarihHints: [String: String] = [
        "ATATÜRK":              "Türkiye Cumhuriyeti'nin kurucusu ve ilk cumhurbaşkanı.",
        "CUMHURİYET":           "1923'te ilan edilen, halkın egemenliğe dayandığı yönetim biçimi.",
        "DEVRİM":               "Köklü toplumsal ya da siyasi düzenin kısa sürede değiştirilmesi.",
        "FEODALİZM":            "Toprak karşılığı hizmet esasına dayalı Orta Çağ Avrupa yönetim sistemi.",
        "HİYEROGLİF":           "Antik Mısırlıların kullandığı resim yazısı sistemi.",
        "İMPARATORLUK":         "Geniş toprakları idare eden tek hükümdar liderliğindeki büyük devlet.",
        "KURTULUŞ":             "İşgale karşı verilen bağımsızlık mücadelesi.",
        "OSMANLICA":            "Osmanlı İmparatorluğu döneminde kullanılan Türkçe-Arapça-Farsça dil karması.",
        "PAPİRÜS":              "Antik Mısırlıların yazmak için kullandığı bitkiden yapılmış malzeme.",
        "RÖNESANS":             "14-17. yüzyıllarda Avrupa'da sanat ve bilimin yeniden doğuşu.",
        "SEFERBERLİK":          "Bir ülkenin tüm kaynaklarının savaş için seferber edilmesi.",
        "TOPKAPI":              "İstanbul'da Osmanlı padişahlarının yüzyıllarca yaşadığı saray.",
        "BALKANLAR":            "Güneydoğu Avrupa'da çok sayıda ülkeyi barındıran coğrafi bölge.",
        "ALEMDAR":              "Sancak taşıyan; özellikle Nizam-ı Cedid'i savunan Osmanlı paşasının unvanı.",
        "ALP ER TUNGA":         "Türk destanlarında geçen, İran kaynaklarında Efrasiyab olarak bilinen Saka hükümdarı.",
        "ANTLAŞMA":             "İki ya da daha fazla devlet arasında imzalanan bağlayıcı uluslararası sözleşme.",
        "ARIZ":                 "Osmanlı'da askeri şikayetleri padişaha ileten görevli.",
        "ARŞİDÜK":              "Avusturya-Macaristan İmparatorluğu'nda hanedan üyelerine verilen yüksek unvan.",
        "ATABEYİ":              "Selçuklu ve Osmanlı dönemlerinde şehzadelerin eğitiminden sorumlu tutulan koruyucu.",
        "AVARIZ":               "Osmanlı'da olağanüstü durumlarda alınan, savaş ve afet zamanlarında toplanan vergi.",
        "BALKAN SAVAŞLARI":     "1912-1913 yıllarında Osmanlı'nın Balkan devletleriyle yaşadığı, büyük toprak kayıplarına yol açan savaşlar.",
        "BARIŞ":                "Çatışma ve savaşın sona ermesiyle kurulan barışçıl düzen.",
        "BEDESTEN":             "Osmanlı şehirlerinde değerli malların alınıp satıldığı, genellikle çarşı içindeki kapalı pazar yapısı.",
        "CEMİYETİ AKVAM":       "Birinci Dünya Savaşı'nın ardından kurulan, BM'nin öncülü olan milletlerarası barış örgütü.",
        "CÜLUS":                "Osmanlı padişahının tahta çıkması ve bunun kutlanması.",
        "CÜLUS BAHŞİŞİ":        "Osmanlı'da yeni padişahın cülus töreninde askere ve halka dağıttığı para veya hediye.",
        "ÇANAKKALE SAVAŞI":     "1915'te Osmanlı kuvvetlerinin İtilaf Devletleri'ne karşı başarıyla savunduğu destansı muharebe.",
        "ÇELEBİ":               "Osmanlı döneminde eğitimli, kültürlü ve zarif kişi için kullanılan saygın unvan.",
        "DARÜLFÜNUN":           "Osmanlı döneminde açılan, günümüz İstanbul Üniversitesi'nin öncülü olan ilk yüksekokul.",
        "DEFTERDAR":            "Osmanlı Devleti'nde hazine ve mali işlerden sorumlu tutulan en üst düzey maliye görevlisi.",
        "DERBENT":              "Stratejik geçit ya da sınır kapısında güvenliği sağlamak üzere kurulan küçük Osmanlı garnizon köyü.",
        "DEREBEYİ":             "Osmanlı'nın zayıflamasıyla bulunduğu bölgede fiilen söz sahibi olan yerel güç odağı.",
        "DİRLİK":               "Osmanlı'da devlet hizmetleri karşılığında verilen, tımar, zeamet ve has olmak üzere üç sınıfa ayrılan toprak geliri.",
        "DİVAN":                "Osmanlı'da sadrazamın başkanlığında devlet işlerinin görüşüldüğü yüksek yönetim kurulu.",
        "EMPERYALİZM":          "Güçlü devletlerin zayıf ülkeleri siyasi, ekonomik veya askeri yollarla denetim altına alma politikası.",
        "ENDERUN":              "Osmanlı sarayının iç bölümünde, devletin en yetenekli gençlerini yetiştirdiği özel eğitim okulu.",
        "ENDÜLÜS":              "711-1492 yılları arasında Müslümanların yönettiği, bilim ve sanatın zirveye ulaştığı İber Yarımadası bölgesi.",
        "ETNOGRAFYA":           "Toplumların örf, gelenek ve kültürel yaşantılarını araştırıp belgeleyen bilim dalı.",
        "FATİH SULTAN MEHMET":  "1453'te İstanbul'u fethederek Bizans İmparatorluğu'na son veren Osmanlı padişahı.",
        "FERMAN":               "Osmanlı padişahının mühürlü, yetkili ve bağlayıcı resmi emirnamesi.",
        "FETRET":               "Osmanlı'da 1402-1413 yılları arasında taht kavgalarının yaşandığı iktidar boşluğu dönemi.",
        "FETVA":                "İslam hukukçusu müftünün dini bir konudaki soruya verdiği yetkili hukuki görüş.",
        "FIRKA":                "Osmanlı ve erken Cumhuriyet dönemlerinde askeri birlik ya da siyasi parti anlamında kullanılan terim.",
        "FIKIH":                "İslam hukukunun ayrıntılı kurallarını ve hükümlerini inceleyen bilim dalı.",
        "GANİMET":              "Savaşta düşmandan ele geçirilen silah, hayvan, mal ve esirlerden oluşan savaş kazanımı.",
        "GÖÇ":                  "Bireylerin ya da toplulukların yaşam koşulları nedeniyle bir yerden başka bir yere kalıcı olarak taşınması.",
        "GÖÇEBE":               "Sabit bir yerleşim yeri olmaksızın mevsimlik otlaklar ve su kaynakları peşinde dolaşan topluluk.",
        "HAKAN":                "Eski Türk ve Moğol devletlerinde en yüksek egemenlik ve otorite ifade eden hükümdar unvanı.",
        "HAN":                  "Türk ve Moğol devletlerinde yönetici için kullanılan, kağandan sonra gelen unvan.",
        "HEGEMONYA":            "Bir devletin diğerleri üzerinde askeri, siyasi ve ekonomik üstünlük kurduğu egemenlik düzeni.",
        "HİCRET":               "Hz. Muhammed'in 622'de Mekke'den Medine'ye göç etmesi; İslam takviminin başlangıç noktası.",
        "HİLAFET":              "İslam dünyasının dini ve siyasi liderliğini üstlenen, Osmanlı'da 1924'e dek süren kurum.",
        "HİSAR":                "Düşman saldırılarına karşı savunma amacıyla inşa edilen surlarla çevrili kale veya kervansaray.",
        "HİYERARŞİ":            "Yetki ve sorumlulukların kademeli biçimde sıralandığı örgütsel düzen.",
        "İMPARATOR":            "Birden fazla ulusu veya krallığı bünyesinde barındıran büyük devleti yöneten en üst hükümdar.",
        "İHTİLAL":              "Mevcut siyasi sistemi zor kullanarak devirmeyi amaçlayan silahlı halk ya da askeri hareket.",
        "İSTİLA":               "Yabancı bir gücün bir ülke ya da bölgeyi askeri kuvvetle ele geçirip işgal etmesi.",
        "İSTİKLAL MAHKEMESİ":   "Türkiye'de 1920-1927 yılları arasında isyan ve ihanet suçlamalarıyla yargılama yapan olağanüstü mahkeme.",
        "İTTİFAK":              "İki ya da daha fazla devletin ortak çıkarlar doğrultusunda birlikte hareket etmeye karar verdiği siyasi anlaşma.",
        "İTİLAF":               "Birinci Dünya Savaşı'nda İngiltere, Fransa ve Rusya'nın kurduğu devletler grubu.",
        "KABOTAJ KANUNU":       "1926'da çıkarılan, Türk kıyılarındaki deniz ticaretini yabancılara kapatan kanun.",
        "KADI":                 "Osmanlı'da şeriat kurallarına göre davaları karara bağlayan, geniş yetkili yargıç.",
        "KADIASKER":            "Osmanlı'da ordu ve sivil yargı işlerini denetleyen, iki büyük kadıaskerin bulunduğu üst yargı makamı.",
        "KAĞAN":                "Türk ve Moğol devletlerinde bütün boyları ve hanlıkları kapsayan en yüksek hükümdar unvanı.",
        "KALKOLİTİK":           "Bakır ve taş aletlerin birlikte kullanıldığı, tarihöncesi Kalkolitik (Bakır Taş) Çağı.",
        "KALVENİZM":            "Jean Calvin'in 16. yüzyılda ortaya koyduğu, Protestan reformu içindeki kader ve seçilmişlik öğretisi.",
        "KAPİKULU":             "Osmanlı'da padişaha doğrudan bağlı, devşirme sistemiyle yetiştirilen seçkin askeri sınıf.",
        "KAPİTALİZM":           "Üretim araçlarının özel ellerde bulunduğu ve piyasa mekanizmasının belirleyici olduğu ekonomik sistem.",
        "KAPİTÜLASYON":         "Osmanlı'nın yabancı devlet vatandaşlarına tanıdığı, kendi mahkemelerinden muafiyet gibi ayrıcalıklar.",
        "KAPTANI DERYA":        "Osmanlı donanmasının en üst komutanı; deniz kuvvetlerinin başındaki amiral.",
        "KERVANSARAY":          "İpek Yolu güzergahında tüccar ve yolcuların konaklayıp hayvanlarını dinlendirdiği büyük han.",
        "KİBELE":               "Anadolu kökenli, doğa ve bereketin anaları olarak tapınılan ana tanrıça kültü.",
        "KİLİKYA":              "Güney Anadolu'da Toros Dağları ile Akdeniz arasındaki tarihi bölge.",
        "KONGRE":               "Devletlerin ya da temsilcilerin siyasi ya da diplomatik meseleleri müzakere ettiği büyük toplantı.",
        "KRAL YOLU":            "Pers İmparatorluğu'nda Susa'dan Sardes'e uzanan, haber ve ticaret için kullanılan kadim anayol.",
        "KURGAN":               "Orta Asya bozkırlarında konuk edilen liderlerin, toprak tümseği şeklinde inşa edilen anıt mezarı.",
        "KURTULUŞ SAVAŞI":      "1919-1923 yılları arasında yürütülen, Türkiye Cumhuriyeti'nin kuruluşuna zemin hazırlayan bağımsızlık hareketi.",
        "KURULTAY":             "Eski Türk ve Moğol devletlerinde boyların ileri gelenlerinin önemli kararlar almak üzere toplandığı büyük meclis.",
        "KUVAİ MİLLİYE":        "Kurtuluş Savaşı'nın başlangıcında düzenli ordu kurulana dek direniş gösteren milis kuvvetleri.",
        "KÜLLİYE":              "Osmanlı'da cami, medrese, imaret ve hastane gibi yapıları bir arada barındıran çok işlevli yapı topluluğu.",
        "KÜMBET":               "Orta Asya ve Anadolu'da hükümdarlara ya da din büyüklerine ait, konik kubbeli anıt mezar yapısı.",
        "LAĞIMCI":              "Osmanlı ordusu'nda kale surlarının altına tünel kazarak patlayıcı yerleştiren uzman asker.",
        "LAHİT":                "Antik ve Orta Çağ dönemlerinde ölülerin içine konulduğu, genellikle taştan yapılmış sanduka şeklinde mezar.",
        "LALA":                 "Osmanlı'da şehzadelerin yetiştirilmesinden ve eğitiminden sorumlu tutulan saray görevlisi.",
        "LALE DEVRİ":           "Osmanlı'da 1718-1730 yılları arasındaki, lale yetiştiriciliği ve Batı ile kültürel alışverişle anılan refah dönemi.",
        "LEJYON":               "Roma İmparatorluğu'nda temel askeri birlik; yaklaşık beş bin piyade askerinden oluşurdu.",
        "LİYAKAT":              "Kişinin başarısı ve yetkinliğine göre yükselmesini esas alan, kayırmacılığa karşı yönetim ilkesi.",
        "LONCA":                "Orta Çağ ve Osmanlı dönemlerinde aynı mesleği yapanların oluşturduğu, üretim ve ticareti düzenleyen örgüt.",
        "MAGNA CARTA":          "1215'te İngiliz baronlarının Kral John'a imzalatttığı, hukuk devletinin temellerini atan belge.",
        "MAARİF":               "Osmanlı ve erken Cumhuriyet dönemlerinde halka açık eğitim, öğretim ve kültür kurumlarını kapsayan yapı.",
        "MAREŞAL":              "Ordu komuta kademesinin en tepesinde yer alan, en yüksek askeri rütbe.",
        "MEBUS":                "Osmanlı Meclis-i Mebusan'ında halkı temsil eden seçilmiş üye.",
        "MECELLE":              "19. yüzyılda hazırlanan, İslam hukuku esaslarına dayalı Osmanlı medeni kanunu.",
        "MEDENİYET":            "Toplumların sanat, bilim, hukuk ve kent yaşamında ulaştığı gelişmişlik düzeyi.",
        "MEDRESE":              "İslam dünyasında dini ve pozitif bilimlerin öğretildiği, câmi bünyesindeki yüksek öğretim kurumu.",
        "MECLİSİ MEBUSAN":      "1876 Kanun-i Esasi ile açılan, Osmanlı'nın ilk seçimle oluşan yasama meclisi.",
        "MEŞRUTİYET":           "Osmanlı'da padişah yetkilerinin anayasa ve meclis denetimiyle sınırlandırıldığı yönetim biçimi.",
        "MEŞVERET":             "İslam yönetim geleneğinde yöneticinin önemli kararları danışarak aldığı istişare toplantısı.",
        "MELİK":                "İslam coğrafyasında bağımsız veya yarı bağımsız küçük devleti yöneten hükümdar unvanı.",
        "MİRAS":                "Bir kişinin ölümünün ardından hukuken mirasçılarına devredilen mal, hak ve yükümlülükler bütünü.",
        "MİNARE":               "Caminin yanına yükseltilen, ezanın okunduğu silindirik veya çok köşeli kule.",
        "MONARŞİ":              "Devlet yönetiminin kalıtsal ya da seçimle belirlenen tek bir hükümdarda toplandığı yönetim biçimi.",
        "MÜBADELE":             "1923 Lozan Antlaşması çerçevesinde Türkiye ile Yunanistan arasında gerçekleştirilen zorunlu nüfus değişimi.",
        "MÜDERRİS":             "Osmanlı medreselerinde ders veren, günümüzdeki profesör karşılığı olan öğretim görevlisi.",
        "MÜTAREKE":             "İki çatışan taraf arasında silahlı çatışmayı geçici olarak durduran ateşkes anlaşması.",
        "NİZAMI CEDİD":         "III. Selim'in 18. yüzyıl sonunda kurduğu, Batı tarzında eğitim alan modern Osmanlı ordusu.",
        "ORTAÇAĞ":              "5. yüzyıldan 15. yüzyıla uzanan, feodalizm ve Kilise egemenliğinin belirleyici olduğu tarih dönemi.",
        "PADİŞAH":              "Osmanlı İmparatorluğu'nun mutlak otoritesini elinde bulunduran hükümdar.",
        "PALEOLİTİK":           "İnsanlığın taştan alet yaparak avcı-toplayıcı geçimle hayatta kaldığı, tarihöncesinin en uzun çağı.",
        "PARLAMENTO":           "Seçilmiş temsilcilerden oluşan, yasa yapma ve devlet bütçesini onaylama yetkisini kullanan yasama organı.",
        "POLİTEİZM":            "Birden fazla tanrının varlığına inanan, antik Yunan ve Roma'nın da benimsediği çok tanrılı inanç sistemi.",
        "REFORM":               "16. yüzyılda Martin Luther öncülüğünde Katolik Kilisesi'nde köklü değişim isteyen Protestan hareket.",
        "REJİM":                "Bir ülkede belirli bir dönem boyunca egemenliğini sürdüren yönetim biçimi ve iktidar yapısı.",
        "RUHBAN":               "Hristiyan kilisesinde dini eğitim almış ve din adamlığına adanmış kişileri tanımlayan unvan.",
        "SADRAZAM":             "Osmanlı'da padişahdan sonra en yetkili devlet adamı; günümüzün başbakanlığına karşılık gelir.",
        "SALTANAT":             "Osmanlı'da hükümdar ailesine ait, kuşaktan kuşağa geçen egemenlik ve otorite.",
        "SANAYİ İNKILABI":      "18. yüzyılda İngiltere'de başlayan, makineli üretime geçişi ve toplumsal dönüşümü simgeleyen süreç.",
        "SAVAŞ":                "Devletler ya da topluluklar arasındaki çatışmanın silahlı mücadeleye döndüğü fiili harp hali.",
        "SEFER":                "Osmanlı padişahı veya ordu komutanının bizzat katıldığı büyük askeri harekât.",
        "SELÇUKLU":             "11-13. yüzyıllarda Orta Asya'dan Anadolu'ya hükmeden Türk-İslam hanedanlığı.",
        "SENATO":               "Roma'dan günümüze uzanan, yasama erkini paylaşan ikinci meclis ya da üst danışma kurulu.",
        "SİPAHİ":               "Osmanlı'da tımar karşılığı atlı asker hizmeti veren, eyalet ordusunun temel süvari sınıfı.",
        "SKOLASTİZM":           "Orta Çağ'da Kilise öğretisini Antik Yunan felsefesiyle uzlaştırmaya çalışan Hristiyan akademik yöntemi.",
        "ŞAMAN":                "Eski Türk ve Altay toplulukları'nda ruhlarla iletişim kuran, hastalık ve doğa olaylarına aracılık eden din adamı.",
        "ŞEHNAME":              "Şair Firdevsi'nin kaleme aldığı, İran ve Türk tarihinin efsanevi kahramanlarını anlatan epik destan.",
        "ŞEHREMİNİ":            "Osmanlı'nın son döneminde İstanbul'un belediye başkanlığı görevini üstlenen kişiye verilen unvan.",
        "ŞEHZADE":              "Osmanlı'da padişahın oğluna verilen, taht adaylığını simgeleyen unvan.",
        "ŞEYHÜLİSLAM":          "Osmanlı'da dini hukuk ve eğitim kurumlarının en tepesinde bulunan, fetva verme yetkisini elinde tutan baş müftü.",
        "TASAVVUF":             "İslam'da iç arınma ve Allah'a yaklaşmayı esas alan mistik gelenek.",
        "TEKFUR":               "Orta Çağ'da Anadolu'daki Rum-Bizans beylerini tanımlamak için kullanılan unvan.",
        "TEOKRASİ":             "Devlet otoritesinin dini kurallara ve din adamlarına dayandığı yönetim biçimi.",
        "TİMAR":                "Osmanlı'da sipahilere verilen, belirli bir gelir karşılığı askerlik hizmeti öngören toprak sistemi.",
        "TUFAN":                "Pek çok kültürde anlatılan, insanlığın büyük bölümünü yok eden büyük su baskını efsanesi.",
        "ULEMA":                "İslam'da dini ilimler alanında eğitim görmüş, fetva ve hüküm verme yetkisine sahip alimler topluluğu.",
        "ULUFE":                "Osmanlı'da Yeniçeri ve kapıkulu askerlerine üç ayda bir ödenen düzenli maaş.",
        "VELİAHT":              "Tahta çıkacak sıradaki kişi; hükümdarın yerine geçmesi öngörülen resmi taht varisi.",
        "VEZİR":                "Osmanlı'da padişaha danışmanlık eden ve idari sorumluluk üstlenen yüksek rütbeli devlet adamı.",
        "ZAFER":                "Savaş ya da mücadelede rakip üzerinde kesin ve tam anlamıyla üstünlük sağlanması.",
        "ZAPTİYE":              "Osmanlı'da iç güvenliği sağlamak ve asayişi korumakla görevli jandarma ve polis kuvveti.",
    ]
}
