import Foundation

extension WordList {

    // MARK: - Words

    static let bilimWords: [WordEntry] = [
        WordEntry(word: "ALGORİTMA",   category: "Bilim"),
        WordEntry(word: "ANATOMİ",     category: "Bilim"),
        WordEntry(word: "ANTROPOLOJİ", category: "Bilim"),
        WordEntry(word: "ARKEOLOJİ",   category: "Bilim"),
        WordEntry(word: "ASTRONOMİ",   category: "Bilim"),
        WordEntry(word: "ASTROFİZİK",  category: "Bilim"),
        WordEntry(word: "ATOM",        category: "Bilim"),
        WordEntry(word: "BİYOLOJİ",    category: "Bilim"),
        WordEntry(word: "BOTANİK",     category: "Bilim"),
        WordEntry(word: "BULUT",       category: "Bilim"),
        WordEntry(word: "ELEKTRON",    category: "Bilim"),
        WordEntry(word: "ELEMENT",     category: "Bilim"),
        WordEntry(word: "ENERJİ",      category: "Bilim"),
        WordEntry(word: "ENTROPİ",     category: "Bilim"),
        WordEntry(word: "ENZİM",       category: "Bilim"),
        WordEntry(word: "EVRİM",       category: "Bilim"),
        WordEntry(word: "FİZİK",       category: "Bilim"),
        WordEntry(word: "FİZYOLOJİ",   category: "Bilim"),
        WordEntry(word: "FOTON",       category: "Bilim"),
        WordEntry(word: "GALAKSİ",     category: "Bilim"),
        WordEntry(word: "GENETİK",     category: "Bilim"),
        WordEntry(word: "HÜCRE",       category: "Bilim"),
        WordEntry(word: "İSTATİSTİK",  category: "Bilim"),
        WordEntry(word: "İZOTOP",      category: "Bilim"),
        WordEntry(word: "JEOLOJİ",     category: "Bilim"),
        WordEntry(word: "KATALİZÖR",   category: "Bilim"),
        WordEntry(word: "KİMYA",       category: "Bilim"),
        WordEntry(word: "KOZMOLOJİ",   category: "Bilim"),
        WordEntry(word: "KUANTUM",     category: "Bilim"),
        WordEntry(word: "MATEMATİK",   category: "Bilim"),
        WordEntry(word: "METEOROLOJİ", category: "Bilim"),
        WordEntry(word: "MİKROSKOP",   category: "Bilim"),
        WordEntry(word: "MOLEKÜL",     category: "Bilim"),
        WordEntry(word: "NÖRON",       category: "Bilim"),
        WordEntry(word: "NÖTRON",      category: "Bilim"),
        WordEntry(word: "OSMOZ",       category: "Bilim"),
        WordEntry(word: "PALEONTOLOJİ",category: "Bilim"),
        WordEntry(word: "PROTEİN",     category: "Bilim"),
        WordEntry(word: "PROTON",      category: "Bilim"),
        WordEntry(word: "ROBOT",       category: "Bilim"),
        WordEntry(word: "SİBER GÜVENLİK", category: "Bilim"),
        WordEntry(word: "TELESKOP",    category: "Bilim"),
        WordEntry(word: "VERİ",        category: "Bilim"),
        WordEntry(word: "YAPAY ZEKA",  category: "Bilim"),
        WordEntry(word: "YAZILIM",     category: "Bilim"),
        WordEntry(word: "ZOOLOJİ",     category: "Bilim"),
    ]

    // MARK: - Hints

    static let bilimHints: [String: String] = [
        "ANATOMİ":      "İnsan ve hayvan vücudunun yapısını inceleyen bilim dalı.",
        "ANTROPOLOJİ":  "Biyolojik ve kültürel açıdan insanı inceleyen bilim.",
        "ARKEOLOJİ":    "Kazı ve buluntularla geçmiş uygarlıkları araştıran bilim.",
        "ASTRONOMİ":    "Yıldız, gezegen ve evrenin oluşumunu inceleyen bilim.",
        "ASTROFİZİK":   "Gök cisimlerinin fiziksel özelliklerini araştıran bilim dalı.",
        "ATOM":         "Maddenin kimyasal özelliklerini taşıyan en küçük yapı taşı.",
        "BİYOLOJİ":     "Canlıları ve yaşam süreçlerini inceleyen temel doğa bilimi.",
        "BOTANİK":      "Bitki türlerini, yapılarını ve işlevlerini araştıran bilim.",
        "ELEKTRON":     "Atom çekirdeği etrafında dönen, negatif yüklü temel parçacık.",
        "ELEMENT":      "Tek tip atomdan oluşan, saf madde olarak altın, demir gibi.",
        "ENERJİ":       "İş yapma kapasitesi; ısı, ışık ve hareketin kaynağı.",
        "ENTROPİ":      "Bir sistemdeki düzensizlik ya da rastgeleliği ölçen termodinamik kavram.",
        "ENZİM":        "Biyokimyasal reaksiyonları hızlandıran protein yapılı katalizör.",
        "EVRİM":        "Canlıların çevre baskısıyla nesiller boyunca değişip gelişmesi.",
        "FİZİK":        "Madde, enerji ve kuvvetlerin temel yasalarını araştıran bilim.",
        "FİZYOLOJİ":    "Canlı organizmalarda gerçekleşen yaşam süreçlerini inceleyen bilim.",
        "FOTON":        "Işığı oluşturan, kütlesiz enerji paketçiği.",
        "GALAKSİ":      "Milyonlarca yıldız, gaz ve tozun yerçekimiyle bir arada tutulduğu devasa yapı.",
        "GENETİK":      "Kalıtım ve genler arasındaki ilişkiyi araştıran biyoloji dalı.",
        "HÜCRE":        "Canlıların temel yapı ve işlev birimi.",
        "İZOTOP":       "Aynı elementi, farklı nötron sayısına sahip atom türleri.",
        "JEOLOJİ":      "Dünya'nın katmanlarını, kayaçları ve tarihini araştıran bilim.",
        "KATALİZÖR":    "Kimyasal tepkimeyi hızlandıran ama kendisi tükenmeyen madde.",
        "KİMYA":        "Maddenin yapısını, bileşimini ve dönüşümlerini araştıran bilim.",
        "KOZMOLOJİ":    "Evrenin kökeni, yapısı ve geleceğini inceleyen bilim dalı.",
        "KUANTUM":      "Madde ve enerjinin en küçük temel birimini inceleyen fizik dalı.",
        "MATEMATİK":    "Sayılar, şekiller ve mantık ilişkilerini araştıran soyut bilim.",
        "METEOROLOJİ":  "Atmosferdeki hava olaylarını inceleyen ve tahmin eden bilim.",
        "MİKROSKOP":    "Gözle görülemeyen küçük yapıları büyüterek inceleyen optik araç.",
        "MOLEKÜL":      "İki ya da daha fazla atomun bağlanmasıyla oluşan en küçük bileşik birimi.",
        "NÖRON":        "Elektrik sinyali ileten sinir sistemi hücresi.",
        "NÖTRON":       "Atom çekirdeğinde yer alan, elektrik yükü olmayan parçacık.",
        "OSMOZ":        "Suyun yarı geçirgen bir zardan yüksek derişimli tarafa geçmesi.",
        "PALEONTOLOJİ": "Fosil kalıntılarını inceleyerek geçmiş yaşamı araştıran bilim.",
        "PROTEİN":      "Amino asitlerden oluşan, yapısal ve işlevsel görevler üstlenen biyomolekül.",
        "PROTON":       "Atom çekirdeğinde yer alan, pozitif yüklü parçacık.",
        "SİBER GÜVENLİK": "Bilgisayar sistemlerini ve verileri siber tehditlere karşı koruyan alan.",
        "TELESKOP":     "Uzaktaki gökcisimlerini büyüterek gözlemlemeye yarayan optik araç.",
        "ZOOLOJİ":      "Hayvanları, davranışlarını ve türlerini inceleyen biyoloji dalı.",
        "ALGORİTMA":    "Bir problemi çözmek için adım adım tanımlanmış işlemler dizisi.",
        "BULUT":        "Bilişimde verilerin ve uygulamaların internet üzerinden sunucu ağında depolandığı sistem.",
        "İSTATİSTİK":   "Verileri toplama, düzenleme ve yorumlama yöntemlerini araştıran matematik dalı.",
        "ROBOT":        "Programlanabilir, otomatik iş yapan, insan müdahalesi olmadan çalışan makine.",
        "VERİ":         "Bilgisayar ortamında işlenen ham bilgi; sayı, metin veya görsel biçiminde olabilir.",
        "YAPAY ZEKA":   "İnsan zekâsını taklit eden, öğrenme ve karar verme yapan bilgisayar sistemi.",
        "YAZILIM":      "Bilgisayara belirli görevleri yaptıran, programlama diliyle yazılmış talimatlar bütünü.",
    ]
}
