import Foundation

extension WordList {

    // MARK: - Words

    static let muzikWords: [WordEntry] = [
        WordEntry(word: "AKOR", category: "Müzik"),
        WordEntry(word: "AKORDEON", category: "Müzik"),
        WordEntry(word: "ALBÜM", category: "Müzik"),
        WordEntry(word: "ARMONİ", category: "Müzik"),
        WordEntry(word: "ARPA", category: "Müzik"),
        WordEntry(word: "BAĞLAMA", category: "Müzik"),
        WordEntry(word: "BALE", category: "Müzik"),
        WordEntry(word: "BARİTON", category: "Müzik"),
        WordEntry(word: "BAS", category: "Müzik"),
        WordEntry(word: "BATERİ", category: "Müzik"),
        WordEntry(word: "BESTECİ", category: "Müzik"),
        WordEntry(word: "BLUES", category: "Müzik"),
        WordEntry(word: "CAZ", category: "Müzik"),
        WordEntry(word: "ÇELLO", category: "Müzik"),
        WordEntry(word: "CÜMBÜŞ", category: "Müzik"),
        WordEntry(word: "DARBUKA", category: "Müzik"),
        WordEntry(word: "DAVUL", category: "Müzik"),
        WordEntry(word: "ELEKTRO GİTAR", category: "Müzik"),
        WordEntry(word: "FLÜT", category: "Müzik"),
        WordEntry(word: "GİTAR", category: "Müzik"),
        WordEntry(word: "KAVAL", category: "Müzik"),
        WordEntry(word: "KEMAN", category: "Müzik"),
        WordEntry(word: "KLARNET", category: "Müzik"),
        WordEntry(word: "KONÇERTO", category: "Müzik"),
        WordEntry(word: "KONSER", category: "Müzik"),
        WordEntry(word: "KONTRBAS", category: "Müzik"),
        WordEntry(word: "KORO", category: "Müzik"),
        WordEntry(word: "MANDOLİN", category: "Müzik"),
        WordEntry(word: "MELODİ", category: "Müzik"),
        WordEntry(word: "MİKROFON", category: "Müzik"),
        WordEntry(word: "NAKARAT", category: "Müzik"),
        WordEntry(word: "NEY", category: "Müzik"),
        WordEntry(word: "NOTA", category: "Müzik"),
        WordEntry(word: "OBUA", category: "Müzik"),
        WordEntry(word: "OPERA", category: "Müzik"),
        WordEntry(word: "ORKESTRA", category: "Müzik"),
        WordEntry(word: "PİYANO", category: "Müzik"),
        WordEntry(word: "RAP", category: "Müzik"),
        WordEntry(word: "RİTİM", category: "Müzik"),
        WordEntry(word: "SAHNE", category: "Müzik"),
        WordEntry(word: "SAKSOFON", category: "Müzik"),
        WordEntry(word: "SENFONİ", category: "Müzik"),
        WordEntry(word: "SOLO", category: "Müzik"),
        WordEntry(word: "SOLİST", category: "Müzik"),
        WordEntry(word: "SOPRANO", category: "Müzik"),
        WordEntry(word: "TEMPO", category: "Müzik"),
        WordEntry(word: "TENOR", category: "Müzik"),
        WordEntry(word: "TROMBON", category: "Müzik"),
        WordEntry(word: "TROMPET", category: "Müzik"),
        WordEntry(word: "VİYOLA", category: "Müzik"),
        WordEntry(word: "ZURNA", category: "Müzik"),
    ]

    // MARK: - Hints

    static let muzikHints: [String: String] = [
        "AKOR":         "Birden fazla notanın aynı anda çalınmasıyla oluşan ahenk grubu.",
        "AKORDEON":     "Körük mekanizmalı, klavyeli nefes çalgısı.",
        "ALBÜM":        "Bir sanatçının parçalarını bir araya getirdiği müzik koleksiyonu.",
        "ARMONİ":       "Birlikte uyum içinde duyulan ses gruplarının teorik incelemesi.",
        "ARPA":         "Dik duran, çok telli ve üçgen görünümlü yaylı çalgı.",
        "BAĞLAMA":      "Türk halk müziğinin simgesi, uzun saplı telli çalgı.",
        "BALE":         "Klasik müzikle birleşen, teknik dans hareketiyle anlatım sanatı.",
        "BARİTON":      "Tenor ile bas arasındaki orta erkek ses türü.",
        "BATERİ":       "Davul, zil ve çeşitli vurmalı aletlerden oluşan bütünleşik ritim seti.",
        "BESTECİ":      "Müzik eserleri yazan, notaya döken sanatçı.",
        "BLUES":        "Afrikalı Amerikalıların duygularını aktardığı, cazın kökenindeki müzik türü.",
        "CAZ":          "Doğaçlama ve ritim ağırlıklı, özgür ruhlu Amerikan müzik türü.",
        "ÇELLO":        "Yay ile çalınan, derin sesi olan orta büyüklükte telli çalgı.",
        "CÜMBÜŞ":       "Metalik gövdeli, sazdan evrilmiş Türk çalgısı.",
        "DARBUKA":      "El ile çalınan, kadeh şeklinde Orta Doğu kökenli vurmalı çalgı.",
        "DAVUL":        "İki tarafından tokmakla vurulan büyük silindir biçimli vurmalı çalgı.",
        "FLÜT":         "Yatay tutulan, delik kapatılarak çalınan tahta nefes çalgısı.",
        "GİTAR":        "Altı telli, parmak veya pena ile çalınan en popüler çalgı.",
        "KAVAL":        "Türk halk müziğinde kullanılan, üflemeli, delik kapaklı nefes çalgısı.",
        "KEMAN":        "Yay çekerek çalınan, dört telli klasik müzik çalgısı.",
        "KLARNET":      "Tek kamışlı, silindirik gövdeli tahta nefes çalgısı.",
        "KONÇERTO":     "Solistin orkestra eşliğinde çaldığı büyük klasik müzik eseri.",
        "KONSER":       "Sanatçıların canlı olarak müzik icra ettiği sahne gösterisi.",
        "KONTRBAS":     "Yay ailesinin en büyük ve en kalın sesli üyesi.",
        "KORO":         "Birlikte şarkı söyleyen büyük ses topluluğu.",
        "MANDOLİN":     "8 telli, küçük gövdeli, pena ile çalınan telli çalgı.",
        "MELODİ":       "Kulağa hoş gelen ardışık nota dizisi.",
        "MİKROFON":     "Ses dalgalarını elektrik sinyaline çeviren kayıt ve yayın aleti.",
        "NAKARAT":      "Şarkının her bölümün sonunda tekrarlanan ana kıtası.",
        "NEY":          "Kamıştan yapılmış, tasavvuf müziğinin simgesi üflemeli çalgı.",
        "NOTA":         "Müzikal sesi ya da süresini temsil eden yazılı sembol.",
        "OBUA":         "Çift kamışlı, keskin sesli tahta orkestra nefes çalgısı.",
        "OPERA":        "Sahne, kostüm ve dramayı müzikle buluşturan büyük gösterim sanatı.",
        "ORKESTRA":     "Çok sayıda müzisyenin birlikte çaldığı büyük çalgı topluluğu.",
        "PİYANO":       "88 tuşlu, çekiçlerin tele vurmasıyla ses çıkaran klavyeli çalgı.",
        "RAP":          "Söz yazarlığını ritimle buluşturan, hız ve uyak ön plana çıkan müzik türü.",
        "RİTİM":        "Müzikte vurgular ve sessizliklerin düzenli örüntüsü.",
        "SAKSOFON":     "Metal gövdeli, kamışlı, cazda sıkça kullanılan nefes çalgısı.",
        "SENFONİ":      "Orkestranın birden fazla bölümde icra ettiği büyük klasik müzik yapıtı.",
        "SOPRANO":      "Kadın seslerinin en tizini, opera ve korolarda öne çıkan ses türü.",
        "TEMPO":        "Müziğin ne kadar hızlı ya da yavaş çalındığını belirleyen ölçü.",
        "TENOR":        "Erkek seslerinin en tiz olanı, operada ana rollerde tercih edilir.",
        "TROMBON":      "Kaydırmalı çekme kolu ile ses yüksekliği ayarlanan pirinç nefes çalgısı.",
        "TROMPET":      "Parlak ve güçlü tonuyla dikkat çeken pirinç üflemeli çalgı.",
        "VİYOLA":       "Kemandan biraz büyük, daha kalın tonda yay çalgısı.",
        "ZURNA":        "Düğünlerde davulla birlikte çalınan ince dilli nefes çalgısı.",
        "ELEKTRO GİTAR":"Manyetik pikap yardımıyla sesi yükseltilen, rock müziğin simgesi.",
    ]
}
